export enum DocumentIndexingTypeEnum {
  NEW_DOCUMENT = 'NEW_DOCUMENT',
  UPLOADED_DOCUMENT = 'UPLOADED_DOCUMENT',
  UPDATED_DOCUMENT = 'UPDATED_DOCUMENT',
  UPLOADED_GOOGLE_DOCUMENT = 'UPLOADED_GOOGLE_DOCUMENT',
}
