export enum ENV {
  LUMIN_BASE_URL = "LUMIN_BASE_URL",
  LUMIN_WEBOPT_PREFIX = "LUMIN_WEBOPT_PREFIX",
  LUMIN_VERSION = "LUMIN_VERSION",
  LUMIN_ENVIRONMENT_NAME = "LUMIN_ENVIRONMENT_NAME",
  LUMIN_PDF_BACKEND_URL = "LUMIN_PDF_BACKEND_URL",
  LUMIN_PDF_APP_URL = "LUMIN_PDF_APP_URL",
  LUMIN_KRATOS_URL = "LUMIN_KRATOS_URL",
  LUMIN_AUTH_SERVICE_URL = "LUMIN_AUTH_SERVICE_URL",
  LUMIN_STATIC_PAGE_URL = "LUMIN_STATIC_PAGE_URL",
  LUMIN_AUTHOR_JWT_EXPIRED_AT = "LUMIN_AUTHOR_JWT_EXPIRED_AT",
  LUMIN_DATADOG_CLIENT_TOKEN = "LUMIN_DATADOG_CLIENT_TOKEN",
}
