export enum DetectionErrorCodes {
  DOWNLOAD_ERROR = 'DOWNLOAD_ERROR',
  UNSUPPORTED_FILE_TYPE = 'UNSUPPORTED_FILE_TYPE',
  PARSE_ERROR = 'PARSE_ERROR',
  MODAL_PREDICT_ERROR = 'MODAL_PREDICT_ERROR',
  THIRD_PARTY_ERROR = 'THIRD_PARTY_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
