import { LayoutElements } from 'lumin-components/GeneralLayout/constants';
import { PasswordModalSource } from 'lumin-components/PasswordModal/constants/PasswordModal.enum';
import {
  LEFT_PANEL_VALUES,
  TOOL_PROPERTIES_VALUE,
} from 'luminComponents/GeneralLayout/components/LuminLeftPanel/constants';
import { LEFT_SIDE_BAR_VALUES } from 'luminComponents/GeneralLayout/components/LuminLeftSideBar/constants';

import getHashParams from 'helpers/getHashParams';

import { ButtonName } from 'utils/Factory/EventCollection/constants/ButtonEvent';
import { getLanguage } from 'utils/getLanguage';

import { SortValues, ShowValues } from 'features/Comments/constants';

import { BannerNames, AnimationBanner } from 'constants/banner';
import {
  ownerFilter,
  modifiedFilter,
  COMMENT_PANEL_LAYOUT_STATE,
  DOCUMENT_CONTENT_EDIT_TYPE,
  folderType,
  PageToolViewMode,
} from 'constants/documentConstants';
import UserEventConstants from 'constants/eventConstants';
import { CONTENT_EDIT_TOOL, SELECT_TOOLS, VIEW_TOOLS } from 'constants/headerItems';
import { LANGUAGES } from 'constants/language';
import { LocalStorageKey } from 'constants/localStorageKey';
import { RESOLUTION_TYPE, DIVIDER_ID } from 'constants/lumin-common';
import { copyMapWithDataProperties } from 'constants/map';
import { NotificationTabs } from 'constants/notificationConstant';
import { PremiumToolsPopOverEvent } from 'constants/premiumToolsPopOverEvent';
import { Routers } from 'constants/Routers';
import { ModalPlacement } from 'constants/styles';

import initialDocumentListState from './states/initialDocumentListState';
import DATA_ELEMENT from '../screens/Viewer/dataElement.constant';

const TOOL_GROUP_BUTTON_HAS_MARGIN = 'ToolGroupButton--has-margin';
const TOOL_BUTTON_ARROW_HAS_MARGIN = 'ToolButtonArrowDropdown--has-margin';
const TOOL_BUTTON_HAS_MARGIN = 'ToolButton--has-margin';
const TITLE_COUNT_MEASUREMENT = 'annotation.countMeasurement';
const TITLE_AREA_MEASUREMENT = 'annotation.areaMeasurement';
const ICON_REDACTION = 'tool-redaction';

export default {
  viewer: {
    docViewer: {},
    CoreControls: {},
    disabledElements: {},
    disabledFeatures: {},
    openElements: {
      header: true,
      leftPanel: false,
      rightPanel: false,
    },
    openedElementData: {},
    isPageEditMode: false,
    isPreviewOriginalVersionMode: false,
    signatureStatus: {
      isFetching: false,
      signatureQueue: [],
      isSyncing: false,
      hasNext: true,
      isFetchedAfterMount: false,
    },
    selectedSignature: null,
    isPlacingMultipleSignatures: false,
    isPlacingMultipleRubberStamp: !!JSON.parse(localStorage.getItem(LocalStorageKey.IS_PLACING_MULTIPLE_RUBBER_STAMP)),
    isActiveEditMode: false,
    themeMode: window.localStorage.getItem('themeMode') || 'light',
    pageEditMode: {
      displayMode: PageToolViewMode.GRID,
    },
    isShowTopBar: true,
    isShowToolbarTablet: true,
    isShowBannerAds: false,
    isShowTopViewerBanner: false,
    isMinimizeBananaSign: false,
    forceReload: false,
    discardContentEdit: false,
    uploadDocVisible: {},
    modalToolType: '',
    isOpenQRCode: false,
    headers: {
      lumin: [
        ...SELECT_TOOLS,
        {
          type: 'actionUndo',
          icon: 'tool-undo icon__18',
          dataElement: DATA_ELEMENT.UNDO,
          title: 'annotation.undo',
          className: TOOL_GROUP_BUTTON_HAS_MARGIN,
          eventTrackingName: UserEventConstants.Events.HeaderButtonsEvent.UNDO,
        },
        {
          type: 'actionRedo',
          icon: 'tool-redo icon__18',
          dataElement: DATA_ELEMENT.REDO,
          title: 'annotation.redo',
          eventTrackingName: UserEventConstants.Events.HeaderButtonsEvent.REDO,
        },
        { type: 'divider' },
        ...VIEW_TOOLS,
        {
          type: 'actionButton',
          icon: 'rotate-counter-clockwise icon__18',
          title: 'action.rotateCounterClockwise',
          dataElement: 'rotateCounterClockwiseButton',
        },
        {
          type: 'divider',
          hidden: [DOCUMENT_CONTENT_EDIT_TYPE.LIMIT_VERSION],
        },
        { type: 'divider' },
        {
          type: 'toolGroupButton',
          toolGroup: 'highlightTools',
          dataElement: 'highlightToolButton',
          title: 'component.highlightToolsButton',
          toolTipTitle: 'Highlight Color',
          toolTipContent: 'documentPage.tooltipHighlightColor',
          wrapperClass: TOOL_BUTTON_ARROW_HAS_MARGIN,
          showColor: 'active',
          isRenderOnTablet: true,
          hidden: [RESOLUTION_TYPE.TABLET_AND_MOBILE],
          permissionRequired: true,
        },
        {
          type: 'toolGroupButton',
          toolGroup: 'textTools',
          dataElement: 'textToolGroupButton',
          title: 'component.textToolsButton',
          showColor: 'active',
          isRenderOnTablet: true,
          hidden: [RESOLUTION_TYPE.TABLET_AND_MOBILE],
          eventTrackingName: UserEventConstants.Events.HeaderButtonsEvent.TEXT_TOOLS,
          permissionRequired: true,
        },
        {
          type: 'divider',
          isRenderOnTablet: true,
          hidden: [RESOLUTION_TYPE.TABLET_AND_MOBILE],
        },
        {
          type: 'toolButtonArrowDropdown',
          toolName: 'AnnotationCreateFreeText',
          dataElement: 'freeTextToolButton',
          toolTipTitle: 'Free text options',
          toolTipContent: 'documentPage.tooltipFreeTextOptions',
          wrapperClass: TOOL_BUTTON_ARROW_HAS_MARGIN,
          hidden: [RESOLUTION_TYPE.TABLET_AND_MOBILE],
          isRenderOnTablet: true,
          eventTrackingName: UserEventConstants.Events.HeaderButtonsEvent.FREE_TEXT,
          permissionRequired: true,
        },
        {
          type: 'toolButtonArrowDropdown',
          toolName: 'AnnotationCreateFreeHand',
          dataElement: 'freeHandToolGroupButton',
          toolTipTitle: 'Free hand options',
          toolTipContent: 'documentPage.tooltipFreehandOptions',
          wrapperClass: TOOL_BUTTON_ARROW_HAS_MARGIN,
          hidden: [RESOLUTION_TYPE.TABLET_AND_MOBILE],
          isRenderOnTablet: true,
          eventTrackingName: UserEventConstants.Events.HeaderButtonsEvent.FREE_HAND_TOOL,
          permissionRequired: true,
        },
        {
          type: 'toolGroupButton',
          toolGroup: 'shapeTools',
          dataElement: 'shapeToolGroupButton',
          title: 'component.shapeToolsButton',
          showColor: 'active',
          wrapperClass: TOOL_BUTTON_ARROW_HAS_MARGIN,
          hidden: [RESOLUTION_TYPE.TABLET_AND_MOBILE],
          isRenderOnTablet: true,
          eventTrackingName: UserEventConstants.Events.HeaderButtonsEvent.SHAPE_TOOLS,
          permissionRequired: true,
        },
        // Erase tool
        {
          type: 'toolButtonArrowDropdown',
          icon: 'tool-eraser',
          toolName: 'AnnotationEraserTool',
          dataElement: 'eraserToolButton',
          title: 'annotation.eraser',
          toolTipTitle: 'Eraser Size',
          toolTipContent: 'documentPage.tooltipEraserSize',
          wrapperClass: TOOL_BUTTON_ARROW_HAS_MARGIN,
          hidden: [RESOLUTION_TYPE.TABLET_AND_MOBILE],
          isRenderOnTablet: true,
          eventTrackingName: UserEventConstants.Events.HeaderButtonsEvent.ERASER,
          permissionRequired: true,
        },
        {
          type: 'toolButton',
          toolName: 'AnnotationCreateStamp',
          dataElement: 'stampToolButton',
          hidden: [RESOLUTION_TYPE.TABLET_AND_MOBILE],
          isRenderOnTablet: true,
          eventTrackingName: UserEventConstants.Events.HeaderButtonsEvent.IMAGE,
          permissionRequired: true,
        },
        {
          type: 'toolButton',
          dataElement: 'rubberStampToolButton',
          toolName: 'AnnotationCreateRubberStamp',
          hidden: [RESOLUTION_TYPE.SMALL_DESKTOP],
          icon: 'tool-rubber-stamp',
          wrapperClass: TOOL_BUTTON_HAS_MARGIN,
          isRenderOnTablet: true,
          'data-lumin-btn-name': ButtonName.RUBBER_STAMP,
          eventTrackingName: UserEventConstants.Events.HeaderButtonsEvent.RUBBER_STAMP,
          permissionRequired: true,
          premiumRequired: true,
          eventName: PremiumToolsPopOverEvent.RubberStamp,
        },
        {
          id: DIVIDER_ID.ONE,
          type: 'divider',
          hidden: [RESOLUTION_TYPE.TABLET_AND_MOBILE],
          isRenderOnTablet: true,
        },
        {
          type: 'statefulButton',
          dataElement: 'signatureToolButton',
          hidden: [RESOLUTION_TYPE.SMALL_DESKTOP],
          isRenderOnTablet: true,
          'data-lumin-btn-name': ButtonName.SIGNATURE_TOOL,
          eventTrackingName: UserEventConstants.Events.HeaderButtonsEvent.SIGNATURE_TOOL,
          permissionRequired: true,
        },
        {
          type: 'toolButton',
          icon: ICON_REDACTION,
          toolName: 'AnnotationCreateRedaction',
          dataElement: 'redactionButton',
          wrapperClass: TOOL_BUTTON_HAS_MARGIN,
          hidden: [RESOLUTION_TYPE.SMALL_DESKTOP],
          isRenderOnTablet: true,
          'data-lumin-btn-name': ButtonName.REDACTION,
          permissionRequired: true,
          premiumRequired: true,
          eventTrackingName: ButtonName.REDACTION,
          eventName: PremiumToolsPopOverEvent.Redaction,
        },
        {
          type: 'toggleElementButton',
          element: 'rightPanelFormBuild',
          toolName: 'FormBuilder',
          title: 'annotation.formBuilder',
          icon: 'form-build-tool',
          'data-lumin-btn-name': ButtonName.FORM_BUILDER_OPEN,
          hidden: [RESOLUTION_TYPE.SMALL_DESKTOP],
          wrapperClass: TOOL_BUTTON_HAS_MARGIN,
          isRenderOnTablet: true,
          permissionRequired: true,
          premiumRequired: true,
          eventTrackingName: ButtonName.FORM_BUILDER_OPEN,
          eventName: PremiumToolsPopOverEvent.FormBuilder,
        },
        {
          type: 'toolButton',
          dataElement: 'dateFreeTextToolButton',
          toolName: 'AnnotationCreateDateFreeText',
          hidden: [RESOLUTION_TYPE.SMALL_DESKTOP],
          wrapperClass: TOOL_BUTTON_HAS_MARGIN,
          isRenderOnTablet: true,
          permissionRequired: true,
        },
        {
          id: DIVIDER_ID.TWO,
          type: 'divider',
          hidden: [RESOLUTION_TYPE.SMALL_DESKTOP],
          isRenderOnTablet: true,
        },
        ...CONTENT_EDIT_TOOL,
        {
          type: 'toolButtonArrowDropdown',
          toolName: 'AnnotationCreateSticky',
          dataElement: 'stickyToolButton',
          hidden: [RESOLUTION_TYPE.SMALL_DESKTOP],
          isRenderOnTablet: true,
          eventTrackingName: UserEventConstants.Events.HeaderButtonsEvent.COMMENT,
          permissionRequired: true,
        },
        {
          type: 'toggleElementButton',
          element: 'rightPanelComment',
          title: 'common.commentsHistory',
          icon: 'comments',
          hidden: [RESOLUTION_TYPE.SMALL_DESKTOP],
          isRenderOnTablet: true,
          eventTrackingName: UserEventConstants.Events.HeaderButtonsEvent.COMMENT_HISTORY,
        },
        {
          type: 'divider',
          hidden: [RESOLUTION_TYPE.SMALL_DESKTOP],
          isRenderOnTablet: true,
        },
        {
          type: 'toggleElementButton',
          dataElement: 'searchButton',
          element: 'searchOverlay',
          icon: 'search-thinner icon__18',
          title: 'component.searchOverlay',
          hidden: [RESOLUTION_TYPE.SMALL_DESKTOP],
          isRenderOnTablet: true,
          eventTrackingName: UserEventConstants.Events.HeaderButtonsEvent.SEARCH_BOX,
        },
        { type: 'moreButton' },
        { type: 'spacer' },
        { type: 'pageManipulation' },
        { type: 'fullScreenButton' },
        { type: 'divider' },
        { type: 'hideTopViewer' },
      ],
      editPDF: [
        ...SELECT_TOOLS,
        ...VIEW_TOOLS,
        {
          type: 'toolButton',
          icon: 'add-paragraph',
          toolName: 'AddParagraphTool',
          dataElement: 'AddParagraph',
        },
      ],
    },
    annotationPopup: [
      { dataElement: 'bringToFrontButton' },
      { dataElement: 'sendToBackButton' },
      { dataElement: 'divider' },
      { dataElement: 'annotationCommentButton' },
      { dataElement: 'annotationDateEditButton' },
      { dataElement: 'annotationRedactButton' },
      { dataElement: 'annotationStyleEditButton' },
      { dataElement: 'annotationCropButton' },
      { dataElement: 'annotationGroupButton' },
      { dataElement: 'annotationContentEditButton' },
      { dataElement: 'annotationUngroupButton' },
      { dataElement: 'annotationDeleteButton' },
      { dataElement: 'calibrateButton' },
      { dataElement: 'linkButton' },
      { dataElement: 'navigateLinkButton' },
      { dataElement: 'fileAttachmentDownload' },
    ],
    textPopup: [
      { dataElement: 'stickyToolButton' },
      { dataElement: 'copyTextButton' },
      { dataElement: 'textRedactToolButton' },
      { dataElement: 'textHighlightToolButton' },
      { dataElement: 'textUnderlineToolButton' },
      { dataElement: 'textSquigglyToolButton' },
      { dataElement: 'textStrikeoutToolButton' },
      { dataElement: 'linkButton' },
    ],
    contextMenuPopup: [
      { dataElement: 'panToolButton' },
      { dataElement: 'stickyToolButton' },
      { dataElement: 'highlightToolButton' },
      { dataElement: 'freeHandToolButton' },
      { dataElement: 'freeTextToolButton' },
    ],
    toolButtonObjects: {
      AnnotationCreateCountMeasurement: {
        dataElement: 'countMeasurementToolButton',
        title: TITLE_COUNT_MEASUREMENT,
        img: 'ic_check_black_24px',
        group: 'countTools',
        showColor: 'always',
      },
      AnnotationCreateCountMeasurement2: {
        dataElement: 'countMeasurementToolButton2',
        title: TITLE_COUNT_MEASUREMENT,
        img: 'ic_check_black_24px',
        group: 'countTools',
        showColor: 'always',
      },
      AnnotationCreateCountMeasurement3: {
        dataElement: 'countMeasurementToolButton3',
        title: TITLE_COUNT_MEASUREMENT,
        img: 'ic_check_black_24px',
        group: 'countTools',
        showColor: 'always',
      },
      AnnotationCreateCountMeasurement4: {
        dataElement: 'countMeasurementToolButton4',
        title: TITLE_COUNT_MEASUREMENT,
        img: 'ic_check_black_24px',
        group: 'countTools',
        showColor: 'always',
      },
      AnnotationCreateDistanceMeasurement: {
        dataElement: 'distanceMeasurementToolButton',
        title: 'annotation.distanceMeasurement',
        icon: 'fullscreen',
        group: 'measurementTools',
        showColor: 'active',
      },
      AnnotationCreatePerimeterMeasurement: {
        dataElement: 'perimeterMeasurementToolButton',
        title: 'annotation.perimeterMeasurement',
        icon: 'annotation-perimeter',
        group: 'measurementTools',
        showColor: 'active',
      },
      AnnotationCreateAreaMeasurement: {
        dataElement: 'areaMeasurementToolButton',
        title: TITLE_AREA_MEASUREMENT,
        img: 'annotation-area',
        group: 'measurementTools',
        showColor: 'active',
      },
      AnnotationCreateEllipseMeasurement: {
        dataElement: 'ellipseMeasurementToolButton',
        title: TITLE_AREA_MEASUREMENT,
        img: 'ic_annotation_ellipse_area_black',
        group: 'measurementTools',
        showColor: 'active',
      },
      AnnotationCreateFreeHand: {
        dataElement: 'freeHandToolButton',
        title: 'annotation.freehand',
        icon: 'tool-freehand',
        group: 'freeHandTools',
        showColor: 'always',
      },
      AnnotationCreateTextHighlight: {
        dataElement: 'highlightToolButton',
        title: 'annotation.highlight',
        icon: 'tool-highlight',
        group: 'highlightTools',
        showColor: 'always',
      },
      AnnotationCreateFreeHandHighlight: {
        dataElement: 'freehandHighlightToolButton',
        title: 'annotation.freehandHighlight',
        icon: 'tool-freehand-highlight',
        group: 'highlightTools',
        showColor: 'always',
      },
      AnnotationCreateTextUnderline: {
        dataElement: 'underlineToolButton',
        title: 'annotation.underline',
        icon: 'underline-tool',
        group: 'textTools',
        showColor: 'active',
        newIcon: 'md_text_underline',
      },
      AnnotationCreateTextSquiggly: {
        dataElement: 'squigglyToolButton',
        title: 'annotation.squiggly',
        icon: 'tool-squiggly',
        group: 'textTools',
        showColor: 'active',
        newIcon: 'md_squiggly',
      },
      AnnotationCreateTextStrikeout: {
        dataElement: 'strikeoutToolButton',
        title: 'annotation.strikeout',
        icon: 'tool-strike',
        group: 'textTools',
        showColor: 'active',
        newIcon: 'md_text_strike_through',
      },
      AnnotationCreateRectangle: {
        dataElement: 'rectangleToolButton',
        title: 'annotation.rectangle',
        icon: 'tool-rectangle',
        group: 'shapeTools',
        showColor: 'active',
        newIcon: 'md_rectangle',
      },
      AnnotationCreateEllipse: {
        dataElement: 'ellipseToolButton',
        title: 'annotation.ellipse',
        icon: 'tool-ellipse',
        group: 'shapeTools',
        showColor: 'active',
        newIcon: 'md_ellipse',
      },
      AnnotationCreateLine: {
        dataElement: 'lineToolButton',
        title: 'annotation.line',
        icon: 'tool-line',
        group: 'shapeTools',
        showColor: 'active',
        newIcon: 'md_line',
      },
      AnnotationCreateArrow: {
        dataElement: 'arrowToolButton',
        title: 'annotation.arrow',
        icon: 'arrow',
        group: 'shapeTools',
        showColor: 'active',
        newIcon: 'md_arrow',
      },
      AnnotationCreatePolyline: {
        dataElement: 'polylineToolButton',
        title: 'annotation.polyline',
        icon: 'tool-polyline',
        group: 'shapeTools',
        showColor: 'active',
        newIcon: 'md_polyline',
      },
      AnnotationCreatePolygon: {
        dataElement: 'polygonToolButton',
        title: 'annotation.polygon',
        icon: 'tool-polygon',
        group: 'shapeTools',
        showColor: 'active',
        newIcon: 'md_polygon',
      },
      AnnotationCreatePolygonCloud: {
        dataElement: 'cloudToolButton',
        title: 'annotation.polygonCloud',
        icon: 'tool-cloud',
        group: 'shapeTools',
        showColor: 'active',
        newIcon: 'md_cloud',
      },
      AnnotationCreateStar: {
        dataElement: 'starToolButton',
        title: 'annotation.star',
        icon: 'star-empty',
        group: 'shapeTools',
        showColor: 'active',
        newIcon: 'md_star',
      },
      AnnotationCreateCross: {
        dataElement: 'crossToolButton',
        title: 'annotation.cross',
        icon: 'cancel',
        group: 'shapeTools',
        showColor: 'active',
        newIcon: 'md_cross',
      },
      AnnotationCreateTick: {
        dataElement: 'tickToolButton',
        title: 'annotation.tick',
        icon: 'check',
        group: 'shapeTools',
        showColor: 'active',
        newIcon: 'md_tick',
      },
      AnnotationCreateRedaction: {
        dataElement: 'redactionButton',
        title: 'component.redaction',
        icon: ICON_REDACTION,
        showColor: 'active',
      },
      AnnotationCreateSignature: {
        dataElement: 'signatureToolButton',
        title: 'annotation.signature',
        icon: 'tool-signature',
        showColor: 'active',
      },
      AnnotationCreateRubberStamp: {
        dataElement: 'rubberStampToolButton',
        title: 'annotation.rubberStamp',
        icon: 'tool-rubber-stamp',
        showColor: 'active',
      },
      AnnotationCreateFreeText: {
        dataElement: 'freeTextToolButton',
        title: 'annotation.freetext',
        icon: 'tool-freetext',
        showColor: 'active',
      },
      AnnotationCreateSticky: {
        dataElement: 'stickyToolButton',
        title: 'annotation.stickyNote',
        icon: 'add-comment',
        showColor: 'active',
      },
      AnnotationCreateStamp: {
        dataElement: 'stampToolButton',
        title: 'annotation.image',
        icon: 'tool-stamp',
        group: '',
        showColor: 'active',
      },
      ContentEditTool: {
        dataElement: 'contentEditButton',
        title: 'annotation.contentEdit',
        img: 'ic_edit_page_24px',
        showColor: 'never',
        group: 'contentEditTools',
      },
      FormBuilder: {
        dataElement: 'formBuilderButton',
        title: 'annotation.formBuilder',
        img: 'form-build-tool',
        group: 'FormBuilder',
      },
      AnnotationCreateFileAttachment: {
        dataElement: 'fileAttachmentToolButton',
        title: 'annotation.fileattachment',
        img: 'ic_fileattachment_24px',
        group: 'miscTools',
        showColor: 'active',
      },
      [window.Core.Tools.ToolNames.RECTANGULAR_AREA_MEASUREMENT]: {
        dataElement: 'rectangularAreaMeasurementToolButton',
        title: TITLE_AREA_MEASUREMENT,
        img: 'ic_annotation_rectangular_area_black_24px',
        group: 'measurementTools',
        showColor: 'active',
      },
      Pan: {
        dataElement: 'panToolButton',
        title: 'tool.pan',
        icon: 'hand',
        showColor: 'never',
      },
      TextSelect: {
        dataElement: 'textSelectButton',
        icon: 'cursor',
        showColor: 'never',
      },
      MarqueeZoomTool: {
        dataElement: 'marqueeToolButton',
        icon: 'image',
        showColor: 'never',
      },
      AnnotationEraserTool: {
        dataElement: 'eraserToolButton',
        title: 'annotation.eraser',
        icon: 'annotation-eraser',
        showColor: 'never',
      },
      AnnotationCreateDateFreeText: {
        dataElement: 'dateFreeTextToolButton',
        title: 'annotation.dateStamp',
        icon: 'calendar',
        showColor: 'active',
      },
      AddParagraphTool: {
        dataElement: 'AddParagraph',
        title: 'annotation.addParagraph',
        icon: 'add-paragraph',
        showColor: 'never',
      },
    },
    activeHeaderGroup: 'lumin',
    tab: {
      signatureModal: 'inkSignaturePanelButton',
      linkModal: 'URLPanelButton',
    },
    customElementOverrides: {},
    activeToolName: 'AnnotationEdit',
    activeToolStyles: {},
    activeLeftPanel: '',
    activeToolGroup: '',
    notePopupId: '',
    isNoteEditing: false,
    noteEditingAnnotationId: '',
    fitMode: '',
    zoom: 1.5,
    rotation: 0,
    displayMode: 'Single',
    currentPage: 1,
    sortStrategy: SortValues.POSITION,
    showNotesOption: ShowValues.SHOW_ALL,
    isFullScreen: false,
    presenterMode: {
      isInPresenterMode: false,
      restoreState: null,
    },
    isMultipleViewerMerging: false,
    isThumbnailMerging: true,
    isThumbnailReordering: true,
    isThumbnailMultiselect: true,
    initialWidgetXfdf: '',
    allowPageNavigation: true,
    enableMouseWheelZoom: true,
    doesAutoLoad: getHashParams('auto_load', true),
    isReadOnly: getHashParams('readonly', false),
    customPanels: [],
    useEmbeddedPrint: true,
    pageLabels: [],
    selectedThumbnailPageIndexes: [],
    noteDateFormat: 'MMM DD, YYYY. HH:mm',
    colorMap: copyMapWithDataProperties('currentPalette', 'iconColor'),
    warning: {},
    customNoteFilter: null,
    zoomList: [0.1, 0.25, 0.5, 1, 1.25, 1.5, 2, 4, 8, 16, 64],
    isAccessibleMode: getHashParams('accessibleMode', false),
    measurementUnits: {
      from: ['in', 'mm', 'cm', 'pt'],
      to: ['in', 'mm', 'cm', 'pt', 'ft', 'm', 'yd', 'km', 'mi'],
    },
    maxSignaturesCount: 2,
    signatureFonts: ['GreatVibes-Regular'],
    isSavingSignature: false,
    leftPanelWidth: 300,
    isReplyDisabledFunc: null,
    userData: [],
    customMeasurementOverlay: [],
    noteTransformFunction: null,
    annotationContentOverlayHandler: null,
    triggerHidden: false,
    annotationsLoaded: false,
    isNotFoundDocument: false,
    commentPlacement: {
      idealPlacement: {},
      originLocation: [],
      selectedCommentId: '',
    },
    gridViewMode: {
      isScroll: false,
      pageToScroll: 0,
    },
    autoSyncStatus: '',
    currentContentBeingEdited: null,
    signatureWidgetSelected: null,
    hasAppliedRedaction: false,
    commentPanelLayoutState: COMMENT_PANEL_LAYOUT_STATE.NORMAL,
    isInContentEditMode: false,
    isUsingRichText: false,
    editPdfVersion: DOCUMENT_CONTENT_EDIT_TYPE.LIMIT_VERSION,
    shouldShowRating: AnimationBanner.DEFAULT,
    isLoadingDocument: true,
    isDocumentLoaded: false,
    internalAnnotationIds: [],
    viewerLoadingModalData: {
      totalSteps: null,
      currentStep: 0,
      renderStatus: () => 'Processing...',
      onCancel: null,
      isShowPercentage: false,
      size: 'medium',
      circularSize: 84,
      progressSuffix: '',
      variant: '',
    },
    integrateModal: {
      isOpenIntegrateModal: false,
      isOpenSignModal: false,
    },
    isConvertingBase64ToSignedUrl: false,
    shouldShowOCRBanner: false,
    rubberStamp: {
      rubberStamps: [],
      page: 0,
      total: 0,
      skip: 0,
      shouldFetchOnInit: true,
    },
    showLoadingDocumentWarn: false,
    downloadType: 'pdf',
    toolAutoEnabled: '',
    isDocumentReady: false,
    activeOutlineEvent: null,
    isLoadingGetDocumentOutlines: false,
    isSummarizing: false,
    isRegeneratingSummary: false,
    currentSummaryDocVersion: null,
    backDropMessage: '',
    isExceedQuotaExternalStorage: false,
    externalQuotaSpace: {
      total: 0,
      used: 0,
      remaining: 0,
    },
    shouldShowInviteCollaboratorsModal: false,
    showTrialModal: true,
    flattenPdf: false,
  },
  search: {
    listeners: [],
    value: '',
    isCaseSensitive: false,
    isWholeWord: false,
    isWildcard: false,
    isRegex: false,
    isSearchUp: false,
    isAmbientString: false,
    activeResult: null,
    activeResultIndex: -1,
    results: [],
    isSearching: false,
    noResult: false,
    isProgrammaticSearch: false,
    isProgrammaticSearchFull: false,
  },
  document: {
    totalPages: 0,
    outlines: {
      children: [],
      model: {
        children: [],
      },
    },
    bookmarks: [],
    layers: [],
    printQuality: 1,
    passwordAttempts: -1,
    passwordProtectedDocumentName: '',
    passwordMessage: '',
    passwordModalSource: PasswordModalSource.UNLOCK,
    loadingProgress: 0,
    lumin_thumbs: [],
    newlyPagesAdded: [],
    allNewlyPagesAdded: [],
    lumin_careTaker: null,
  },
  user: {
    name: getHashParams('user', 'Guest'),
    isAdmin: getHashParams('admin', false),
    disablePwaDownload: true,
    userSignatures: [],
  },
  advanced: {
    customCSS: getHashParams('css', null),
    defaultDisabledElements: getHashParams('disabledElements', ''),
    fullAPI: getHashParams('pdfnet', true),
    preloadWorker: getHashParams('preloadWorker', false),
    serverUrl: getHashParams('server_url', ''),
    serverUrlHeaders: JSON.parse(getHashParams('serverUrlHeaders', '{}')),
    useSharedWorker: getHashParams('useSharedWorker', false),
    disableI18n: getHashParams('disableI18n', false),
    pdfWorkerTransportPromise: null,
    officeWorkerTransportPromise: null,
  },
  // ----------------------------- Dev by Lumin ---------------------------------
  uploadingDocuments: {
    queue: [],
    files: {},
    openUploadingPopper: false,
  },
  payment: {
    isPurchasing: false,
    billingWarning: {}, // [id]: {}
  },
  modal: {
    fullScreen: false,
    open: false,
    type: 'warning',
    title: 'Default',
    message: 'Default',
    onCancel: null,
    onConfirm: () => {},
    confirmButtonTitle: 'Confirm',
    confirmButtonType: 'button',
    isCustomModal: false,
    firstButtonTitle: 'Default',
    secondButtonTitle: 'Default',
    onFirstButtonClick: () => {},
    onSecondButtonClick: () => {},
    deleteButton: 'Delete',
    disableBackdropClick: false,
    disableEscapeKeyDown: false,
    isProcessing: false,
    closeOnConfirm: true,
    checkboxMessage: '',
    cancelButtonStyle: '',
    cancelDataLumin: {},
    confirmDataLumin: {},
    hasCloseBtn: false,
    placement: ModalPlacement.CENTER,
    closeOnRouteChange: true,

    // NOTE: new layout
    size: 'medium',
    showCloseIcon: false,
    footerVariant: 'variant3',
    header: null,
    footer: null,
    content: null,
    PaperProps: {},
  },
  auth: {
    isCompletedGettingUserData: false,
    isAuthenticating: true,
    currentUser: null,
    currentDocument: null,
    isFetchingCurrentDocument: true,
    ownedFilter: ownerFilter.byAnyone,
    lastModifiedFilter: modifiedFilter.modifiedByAnyone,
    subMenuType: '',
    gapiLoaded: false,
    isOffline: false,
    isSourceDownloading: false,
    locationCurrency: {
      value: localStorage.getItem(LocalStorageKey.CURRENCY),
      loading: !localStorage.getItem(LocalStorageKey.CURRENCY),
    },
    language: window.location.pathname.includes(Routers.OPEN_LUMIN) ? LANGUAGES.EN : getLanguage(),
    wrongIpStatus: {
      open: false,
      email: null,
    },
    membershipOfOrg: {
      require: false,
      email: null,
    },
    userLocationLoaded: false,
    userSignPayment: null,
    gtmLoaded: false,
  },
  notification: {
    tab: NotificationTabs.GENERAL,
  },
  widgetNotification: {
    hasNewWidgetNotify: false,
    widgetNotificationList: [],
  },
  banner: {
    [BannerNames.COOKIES]: false,
  },
  generalLayout: {
    isRightPanelOpen: false,
    isToolPropertiesOpen: false,
    isLeftPanelOpen: false,
    toolbarValue: LEFT_SIDE_BAR_VALUES.POPULAR.value,
    leftPanelValue: LEFT_PANEL_VALUES.THUMBNAIL,
    rightPanelValue: LayoutElements.DEFAULT,
    toolPropertiesValue: TOOL_PROPERTIES_VALUE.DEFAULT,
    isOpenSearchOverlay: false,
    isCommentPanelOpen: false,
    isInFocusMode: false,
  },
  organization: {
    currentTeam: null,
    currentOrganization: {
      data: undefined,
      loading: true,
      error: null,
    },
    organizations: {
      loading: true,
      error: null,
      data: undefined,
    },
    suggestedOrganizations: {
      loading: true,
      error: null,
      data: undefined,
    }
  },
  folder: {
    currentFolder: null,
    folderList: {
      data: [],
      error: null,
      loading: true,
      total: 0,
    },
  },
  documentList: initialDocumentListState,
  report: {
    status: 'IDLE',
    urlsArray: [],
    reportData: [],
  },
  dialog: {
    open: false,
  },
  eventTracking: {
    queue: [],
    pinpointLoaded: false,
  },
  custom: {
    forceReloadVersion: false,
    error: null,
  },
  pageSearch: {
    isFocusing: false,
    searchKey: '',
    findDocumentByName: false,
  },
  home: {
    teamSelectorData: {
      selectedTeam: null,
      folderType: folderType.ORGANIZATION,
    },
  },
  multipleDownload: {
    errorDocuments: [],
    errorModal: {
      title: '',
      opened: false,
    },
    errorTypes: [],
  },
  general: {
    documentTabType: 'personal',
  },

  // ----------------------------- End dev by Lumin ---------------------------------
};
