import { DocumentSummarizationEventName, DocumentSummarizationEventPurpose } from './DocumentSummarizationEvent';

export const ButtonName = {
  PASSWORD_PROTECTION: 'passwordProtection',
  SET_PASSWORD: 'setPassword',
  CHANGE_PASSWORD: 'changePassword',
  REMOVE_PASSWORD: 'removePassword',
  ORG_PLAN_UPGRADE: 'orgPlanUpgrade',
  PLAN_PAGE_REDIRECT: 'planPageRedirect',
  LUMIN_DOWNLOAD: 'luminDownload',
  PROMOTION_FREE_TRIAL_SKIP: 'promotionFreeTrialSkip',
  PROMOTION_FREE_TRIAL_SUBMIT: 'promotionFreeTrialSubmit',
  TEACHER_PURPOSE_SELECT: 'teacherPurposeSelect',
  STUDENT_PURPOSE_SELECT: 'studentPurposeSelect',
  PERSONAL_PURPOSE_SELECT: 'personalPurposeSelect',
  SMALL_BUSINESS_PURPOSE_SELECT: 'smallBusinessPurposeSelect',
  LARGE_COMPANY_PURPOSE_SELECT: 'largeCompanyPurposeSelect',
  NON_PROFIT_PURPOSE_SELECT: 'nonProfitPurposeSelect',
  PURPOSE_SKIP: 'purposeSkip',
  INDIVIDUAL_PLAN_SWITCH: 'individiualPlanSwitch',
  ORGANIZATION_PLAN_SWITCH: 'organizationPlanSwitch',
  PROFESSIONAL_PLAN_UPGRADE: 'professionalPlanUpgrade',
  MODAL_SHARE_DOCUMENT_OPEN: 'modalShareDocumentOpen',
  SALE_EDUCATION_AND_NON_PROFIT_CONTACT: 'saleEducationAndNotProfitContact',
  ORGANIZATION_CREATION_PAGE_REDIRECT: 'organizationCreationRedirect',
  BUSINESS_PLAN_UPGRADE: 'businessPlanUpgrade',
  ENTERPRISE_FREE_QUOTE: 'enterpriseFreeQuoteGet',
  ORGANIZATION_SET_UP: 'organizationSetUp',
  ALL_FAQ_OPEN: 'allFaqOpen',
  ALL_FAQ_HIDE: 'allFaqHide',
  ORGANIZATION_CREATE: 'organizationCreate',
  ORGANIZATION_PAYMENT_PAGE_REDIRECT: 'organizationPaymentRedirect',
  ORGANIZATION_CREATION_REDIRECT_FROM_ORG_LIST: 'organizationCreationRedirectFromOrgList',
  INVITE_ORG_MEMBER_MODAL_OPEN_IN_ORG_LIST: 'inviteOrgMemberModalOpenInOrgList',
  ORG_DASHBOARD_REDIRECT_FROM_ORG_LIST: 'orgDashboardRedirectFromOrgList',
  FREE_TRIAL_PAGE_REDIRECT: 'freeTrialPageRedirect',
  PERSONAL_ACTIVITIES_DASHBOARD_SWITCH: 'personalActivitiesInsightSwitch',
  PERSONAL_INSIGHTS_DASHBOARD_SWITCH: 'personalInsightDashboardSwitch',
  ORG_PAYMENT_REDIRECT_FROM_BILLING_DASHBOARD: 'orgPaymentRedirectFromBillingDashboard',
  ORG_PAYMENT_REDIRECT_FROM_SECURITY_DASHBOARD: 'orgPaymentRedirectFromSecurityDashboard',
  ORG_PAYMENT_REDIRECT_FROM_INSIGHTS_DASHBOARD: 'orgPaymentRedirectFromInsightsDashboard',
  ADD_ORGANIZATION_MEMBER_MODAL_OPEN: 'addOrganizationMemberModalOpen',
  ANNUAL_PROFESSIONAL_UPGRADE_WITH_SAVE_OF: 'annualProfessionalUpgradeWithSaveOf',
  ANNUAL_PROFESSIONAL_UPGRADE: 'annualProfessionalUpgrade',
  ORGANIZATION_PLAN_LEARN_MORE: 'organization_plan_learn_more',
  GOOGLE_DRIVE_ACCOUNT_CHANGE: 'googleDriveAccountChange',
  GO_TO_DOCUMENT_LIST: 'goToDocumentList',
  CONNECT_GOOGLE_DRIVE: 'connectToGoogleDrive',
  INFORM_OPEN_DOCUMENT_THUMBS_UP: 'informOpenDocumentThumbsUp',
  INFORM_OPEN_DOCUMENT_THUMBS_DOWN: 'informOpenDocumentThumbsDown',
  INFORM_OPEN_DOCUMENT_CONFIRM: 'informOpenDocumentConfirm',
  LUMIN_NEW_DESIGN_SURVEY_THUMBS_UP: 'luminNewDesignSurveyThumbsUp',
  LUMIN_NEW_DESIGN_SURVEY_THUMBS_DOWN: 'luminNewDesignSurveyThumbsDown',
  LUMIN_NEW_DESIGN_CONFIRM: 'luminNewDesignConfirm',
  LUMIN_NEW_AUTO_SYNC_CONFIRM: 'luminNewAutoSyncConfirm',
  INSTALL_PWA_CTA_NOT_WINDOWS: 'installPwaCtaNotWindows',
  SIGN_IN_GOOGLE: 'signInGoogle',
  SIGN_IN_DROPBOX: 'signInDropbox',
  SIGN_IN_SUBMIT: 'signInSubmit',
  SIGN_UP_GOOGLE: 'signUpGoogle',
  SIGN_UP_DROPBOX: 'signUpDropbox',
  SIGN_UP_SUBMIT: 'signUpSubmit',
  SIGNATURE_TOOL: 'signatureToolIcon',
  RUBBER_STAMP: 'rubberStamp',
  SIGNATURE_TOOL_START_FREE_TRIAL: 'signatureToolStartFreeTrialLink',
  SIGNATURE_TOOL_START_UPGRADE: 'signatureToolStartUpgradeLink',
  PERIOD_SWITCH_TO_MONTHLY: 'periodSwitchToMonthly',
  PERIOD_SWITCH_TO_YEARLY: 'periodSwitchToYearly',
  GO_TO_TRIAL_PAGE: 'goToTrialPage',
  ENABLE_OFFLINE: 'enableOfflineSupport',
  ENABLE_OFFLINE_ITEM: 'enableOfflineSupportItem',
  DISABLE_OFFLINE: 'disableOfflineSupport',
  UPDATE_OFFLINE_SOURCE: 'updateOfflineSupportSettings',
  UPDATE_OFFLINE_SOURCE_IN_NAV: 'updateOfflineSupportNav',
  MAKE_OFFLINE_FILE_IN_VIEWER: 'makeOfflineAvailableViewer',
  MAKE_OFFLINE_FILE_UNAVAILABLE_IN_VIEWER: 'makeOfflineUnavailableViewer',
  MAKE_OFFLINE_FILE_IN_DOCLIST: 'makeOfflineAvailableDocList',
  MAKE_OFFLINE_FILE_UNAVAILABLE_IN_DOCLIST: 'makeOfflineUnavailableDocList',
  MAKE_OFFLINE_AVAILABLE_TOAST: 'makeOfflineAvailableToast',
  BOARDING_CREATE_NEW_CIRCLE: 'onboardingCreateNewCircle',
  ON_BOARDING_JOIN_AN_ORGANIZATION_INSTEAD: 'onboardingJoinACircleInstead',
  ON_BOARDING_ORGANIZATION_CONNECT_GOOGLE_ACCOUNT: 'onboardingOrganizationConnectGoogleAccount',
  ON_BOARDING_ORGANIZATION_CONNECT_DONT_GOOGLE_ACCOUNT: 'onboardingOrganizationDontConnectGoogle',
  ON_BOARDING_ORGANIZATION_BROWSE_DOCUMENTS: 'onboardingOrganizationBrowseDocuments',
  ON_BOARDING_ORGANIZATION_UPLOAD_DOCUMENTS: 'onboardingOrganizationUploadDocument',
  ON_BOARDING_SKIP_INVITE_ORGANIZATION_MEMBERS: 'onboardingSkipInviteOrganizationMembers',
  TURN_ON_AUTO_SYNC: 'turnOnAutoSync',
  TURN_OFF_AUTO_SYNC: 'turnOffAutoSync',
  FORM_BUILDER_TEXT_FIELD: 'formBuilderTextField',
  FORM_BUILDER_CHECKBOX: 'formBuilderSelectCheckbox',
  FORM_BUILDER_RADIO_BUTTON: 'formBuilderSelectRadioButton',
  FORM_BUILDER_SIGNATURE_FIELD: 'formBuilderSelectSignatureField',
  FORM_BUILDER_DISCARD_CHANGES: 'formBuilderDiscardChanges',
  FORM_BUILDER_CANCEL_DISCARD_CHANGES: 'formBuilderCancelDiscardChanges',
  TEMPLATE_UPLOAD_DRIVE: 'templateUploadDrive',
  TEMPLATE_UPLOAD_DROPBOX: 'templateUploadDropbox',
  TEMPLATE_UPLOAD_DEVICE: 'templateUploadDevice',
  TEMPLATE_CREATE_DOCLIST: 'templateCreateDocList',
  USE_TEMPLATE: 'templateUse',
  EDIT_TEMPLATE: 'templateEditInfo',
  ONBOARDING_CREATE_NEW_CIRCLE_CONNECT_GOOGLE_ACCOUNT: 'onboardingCreateNewCircleConnectGoogleAccount',
  ONBOARDING_CIRCLE_PURPOSE: 'onboardingCirclePurpose',
  SEND_AND_SIGN: 'sendAndSign',
  NEXT_TO_ADD_DUE_DATE: 'nextToAddDueDate',
  REDACTION: 'redaction',
  APPLY_REDACTION: 'applyRedaction',
  DELETE_REDACTION: 'deleteRedaction',
  CHANGE_COLOUR_REDACTION: 'changeColourRedaction',
  EDIT_PDF: 'editPDF',
  DELETE_TEXTBLOCK: 'deleteTextblock',
  DELETE_PDF_IMAGE: 'deletePdfImage',
  START_EDIT_PDF_TEXT: 'startEditPdfText',
  REDACTION_BY_TEXT: 'redactionByText',
  HIDE_BANANASIGN: 'hideSignAndSend',
  DISCARD_CHANGES_EDIT_PDF: 'discardChangesEditPdf',
  ADD_DOMAIN: 'addDomain',
  VISIBILITY_INVITE_ONLY: 'visibilityInviteOnly',
  VISIBILITY_AUTO_APPROVE: 'visibilityAutoApprove',
  VISIBILITY_REQUEST_ACCESS: 'visibilityRequestAccess',
  CLICK_DOC_STACK_ON_DOC_LIST: 'clickDocStackOnDocList',
  START_TRIAL_ON_DOC_STACK_DOC_LIST: 'startTrialOnDocStackDocList',
  GO_PREMIUM_ON_DOC_STACK_DOC_LIST: 'goPremiumOnDocStackDocList',
  START_TRIAL_ON_PROFILE_POP_OVER: 'startTrialOnProfilePopOver',
  GO_PREMIUM_ON_PROFILE_POP_OVER: 'goPremiumOnProfilePopOver',
  START_TRIAL_ON_BILLING_SETTINGS: 'startTrialOnBillingSettings',
  GO_PREMIUM_ON_BILLING_SETTINGS: 'goPremiumOnBillingSettings',
  START_TRIAL_ON_DASHBOARD_BILLING: 'startTrialOnDashboardBilling',
  GO_PREMIUM_ON_DASHBOARD_BILLLING: 'goPremiumOnDashboardBilling',
  CHECK_OUT_LUMINS_FACEBOOK: 'checkOutLuminsFacebook',
  CHECK_OUT_LUMINS_INSTAGRAM: 'checkOutLuminsInstagram',
  CHECK_OUT_LUMINS_TIKTOK: 'checkOutLuminsTiktok',
  CHECK_OUT_LUMINS_LINKEDIN: 'checkOutLuminsLinkedIn',
  BUY_PRO_ON_WHATS_NEW_MODAL: 'buyProOnWhatsNewModal',
  FREE_BUY_PRO_WHATS_NEW_MODAL: 'buyProOnWhatsNewModal',
  LEARN_ABOUT_PRO_PLAN: 'learnAboutProPlan',
  LEARN_PRO_PLAN: 'learnAboutProPlan',
  BUY_BUSINESS_ON_WHATS_NEW_MODAL: 'buyBusinessOnWhatsNewModal',
  LEARN_ABOUT_BUSINESS_PLAN: 'learnAboutBusinessPlan',
  ORGANIZATION_CREATED: 'organizationCreated',
  NOTIFICATION_WIDGET: 'notificationWidget',
  INTEGRATE_WITH_BANANASIGN: 'integrateWithBananasign',
  VIEW_ORIGINAL_VERSION: 'viewOriginalVersion',
  RESTORE_ORIGINAL_VERSION: 'restoreOriginalVersion',
  ADD_PARAGRAPH: 'addParagraph',
  COPY_LINK: 'copyLink',
  REMOVE_AUTO_COMPLETE_ENTRY: 'removeAutoCompleteEntry',
  REMOVE_MULTIPLE_AUTO_COMPLETE_ENTRIES: 'removeMultipleAutoCompleteEntries',
  PERFORM_OCR: 'performOCR',
  SAVE_ON_COMPUTER: 'saveOnComputer',
  SAVE_TO_DRIVE: 'saveToDrive',
  SAVE_AS_DOCX: 'saveAsDocx',
  SAVE_AS_PDF: 'saveAsPDF',
  SAVE_AS_XLSX: 'saveAsXlsx',
  SAVE_AS_PPTX: 'saveAsPptx',
  SAVE_AS_JPG: 'saveAsJpg',
  SAVE_AS_PNG: 'saveAsPng',
  CONFIRM_SAVE_TO_DRIVE: 'confirmSaveToDrive',
  CANCEL_SAVE_TO_DRIVE: 'cancelSaveToDrive',
  LUMIN_HOME_PAGE: 'luminHomePage',
  GIVE_FEEDBACK: 'giveFeedback',
  NOTIFICATION: 'notification',
  INVITE_MEMBER_MODAL_MAKE_MEMBER: 'inviteMemberModalMakeMember',
  INVITE_MEMBER_MODAL_MAKE_BILLING_MODERATOR: 'inviteMemberModalMakeModerator',
  INVITE_MEMBER_MODAL_REMOVE: 'inviteMemberModalRemove',
  NOTIFICATION_CENTER_GENERAL: 'notificationCenterGeneral',
  NOTIFICATION_CENTER_INVITES: 'notificationCenterInvites',
  NOTIFICATION_CENTER_REQUESTS: 'notificationCenterRequests',
  INVITE_CIRCLE_MEMBER: 'inviteCircleMember',
  REDIRECT_TO_PRO_MONTHLY_PLAN_LUMIN_SIGN: 'redirectToProMonthlyPlanLuminSign',
  REDIRECT_TO_PRO_ANNUAL_PLAN_LUMIN_SIGN: 'redirectToProAnnualPlanLuminSign',
  REDIRECT_TO_FREE_PLAN_LUMIN_SIGN: 'redirectToFreePlanLuminSign',
  INVITE_MEMBER_TO_EXTEND_FREE_TRIAL: 'inviteMemberToExtendFreeTrial',
  SECURITY_CIRCLE_ADMIN_CAN_INVITE: 'securityCircleAdminCanInvite',
  SECURITY_CIRCLE_MEMBERS_CAN_INVITE: 'securityCircleMembersCanInvite',
  OUTLINE_MENU: 'outlineMenu',
  ADD_OUTLINE: 'addOutline',
  ADD_SUB_OUTLINE: 'addSubOutline',
  EDIT_OUTLINE: 'editOutline',
  DELETE_OUTLINE: 'deleteOutline',
  CONNECT_GOOGLE_ACCOUNT: 'connectGoogleAccount',
  SECURITY_GOOGLE_SIGN_IN: 'securityGoogleSignIn',
  SECURITY_VISIBILITY_INVITE_ONLY: 'securityVisibilityInviteOnly',
  SECURITY_VISIBILITY_REQUEST_ACCESS: 'securityVisibilityRequestAccess',
  SECURITY_VISIBILITY_ANYONE_CAN_JOIN: 'securityVisibilityAnyoneCanJoin',
  SECURITY_ASSOCIATED_DOMAIN_ADD: 'securityAssociatedDomainAdd',
  SECURITY_INVITE_PERMISSION_ADMIN: 'securityInvitePermissionAdmin',
  MICROSOFT_ACCOUNT_CHANGE: 'microsoftAccountChange',
  ...DocumentSummarizationEventName,
  WORKSPACE_SWITCHER_CREATE_WORKSPACE: 'createWorkspace',
  WORKSPACE_SWITCHER_INVITE_CIRCLE_MEMBER: 'inviteCircleMember',
  WORKSPACE_SWITCHER_SETTINGS: 'settings',
  WORKSPACE_SWITCHER_JOIN_WORKSPACE: 'joinWorkspace',
  WORKSPACE_SWITCHER_REQUEST_ACCESS_WORKSPACE: 'requestAccessWorkspace',
  WORKSPACE_SWITCHER_CLOSE_SUGGESTED_WORKSPACE: 'closeSuggestedWorkspace',
  EDIT_IN_LUMIN_MOBILE_APP: 'editInLuminMobileApp',
  FORM_BUILDER: 'FormBuilder',
  FORM_BUILDER_OPEN: 'formBuilderOpen',
  FORM_FIELD_DETECTION: 'formFieldDetection',
  READ_ALOUD_PDF: 'readAloudPDF',
  UPLOAD_FROM_ONE_DRIVE: 'uploadFromOneDrive',
  SWITCH_TO_CLASSIC_LAYOUT_IN_APP: 'switchToClassicLayoutInApp',
  SWITCH_TO_NEW_LAYOUT_IN_APP: 'switchToNewLayoutInApp',
  MERGE: 'merge',
  HOME_EDIT_A_PDF: 'homeEditAPdf',
  HOME_UPLOAD_A_PDF: 'homeUploadAPdf',
  HOME_GET_SIGNATURES: 'homeGetSignatures',
  HOME_USE_A_TEMPLATE: 'homeUseATemplate',
  HOME_MAKE_A_SPACE: 'homeMakeASpace',
  UPLOAD_DOC: 'uploadDoc',
  CREATE_FOLDER: 'createFolder',
  HOME_WRITE_MY_AGREEMENT: 'homeWriteMyAgreement',
  EDIT_IN_AGREEMENT_GEN: 'editInAgreementGen',
  FORM_FIELD_DETECTION_IN_AI_TAB: 'formFieldDetectionInAITab',
  PLAN_SWITCH_TO_ORG_STARTER: 'planSwitchToOrgStarter',
  PLAN_SWITCH_TO_ORG_PRO: 'planSwitchToOrgPro',
  PLAN_SWITCH_TO_ORG_BUSINESS: 'planSwitchToOrgBusiness',
  SHARE_IN_SLACK: 'shareInSlack',
  SHARE_IN_SLACK_AUTHORIZE: 'shareInSlackAuthorize',
  UPLOAD_FILE_ON_CHOOSE_A_FILE_TO_EDIT: 'uploadFileOnChooseAFileToEdit',
  ONBOARDING_ORGANIZATION_GET_STARTED: 'onboardingOrganizationGetStarted',
  ONBOARDING_CREATE_NEW_CIRCLE_CONTINUE: 'onboardingCreateNewCircleContinue',
  ENABLE_INVITE_LINK: 'enableInviteLink',
  DISABLE_INVITE_LINK: 'disableInviteLink',
  CHANGE_ROLE_INVITE_LINK: 'changeRoleInviteLink',
  REGENERATE_INVITE_LINK: 'regenerateInviteLink',
  INVITE_MEMBERS_TOP_RIGHT: 'inviteMembersTopRight',
  DOWNLOAD_DOCUMENT: 'Download',
  HELP: 'HelpButton',
  ZOOM_OUT: 'zoomOut',
  CHANGE_ZOOM_NUMBER: 'changeZoomNumber',
  ZOOM_IN: 'zoomIn',
  PREVIOUS_PAGE: 'PreviousPage',
  NEXT_PAGE: 'NextPage',
  GO_TO_FIRST_PAGE: 'GoToFirstPage',
  GO_TO_LAST_PAGE: 'GoToLastPage',
  CHANGE_PAGE_NUMBER: 'ChangePageNumber',
  EDITOR_CHATBOT_CLEAR_HISTORY: 'clearChatbotHistory',
  BACK: 'Back',
  ADD_PAYMENT_METHOD: 'addPaymentMethod',
  CONTACT_US: 'contactUs',
  CONTINUE: 'Continue',
  CREATE_CERTIFIED_VERSION: 'createCertifiedVersion',
  SAVE_AS_TEMPLATE: 'saveAsTemplate',
};

const GO_PREMIUM_PURPOSE = 'Users want to go premium';
const START_TRIAL_PURPOSE = 'Users want to start trial';

export const ButtonPurpose = {
  [ButtonName.ORG_PLAN_UPGRADE]: 'Upgrade organization plan',
  [ButtonName.PLAN_PAGE_REDIRECT]: 'Redirect to plan page',
  [ButtonName.LUMIN_DOWNLOAD]: 'Download Lumin PWA',
  [ButtonName.PROMOTION_FREE_TRIAL_SKIP]: 'Skip promotion free trial modal',
  [ButtonName.PROMOTION_FREE_TRIAL_SUBMIT]: 'Submit Free trial in promotion modal',
  [ButtonName.TEACHER_PURPOSE_SELECT]: 'Select teacher purpose',
  [ButtonName.STUDENT_PURPOSE_SELECT]: 'Select student purpose',
  [ButtonName.PERSONAL_PURPOSE_SELECT]: 'Select personal purpose',
  [ButtonName.SMALL_BUSINESS_PURPOSE_SELECT]: 'Select small business purpose',
  [ButtonName.LARGE_COMPANY_PURPOSE_SELECT]: 'Select large company purpose',
  [ButtonName.NON_PROFIT_PURPOSE_SELECT]: 'Select non-profit purpose',
  [ButtonName.PURPOSE_SKIP]: 'Skip select purpose',
  [ButtonName.INDIVIDUAL_PLAN_SWITCH]: 'Switch to individual plan section',
  [ButtonName.ORGANIZATION_PLAN_SWITCH]: 'Switch to organization plan section',
  [ButtonName.PROFESSIONAL_PLAN_UPGRADE]: 'Upgrade to professional plan',
  [ButtonName.MODAL_SHARE_DOCUMENT_OPEN]: 'Open share document modal',
  [ButtonName.SALE_EDUCATION_AND_NON_PROFIT_CONTACT]: 'Contact sale team about education or not-profit plan',
  [ButtonName.ORGANIZATION_CREATION_PAGE_REDIRECT]: 'Redirect to organization creation page',
  [ButtonName.BUSINESS_PLAN_UPGRADE]: 'Upgrade organization to larger size',
  [ButtonName.ENTERPRISE_FREE_QUOTE]: 'Get a free quote with enterprise plan',
  [ButtonName.ORGANIZATION_SET_UP]: 'Set up an organization',
  [ButtonName.ALL_FAQ_OPEN]: 'Open all FAQs',
  [ButtonName.ALL_FAQ_HIDE]: 'Hide all FAQs',
  [ButtonName.ORGANIZATION_CREATE]: 'Create organization',
  [ButtonName.ORGANIZATION_PAYMENT_PAGE_REDIRECT]: 'Redirect to organization payment page',
  [ButtonName.ORGANIZATION_CREATION_REDIRECT_FROM_ORG_LIST]:
    'Redirect from organization list to organization creation page',
  [ButtonName.INVITE_ORG_MEMBER_MODAL_OPEN_IN_ORG_LIST]:
    'Open modal to invite organization member in organization list',
  [ButtonName.ORG_DASHBOARD_REDIRECT_FROM_ORG_LIST]: 'Redirect from organization list to organization dashboard',
  [ButtonName.FREE_TRIAL_PAGE_REDIRECT]: 'Redirect to free trial page from personal insight',
  [ButtonName.PERSONAL_ACTIVITIES_DASHBOARD_SWITCH]: 'Switch to activities dashboard section',
  [ButtonName.PERSONAL_INSIGHTS_DASHBOARD_SWITCH]: 'Switch to insights dashboard section',
  [ButtonName.ORG_PAYMENT_REDIRECT_FROM_BILLING_DASHBOARD]:
    'Redirect from billing dashboard to organization payment page',
  [ButtonName.ORG_PAYMENT_REDIRECT_FROM_SECURITY_DASHBOARD]:
    'Redirect from security dashboard to organization payment page',
  [ButtonName.ORG_PAYMENT_REDIRECT_FROM_INSIGHTS_DASHBOARD]:
    'Redirect from insights dashboard to organization payment page',
  [ButtonName.ADD_ORGANIZATION_MEMBER_MODAL_OPEN]: 'Open modal to invite organization member',
  [ButtonName.ANNUAL_PROFESSIONAL_UPGRADE_WITH_SAVE_OF]:
    'Redirect from header button to annual professional payment page with save of 34% ',
  [ButtonName.ANNUAL_PROFESSIONAL_UPGRADE]: 'Redirect from header button to annual professional page',
  [ButtonName.ORGANIZATION_PLAN_LEARN_MORE]: 'Learn more organization plans',
  [ButtonName.GOOGLE_DRIVE_ACCOUNT_CHANGE]: 'Change google drive account to open document',
  [ButtonName.GO_TO_DOCUMENT_LIST]: 'Go to document list',
  [ButtonName.CONNECT_GOOGLE_DRIVE]: 'Prompt the user to connect Lumin to Google Drive',
  [ButtonName.INFORM_OPEN_DOCUMENT_THUMBS_UP]: 'Selected thumbs up on working with documents modal',
  [ButtonName.INFORM_OPEN_DOCUMENT_THUMBS_DOWN]: 'Selected thumbs down on working with documents modal',
  [ButtonName.INFORM_OPEN_DOCUMENT_CONFIRM]: 'Clicked to confirm document experience',
  [ButtonName.LUMIN_NEW_DESIGN_SURVEY_THUMBS_UP]: 'Thumbs up on Lumin new design survey',
  [ButtonName.LUMIN_NEW_DESIGN_SURVEY_THUMBS_DOWN]: 'Thumbs down on Lumin new design survey',
  [ButtonName.LUMIN_NEW_DESIGN_CONFIRM]: 'Clicked to confirm New UI experience',
  [ButtonName.LUMIN_NEW_AUTO_SYNC_CONFIRM]: 'Clicked to confirm New Auto Sync modal',
  [ButtonName.INSTALL_PWA_CTA_NOT_WINDOWS]: 'Clicked on install call to action button for users who OS is not windows',
  [ButtonName.SIGN_IN_GOOGLE]: 'Sign in with google',
  [ButtonName.SIGN_IN_DROPBOX]: 'Sign in with dropbox',
  [ButtonName.SIGN_IN_SUBMIT]: 'Clicked sign in with email form',
  [ButtonName.SIGN_UP_GOOGLE]: 'Sign up with google',
  [ButtonName.SIGN_UP_DROPBOX]: 'Sign up with dropbox',
  [ButtonName.SIGN_UP_SUBMIT]: 'Clicked sign up with email form',
  [ButtonName.SIGNATURE_TOOL]: 'Open the signature tool in the viewer',
  [ButtonName.SIGNATURE_TOOL_START_FREE_TRIAL]: 'Prompt user to start free trial to add more signatures',
  [ButtonName.SIGNATURE_TOOL_START_UPGRADE]: 'Prompt user to upgrade professional to add more signatures',
  [ButtonName.PERIOD_SWITCH_TO_MONTHLY]: 'Switch to a monthly billing period',
  [ButtonName.PERIOD_SWITCH_TO_YEARLY]: 'Switch to a yearly billing period',
  [ButtonName.GO_TO_TRIAL_PAGE]: 'Clicked Start Free trial button on header',
  [ButtonName.ENABLE_OFFLINE]: 'Enable Offline Support',
  [ButtonName.ENABLE_OFFLINE_ITEM]: 'Enable Offline Support on Doc item',
  [ButtonName.DISABLE_OFFLINE]: 'Disable Offline Support',
  [ButtonName.UPDATE_OFFLINE_SOURCE]: 'To know if user updates Offline Support after enabling it',
  [ButtonName.UPDATE_OFFLINE_SOURCE_IN_NAV]: 'To know if user updates Offline Support after enabling it',
  [ButtonName.MAKE_OFFLINE_FILE_IN_VIEWER]: 'Make a file Offline Available in Doc Viewer',
  [ButtonName.MAKE_OFFLINE_FILE_UNAVAILABLE_IN_VIEWER]: 'Make a file Offline Unavailable in Doc Viewer',
  [ButtonName.MAKE_OFFLINE_FILE_IN_DOCLIST]: 'Make a file Offline Available in Doc list',
  [ButtonName.MAKE_OFFLINE_FILE_UNAVAILABLE_IN_DOCLIST]: 'Make a file Offline Unavailable in Doc list',
  [ButtonName.MAKE_OFFLINE_AVAILABLE_TOAST]: 'Make a file Offline Available',
  [ButtonName.BOARDING_CREATE_NEW_CIRCLE]: 'Create a new circle during onboarding',
  [ButtonName.ON_BOARDING_JOIN_AN_ORGANIZATION_INSTEAD]:
    'User selected to join an organization instead of creating one',
  [ButtonName.ON_BOARDING_ORGANIZATION_CONNECT_GOOGLE_ACCOUNT]:
    'Connect Google account during organizations onboarding',
  [ButtonName.ON_BOARDING_ORGANIZATION_CONNECT_DONT_GOOGLE_ACCOUNT]:
    'Dont connect Google during organization onboarding',
  [ButtonName.ON_BOARDING_ORGANIZATION_BROWSE_DOCUMENTS]:
    'Take user from organization onboarding process to browser their documents',
  [ButtonName.ON_BOARDING_ORGANIZATION_UPLOAD_DOCUMENTS]:
    'Take user from organziation onboarding to uploading a document',
  [ButtonName.ON_BOARDING_SKIP_INVITE_ORGANIZATION_MEMBERS]:
    'Skip adding organization members during onboarding process',
  [ButtonName.TURN_ON_AUTO_SYNC]: 'Turn on Auto-sync toggle',
  [ButtonName.TURN_OFF_AUTO_SYNC]: 'Turn off Auto-sync toggle',
  [ButtonName.FORM_BUILDER_OPEN]: 'Open the form builder',
  [ButtonName.FORM_BUILDER_TEXT_FIELD]: 'Select the form builder text field',
  [ButtonName.FORM_BUILDER_CHECKBOX]: 'Select the form builder checkbox tool',
  [ButtonName.FORM_BUILDER_RADIO_BUTTON]: 'Select the radio button in the form builder',
  [ButtonName.FORM_BUILDER_SIGNATURE_FIELD]: 'Select the form builder signature field',
  [ButtonName.FORM_BUILDER_DISCARD_CHANGES]: 'Discard changes made with the form builder',
  [ButtonName.FORM_BUILDER_CANCEL_DISCARD_CHANGES]: 'User decides not to discard their changes in form builder',
  [ButtonName.TEMPLATE_UPLOAD_DRIVE]: 'Clicked on Upload Template from Drive',
  [ButtonName.TEMPLATE_UPLOAD_DROPBOX]: 'Clicked on Upload Template from Dropbox',
  [ButtonName.TEMPLATE_UPLOAD_DEVICE]: 'Clicked on Upload Template from Device',
  [ButtonName.TEMPLATE_CREATE_DOCLIST]: 'Users want to create a file as Template from Doc List',
  [ButtonName.USE_TEMPLATE]: 'Clicked on Use Template CTA on Preview template modal',
  [ButtonName.EDIT_TEMPLATE]: "Users want to edit Template's Info",
  [ButtonName.ONBOARDING_CREATE_NEW_CIRCLE_CONNECT_GOOGLE_ACCOUNT]:
    'User selected to connect Google Account to add collaborators to their circle',
  [ButtonName.ONBOARDING_CIRCLE_PURPOSE]: 'User selected what they use Lumin for',
  [ButtonName.SEND_AND_SIGN]: 'Open document with Lumin Sign',
  [ButtonName.NEXT_TO_ADD_DUE_DATE]: 'Next to add due date step of Bananasign',
  [ButtonName.REDACTION]: 'Redaction tool',
  [ButtonName.APPLY_REDACTION]: 'Apply redaction annotation',
  [ButtonName.DELETE_REDACTION]: 'Delete redaction annotation',
  [ButtonName.CHANGE_COLOUR_REDACTION]: 'Change redaction annotation colour',
  [ButtonName.EDIT_PDF]: 'Edit PDF content',
  [ButtonName.DELETE_TEXTBLOCK]: 'Delete text',
  [ButtonName.DELETE_PDF_IMAGE]: 'Delete Pdf image',
  [ButtonName.START_EDIT_PDF_TEXT]: 'Start edit PDF text',
  [ButtonName.REDACTION_BY_TEXT]: 'Redaction tool by text',
  [ButtonName.HIDE_BANANASIGN]: 'Hide Sign and Send button',
  [ButtonName.DISCARD_CHANGES_EDIT_PDF]: 'Discard edit pdf changes',
  [ButtonName.ADD_DOMAIN]: 'Circle wants to add domain that make circle visible to Lumin users with the same domain',
  [ButtonName.VISIBILITY_INVITE_ONLY]: "Change circle's visibility to invite only",
  [ButtonName.VISIBILITY_AUTO_APPROVE]: "Change circle's visibility to auto approve",
  [ButtonName.VISIBILITY_REQUEST_ACCESS]: "Change circle's visibility to request access",
  [ButtonName.CLICK_DOC_STACK_ON_DOC_LIST]: 'How engaged users are on the doc stack',
  [ButtonName.START_TRIAL_ON_DOC_STACK_DOC_LIST]: 'How engaged users are on the doc stack',
  [ButtonName.GO_PREMIUM_ON_DOC_STACK_DOC_LIST]: GO_PREMIUM_PURPOSE,
  [ButtonName.START_TRIAL_ON_PROFILE_POP_OVER]: START_TRIAL_PURPOSE,
  [ButtonName.GO_PREMIUM_ON_PROFILE_POP_OVER]: GO_PREMIUM_PURPOSE,
  [ButtonName.START_TRIAL_ON_BILLING_SETTINGS]: START_TRIAL_PURPOSE,
  [ButtonName.GO_PREMIUM_ON_BILLING_SETTINGS]: GO_PREMIUM_PURPOSE,
  [ButtonName.START_TRIAL_ON_DASHBOARD_BILLING]: START_TRIAL_PURPOSE,
  [ButtonName.GO_PREMIUM_ON_DASHBOARD_BILLLING]: GO_PREMIUM_PURPOSE,
  [ButtonName.CHECK_OUT_LUMINS_FACEBOOK]: "Users want to check out Lumin's Facebook",
  [ButtonName.CHECK_OUT_LUMINS_INSTAGRAM]: "Users want to check out Lumin's Instagram",
  [ButtonName.CHECK_OUT_LUMINS_TIKTOK]: "Users want to check out Lumin's Tiktok",
  [ButtonName.CHECK_OUT_LUMINS_LINKEDIN]: "Users want to check out Lumin's LinkedIn",
  [ButtonName.LEARN_PRO_PLAN]: 'Professional users want to learn more about Pro plan.',
  [ButtonName.BUY_BUSINESS_ON_WHATS_NEW_MODAL]:
    "Old Business users wants to upgrade to Business plan on the What's new modal.",
  [ButtonName.LEARN_ABOUT_BUSINESS_PLAN]: 'Business users want to learn more about Business plan',
  [ButtonName.BUY_PRO_ON_WHATS_NEW_MODAL]: "Professional users wants to upgrade to Pro plan on the What's new modal.",
  [ButtonName.ORGANIZATION_CREATED]: 'Create an organizationCreated event with the appropriate parameters',
  [ButtonName.NOTIFICATION_WIDGET]: 'Open notification widget',
  [ButtonName.INTEGRATE_WITH_BANANASIGN]: 'Open document with BananaSign',
  [ButtonName.VIEW_ORIGINAL_VERSION]: 'View original version of the document',
  [ButtonName.RESTORE_ORIGINAL_VERSION]: 'Restore the original version of the document',
  [ButtonName.ADD_PARAGRAPH]: 'add a text box to input paragraph in Edit mode',
  [ButtonName.PERFORM_OCR]: 'Perform OCR',
  COPY_LINK_ON_DOCUMENT_LIST: 'Copy document link from document list',
  COPY_LINK_ON_DOCUMENT_LIST_DROPDOWN:
    'Copy document link from Share link modal on document list (the share button on the document dropdown)',
  COPY_LINK_ON_HEADER: 'Copy document link from document viewer (button share on the header)',
  COPY_LINK_FROM_SHARE_LINK_ON_HEADER:
    'Copy document link from Share link modal in doc viewer (the share button on the header)',
  COPY_LINK_ON_SIDEBAR: 'Copy document link from document viewer sidebar (button share on the sidebar)',
  COPY_LINK_FROM_SHARE_LINK_ON_SIDEBAR:
    'Copy document link from Share link modal in doc viewer (the share button on the sidebar)',
  COPY_LINK_FROM_COPY_LINK_ON_SIDEBAR:
    'Copy document link from Share link modal in doc viewer (the copy link button on the sidebar)',
  [ButtonName.REMOVE_AUTO_COMPLETE_ENTRY]: 'Remove a single entry of the auto-complete feature',
  [ButtonName.REMOVE_MULTIPLE_AUTO_COMPLETE_ENTRIES]: 'Remove multiple entries of the auto-complete feature',
  [ButtonName.COPY_LINK]: 'Copy document link from the document dropdown on the document list',
  [ButtonName.SAVE_ON_COMPUTER]: 'Save file to computer',
  [ButtonName.SAVE_TO_DRIVE]: 'Change save location to Google Drive',
  [ButtonName.SAVE_AS_DOCX]: 'Save file as .docx',
  [ButtonName.SAVE_AS_PDF]: 'Save file as .pdf',
  [ButtonName.CONFIRM_SAVE_TO_DRIVE]: 'Confirm to save file to Google Drive at the desired folder',
  [ButtonName.CANCEL_SAVE_TO_DRIVE]: 'Cancel saving file to Google Drive and go back to the first modal',
  [ButtonName.COPY_LINK]: 'Copy document link from the document dropdown on the document list',
  [ButtonName.LUMIN_HOME_PAGE]: 'Back to previous document list',
  [ButtonName.GIVE_FEEDBACK]: 'Prompt users to give Lumin feedback',
  [ButtonName.NOTIFICATION]: 'Notification center on the header',
  [ButtonName.INVITE_MEMBER_MODAL_MAKE_MEMBER]: `On the Invite member modal, make the invited 'member'`,
  [ButtonName.INVITE_MEMBER_MODAL_MAKE_BILLING_MODERATOR]: `On the Invite member modal, make the invited 'Billing Moderator'`,
  [ButtonName.INVITE_MEMBER_MODAL_REMOVE]: 'On the Invite member modal, remove the invited',
  [ButtonName.NOTIFICATION_CENTER_GENERAL]: 'Users engage in the notification center, General tab',
  [ButtonName.NOTIFICATION_CENTER_INVITES]: 'Users engage in the notification center, Invites tab',
  [ButtonName.NOTIFICATION_CENTER_REQUESTS]: 'Users engage in the notification center, Requests tab',
  [ButtonName.INVITE_CIRCLE_MEMBER]: 'Invite members to Circle',
  [ButtonName.REDIRECT_TO_PRO_MONTHLY_PLAN_LUMIN_SIGN]: 'Redirect to Lumin Sign Pro Monthly Plan',
  [ButtonName.REDIRECT_TO_PRO_ANNUAL_PLAN_LUMIN_SIGN]: 'Redirect to Lumin Sign Pro Annual Plan',
  [ButtonName.REDIRECT_TO_FREE_PLAN_LUMIN_SIGN]: 'Redirect to Lumin Sign Free Plan',
  [ButtonName.INVITE_MEMBER_TO_EXTEND_FREE_TRIAL]: 'Invite member to extend free trial',
  [ButtonName.SECURITY_CIRCLE_ADMIN_CAN_INVITE]: 'enable the Circle Administrators to invite collaborators',
  [ButtonName.SECURITY_CIRCLE_MEMBERS_CAN_INVITE]: 'enable anyone in the Circle to invite collaborators',
  ADD_OUTLINE_FROM_BOTTOM_BUTTON: 'Add outline from button icon',
  [ButtonName.CONNECT_GOOGLE_ACCOUNT]: 'Connect with Google account to invite members',
  DOCUMENT_SUMMARIZE_RIGHT_SIDE_BAR_BUTTON: 'Summarize document in right sidebar button',
  [ButtonName.MICROSOFT_ACCOUNT_CHANGE]: 'Change microsoft account to open drive document',
  ...DocumentSummarizationEventPurpose,
  [ButtonName.EDIT_IN_LUMIN_MOBILE_APP]: 'Prompt users to continue working on documents in Lumin mobile app',
  [ButtonName.UPLOAD_FROM_ONE_DRIVE]: 'user wants to upload a OneDrive file to Lumin',
  [ButtonName.EDIT_IN_AGREEMENT_GEN]: 'Edit document in AgreementGen',
  [ButtonName.FORM_FIELD_DETECTION_IN_AI_TAB]: 'Select form field detection from Lumin AI tab',
  [ButtonName.MERGE]: 'Merge document from doc list',
  [ButtonName.EDIT_IN_AGREEMENT_GEN]: 'Edit document in AgreementGen',
  [ButtonName.FORM_FIELD_DETECTION_IN_AI_TAB]: 'Select form field detection from Lumin AI tab',
  [ButtonName.PLAN_SWITCH_TO_ORG_STARTER]: 'Switch to plan organization starter',
  [ButtonName.PLAN_SWITCH_TO_ORG_PRO]: 'Switch to plan organization pro',
  [ButtonName.PLAN_SWITCH_TO_ORG_BUSINESS]: 'Switch to plan organization business',
  [ButtonName.ONBOARDING_ORGANIZATION_GET_STARTED]: 'Take users to document list to start their work',
  [ButtonName.ONBOARDING_CREATE_NEW_CIRCLE_CONTINUE]: 'User continued after selecting purpose',
  [ButtonName.DOWNLOAD_DOCUMENT]: 'Download from viewer menu',
  [ButtonName.CHANGE_ZOOM_NUMBER]: 'Change zoom number from bottom navigation',
  [ButtonName.EDITOR_CHATBOT_CLEAR_HISTORY]: 'Clear Viewer chatbot history',
  [ButtonName.BACK]: 'Back in modal Checkout on Viewer',
  [ButtonName.ADD_PAYMENT_METHOD]: 'Add payment method in modal Checkout on Viewer',
  [ButtonName.CONTACT_US]: 'Contact us from checkout on viewer modal',
  [ButtonName.CONTINUE]: 'Continue in modal Checkout on Viewer',
  [ButtonName.CREATE_CERTIFIED_VERSION]: 'Create a certified version with digital signature',
};
