import { ModalName } from './ModalName';

const allowOrgToAddMoreDomains = `Allow circle to add more domains that make the circle visible to Lumin users with the same domain`;

const requestPurpose = 'Request to change document permission';

export const ModalPurpose = {
  [ModalName.PASSWORD_REQUIRED]: 'Enter password to open the document',
  [ModalName.ENCRYPT_WITH_PASSWORD]: 'Set password for the document',
  [ModalName.CHANGE_YOUR_PASSWORD]: 'Change password for the document',
  [ModalName.REMOVE_PASSWORD]: 'Remove password for the document',
  [ModalName.PROMOTION_PROFESSIONAL_FREE_TRIAL]: 'Prompt user to start professional free trial',
  [ModalName.PROMPT_UPGRADE_FREE_TRIAL]: 'Prompt user to start free trial in viewer and document list',
  [ModalName.NEW_VIEWER_FEATURE_GUIDE]: 'Show new feature of viewer guide',
  [ModalName.USER_PURPOSE_SELECT]: 'Select user purpose',
  [ModalName.WELCOME_ORGANIZATION_GUIDE]: 'Welcome organization guide',
  [ModalName.ADD_MEMBER_ORGANIZATION_GUIDE]: 'Add member organization guide',
  [ModalName.MANAGE_ORGANIZATION_TEAM_GUIDE]: 'Manage organization team guide',
  [ModalName.DASHBOARD_ORGANIZATION_GUIDE]: 'Done new feature organization guide',
  [ModalName.INFORM_OPEN_DOCUMENT]: "Collect user's experience with the documents feature",
  [ModalName.INFORM_NEW_DESIGN]: "Collect user's experience with the New UI",
  [ModalName.LUMIN_NEW_DESIGN_SURVEY]: 'To survey users about the new design',
  [ModalName.CONFIRM_BANANASIGN_INTEGRATION]: 'To confirm whether user want to integrate or not',
  [ModalName.ADD_SIGNER_VIEWER_TRACKING]: 'To check whether user added signer/viewer or not',
  [ModalName.APPLY_REDACTION]: 'Apply redaction',
  [ModalName.LEAVING_REDACTION_MODE]: 'Leaving redaction mode',
  [ModalName.EDIT_PDF_TEXT]: 'Edit pdf text',
  [ModalName.OPEN_EDIT_PDF_MODE]: 'Open edit pdf mode',
  [ModalName.LEAVE_EDIT_MODE_AND_SAVE_CHANGES]: 'Leave edit mode and save changes',
  [ModalName.ADD_DOMAIN]: allowOrgToAddMoreDomains,
  [ModalName.UPGRADE_TO_ENABLE_AUTO_APPROVE]: allowOrgToAddMoreDomains,
  [ModalName.REQUEST_COMMENT_PERMISSION]: requestPurpose,
  [ModalName.REQUEST_EDIT_PERMISSION]: requestPurpose,
  [ModalName.REQUEST_SHARE_PERMISSION]: requestPurpose,
  [ModalName.REQUEST_UPGRADE_HIT_LIMIT]: 'Request to upgrade plan',
  [ModalName.REQUEST_START_TRIAL_HIT_LIMIT]: 'Request to start trial',
  [ModalName.WHATS_NEW]: 'Introduce news to users.',
  [ModalName.UPGRADE_DOCUMENT_SIZE]: 'Ask user to upgrade document size to convert to Lumin storage',
  [ModalName.RESTORE_ORIGINAL_VERSION]: 'Restore the original version of the document',
  [ModalName.LEAVE_WITHOUT_SYNCING]: 'Warn user to sync to Google Drive before leaving to avoid losing changes',
  [ModalName.PROMPT_USER_TO_SYNC_CHANGES]: 'Prompt user to sync changes before leaving viewer',
  [ModalName.SYNC_PAGE_TOOLS_CHANGES]: 'Prompt user to sync changes if the file > 200MB',
  [ModalName.COMFIRM_MERGE]: 'Confirm merge documents',
  [ModalName.CONFIRM_PERFORMING_OCR]: 'Confirm start to performing OCR',
  [ModalName.OCR_UNAVAILABLE]: 'OCR unavailable because of document size too large',
  [ModalName.RUBBER_STAMP]: 'Create custom rubber stamp',
  [ModalName.INVITE_CIRCLE_MEMBER]: 'Invite members to Circle',
  [ModalName.REQUEST_UPGRADE_TO_ADD_DOMAIN]: 'request to upgrade subscription to add associated domain.',
  [ModalName.REQUEST_UPGRADE_GOOGLE_SIGN_IN]:
    'request to upgrade subscription to force members to sign in with Google.',
  [ModalName.REQUEST_UPGRADE_INVITE_PERMISSION]: 'request to upgrade subscription to customize the invite permissions.',
  [ModalName.REACTIVATE_ACCOUNT_MODAL]: 'Prompt user to reavtivate modal',
  [ModalName.ADD_OUTLINE]: 'Add an outline to outlines panel',
  [ModalName.EDIT_OUTLINE]: 'Edit outline title and destination',
  [ModalName.DELETE_OUTLINE]: 'Delete outline from the panel',
  [ModalName.REACTIVATE_LUMIN_CIRCLE_SUBSCRIPTION_MODAL]: 'Prompt user to reactivate subscription',
  [ModalName.LUMIN_SIGN_PAYWALL]: 'Prompt user to start a plan on Lumin Sign Paywall',
  [ModalName.EXTEND_FREE_TRIAL_MODAL]: 'Prompt user to invite members to extend free trial days',
  [ModalName.VERSION_HISTORY_UPGRADE]: 'Premium tool pop-over',
  [ModalName.FORM_FIELD_DETECTION_CONSENT]: 'Signature field detection user consent',
  [ModalName.ERROR_WHEN_DETECT_FORM_FIELDS]: 'Error when detecting signature fields',
  [ModalName.DOWNLOAD_DOCUMENT]: 'Open download document modal',
  [ModalName.ERROR_WHEN_DETECT_FORM_FIELDS]: 'Error when detecting signature fields',
  [ModalName.FFD_DOCUMENT_IS_UNSUPPORTED]: 'Document is unsupported to detect form fields',
  [ModalName.BULK_DOWNLOAD_ERRORS]: 'Inform the docs excluded from the bulk download',
  [ModalName.JOINED_ORGANIZATION]: 'Joined an organization modal from onboarding flow',
  [ModalName.OVERWRITE_OR_KEEP_PERMISSIONS]: 'ask if actor wants to overwrite or keep existing permissions',
  [ModalName.CHOOSE_A_FILE_TO_EDIT]: 'Choose a file to edit from Home page',
  [ModalName.CONFIRM_RESET_INVITE_LINK]: 'confirm to reset the invite link',
  [ModalName.CONFIRM_CHANGE_ROLE_INVITE_LINK]: 'confirm to change role of the invite link',
  [ModalName.CONFIRM_DEACTIVATE_INVITE_LINK]: 'confirm to deactivate the invite link',
  [ModalName.INVITE_TO_GET_FREE_DOC_STACK]: 'Prompt to invite to get free doc stack',
  [ModalName.PROMPT_TO_JOIN_TRIALING_WS]: 'Prompt to join a trialing Workspace that has just started their trial',
  [ModalName.CHECKOUT_ON_VIEWER]: 'Prompt user to start free trial from viewer',
  [ModalName.CREATE_CERTIFIED_VERSION_SUCCESS]: 'Certified version is created successfully',
  [ModalName.CREATE_CERTIFIED_VERSION_FAIL]: 'Certified version fails to be created',
  [ModalName.PREVIEW_TEMPLATE]: 'Preview general information of a template',
  [ModalName.SIGN_REQUEST_UPGRADE]: 'Request to upgrade to Lumin Sign Pro',
};
