export const NavigationNames = {
  WORKSPACE_SWITCHER: 'workspaceSwitcher',
  HOME: 'home',
  DOCS: 'documents',
  CONTRACTS: 'sign',
  TEMPLATES: 'templates',
  SETTINGS: 'settings',
  INVITE_WORKSPACE_MEMBER: 'inviteWorkspaceMember',
  MY_DOCUMENTS: 'myDocuments',
  SHARED_WITH_ME: 'sharedWithMe',
  STARRED: 'starred',
  RECENT: 'recent',
  SPACE: 'space',
  SPACES: 'spaces',
  CREATE_SPACE: 'createSpace',
  TEMPLATES_GALLERY: 'templatesGallery',
  INSIGHTS: 'insights',
  PEOPLE: 'people',
  BILLING: 'billing',
  SECURITY: 'security',
  PREFERENCE: 'preference',
  DEVELOPER_API: 'developerApi',
  WORKSPACE: 'workspace',
  MEMBERS: 'members',
  UPLOAD_DOC: 'uploadDoc',
  AGREEMENT_GEN: 'generate',
};
