export const LayoutElements = {
  DEFAULT: 'DEFAULT',
  SEARCH: 'SEARCH',
  SEARCH_OVERLAY: 'SEARCH_OVERLAY',
  NOTE_HISTORY: 'NOTE_HISTORY',
  COMMENT_PANEL: 'COMMENT_PANEL',
  SUMMARIZATION: 'SUMMARIZATION',
  CHATBOT: 'CHATBOT',
  TRANSLATOR: 'TRANSLATOR',
  INVOICE_EXTRACTOR: 'INVOICE_EXTRACTOR',
  RESUME_CHECKER: 'RESUME_CHECKER',
};
