#!/bin/bash
set -euox pipefail

NEXT_PUBLIC_ENVIRONMENT_NAME=$BITBUCKET_BRANCH

if [ $NEXT_PUBLIC_ENVIRONMENT_NAME == 'master' ]; then
  NEXT_PUBLIC_ENVIRONMENT_NAME='staging'
fi

echo export TAG="$NEXT_PUBLIC_ENVIRONMENT_NAME-$BITBUCKET_BUILD_NUMBER"

echo export NEXT_PUBLIC_ENVIRONMENT_NAME="$NEXT_PUBLIC_ENVIRONMENT_NAME"