export enum ExploredFeatureKeys {
  EDIT_PDF = 'EDIT_PDF',
  FORM_BUILDER = 'FORM_BUILDER',
  SPLIT_PDF = 'SPLIT_PDF',
  OCR = 'OCR',
  SUMMARIZATION = 'SUMMARIZATION',
  PROTECT_PDF = 'PROTECT_PDF',
  REDACT_PDF = 'REDACT_PDF',
}
