export enum LoggerReason {
  CRASH_ERROR = 'CRASH_ERROR',
  DATADOG_ADAPTOR = 'DATADOG_ADAPTOR',
  LINK_ACCOUNT = 'LINK_ACCOUNT',
  SIGN_UP_PASSWORD = 'SIGN_UP_PASSWORD',
  FAIL_TO_LOAD_GTM = 'FAIL_TO_LOAD_GTM',
  SIGN_IN_OIDC = 'SIGN_IN_OIDC',
  ENABLE_SOCIAL_SIGN_IN = 'ENABLE_SOCIAL_SIGN_IN'
}

export enum AwsPinpointReason {
  RECORD_FAILED = 'AWS_PINPOINT_RECORD_FAILED',
  SETUP_FAILED = 'AWS_PINPOINT_SETUP_FAILED'
}

export enum LOGGER_SCOPE {
  REDIS_CONNECTION = 'REDIS_CONNECTION'
}
