import { rgba } from 'polished';

import { THEME_MODE } from 'constants/lumin-common';

import { Shadows } from './Shadows';

export const Colors = {
  PRIMARY: 'var(--color-primary-90)',
  PRIMARY_10: 'var(--color-primary-10)',
  PRIMARY_20: 'var(--color-primary-20)',
  PRIMARY_30: 'var(--color-primary-30)',
  PRIMARY_40: 'var(--color-primary-40)',
  PRIMARY_50: 'var(--color-primary-50)',
  PRIMARY_60: 'var(--color-primary-60)',
  PRIMARY_70: 'var(--color-primary-70)',
  PRIMARY_80: 'var(--color-primary-80)',
  PRIMARY_90: 'var(--color-primary-90)',
  PRIMARY_110: 'var(--color-primary-110)',

  SECONDARY: '#8093a7',
  SECONDARY_10: 'var(--color-secondary-10)',
  SECONDARY_20: 'var(--color-secondary-20)',
  SECONDARY_30: 'var(--color-secondary-30)',
  SECONDARY_40: 'var(--color-secondary-40)',
  SECONDARY_50: 'var(--color-secondary-50)',
  SECONDARY_60: 'var(--color-secondary-60)',
  SECONDARY_70: 'var(--color-secondary-70)',
  SECONDARY_80: 'var(--color-secondary-80)',
  SECONDARY_90: 'var(--color-secondary-90)',

  ROMAN: 'var(--color-roman)',

  NEUTRAL_0: 'var(--color-neutral-0)',
  NEUTRAL_5: 'var(--color-neutral-5)',
  NEUTRAL_10: 'var(--color-neutral-10)',
  NEUTRAL_20: 'var(--color-neutral-20)',
  NEUTRAL_30: 'var(--color-neutral-30)',
  NEUTRAL_40: 'var(--color-neutral-40)',
  NEUTRAL_50: 'var(--color-neutral-50)',
  NEUTRAL_60: 'var(--color-neutral-60)',
  NEUTRAL_70: 'var(--color-neutral-70)',
  NEUTRAL_80: 'var(--color-neutral-80)',
  NEUTRAL_90: 'var(--color-neutral-90)',
  NEUTRAL_100: 'var(--color-neutral-100)',
  GRAY: 'var(--color-gray)',
  HOVER_GRAY: '#F4F3E4',
  PALEBLUE: '#C1D1E1',
  PALEBLUE_DARKER: '#e6eefa',
  SOLITUDE: '#e7ebf0',
  ALICEBLUE: '#f2f6fa',
  RED: '#ed3d48',
  GREEN: '#a4de53',
  YELLOW: '#ffbc41',
  SMOKE: '#ebf0f5',
  CLOUDYBLUE: '#c0d0df',
  WHITE: '#fff',
  ROYAL_BLUE_HOVER: '#1665d8',
  BACKGROUND_OVERLAY: 'rgba(32, 46, 63, 0.72)',
  DOCUMENT_OVERLAY: 'rgba(16, 45, 66, 0.5)',
  ROYAL_BLUE_20: 'rgba(60, 130, 240, 0.2)',
  ROYAL_BLUE_80: '#3c80ef',
  ACCENT: '#ed3e47',
  DARK_SKY_BLUE: 'rgb(60, 128, 239)',
  GRAY7: '#d7dee7',
  LINE_BREAK: '#e6e6e6',
  BLUE: '#3180f1',
  BLUE_HOVER: '#1F67CF',
  GRAY_2: '#c1d1e0',
  GRAY_3: '#dbdde1',
  GRAY_4: '#a6acb2',
  RED_ORANGE: '#ff3519',
  PRUSSIAN_BLUE: '#0C395B',
  APPROX_SOLITUDE: '#e7f0ff',
  HAWKES_BLUE: '#E2ECFD',
  LOADING_OVERLAY: 'rgba(255, 255, 255, 0.6)',
  SAN_JUAN: '#385375',
  SELAGO: '#e6f0fc',
  ROCK_BLUE: '#98afcd',
  KASHMIR_BLUE: '#4e6c92',
  WHISPER: '#f7f8fb',
  DEEP_COVE: '#061843',
  ANAKIWA: '#94bdff',
  PINKSALMON: '#ff93b0',
  INPUT_DISABLED: 'rgba(192, 208, 223, 0.2)',
  SUCCESS_10: 'var(--color-success-10)',
  SUCCESS_50: 'var(--color-success-50)',
  SUCCESS_60: 'var(--color-success-60)',
  WARNING_10: 'var(--color-warning-10)',
  WARNING_50: 'var(--color-warning-50)',
  WARNING_60: 'var(--color-warning-60)',
  OTHER_1: 'var(--color-other-1)',
  OTHER_2: 'var(--color-other-2)',
  OTHER_3: 'var(--color-other-3)',
  OTHER_4: 'var(--color-other-4)',
  OTHER_5: 'var(--color-other-5)',
  OTHER_8: 'var(--color-other-8)',
  OTHER_13: 'var(--color-other-13)',
  OTHER_14: 'var(--color-other-14)',
  OTHER_15: 'var(--color-other-15)',
  OTHER_16: 'var(--color-other-16)',
  OTHER_17: 'var(--color-other-17)',
  OTHER_18: 'var(--color-other-18)',
  OTHER_19: 'var(--color-other-19)',
  OTHER_20: 'var(--color-other-20)',
  OTHER_22: 'var(--color-other-22)',
  OTHER_23: 'var(--color-other-23)',
  OTHER_24: 'var(--color-other-24)',
  OTHER_25: 'var(--color-other-25)',
  OTHER_26: 'var(--color-other-26)',
  OTHER_27: 'var(--color-other-27)',
  OTHER_28: 'var(--color-other-28)',
  OTHER_29: 'var(--color-other-29)',
  PERSIAN_PINK: 'var(--color-persian-pink)',
  BLACK: 'var(--color-black)',
  BLUE_LIGHT: '#DDF0F4',
  LIGHT_PURPLE: 'var(--color-light-purple)',
  LIGHT_CYAN: '#edfbff',
  PURPLE: 'var(--color-purple)',

  WHITE_HOVER: 'var(--color-white-hover)',
  LUMIN_SIGN_PRIMARY: 'var(--color-lumin-sign-primary)',
  LUMIN_SIGN_OUTLINE: 'var(--color-lumin-sign-outline)',
  LUMIN_SIGN_LINK: 'var(--color-lumin-sign-link)',
  LUMIN_SIGN_WARNING: 'var(--color-lumin-sign-warning)',
  LUMIN_SIGN_PROCESS: 'var(--color-lumin-sign-process)',
};

export const DarkTheme = {
  BACKGROUND: Colors.SAN_JUAN,
  PRIMARY_TEXT: Colors.SELAGO,
  SECONDARY_TEXT: Colors.ROCK_BLUE,
  HEADER_TEXT: Colors.NEUTRAL_40,
  HEADER_TEXT_HOVER: Colors.NEUTRAL_80,
  BORDER: Colors.SAN_JUAN,
  TOOLTIP_BG: Colors.NEUTRAL_40,
  TOOLTIP_TEXT: Colors.NEUTRAL_100,
  DROPDOWN_HOVER_BG: Colors.NEUTRAL_90,
  PANEL_BG: Colors.NEUTRAL_90,
  FILTER_SELECTING: Colors.NEUTRAL_60,
  FILTER_HOVER: Colors.NEUTRAL_80,

  CHECKBOX_BORDER: Colors.NEUTRAL_60,
  CHECKBOX_BG: Colors.NEUTRAL_100,

  MOVE_DOCUMENT_MODAL: {
    HEADER_TEXT: Colors.NEUTRAL_10,
    INPUT_TEXT: Colors.NEUTRAL_60,
    DROP_DOWN_ICON: Colors.NEUTRAL_40,
    DROP_DOWN_ITEM_HOVER_BG: Colors.NEUTRAL_80,
    DROP_DOWN_ITEM_CONTENT: Colors.NEUTRAL_40,
    DROP_DOWN_ITEM_CONTENT_HOVER: Colors.NEUTRAL_20,
    INPUT_HOVER: Colors.NEUTRAL_80,
    DIVIDER_BG: Colors.NEUTRAL_80,
    FOLDER_TITLE: Colors.NEUTRAL_10,
    FOLDER_TITLE_DISABLED: Colors.NEUTRAL_50,
    EXPANDED_TITLE: Colors.NEUTRAL_40,
    BREADCRUMB_TITLE: Colors.NEUTRAL_40,
    BREADCRUMB_LAST_TITLE: Colors.NEUTRAL_20,
    EXPANDED_ITEM_HOVER: Colors.NEUTRAL_80,
    EXPANDED_ITEM_SELECTED: Colors.PRIMARY_90,
    EXPANDED_ITEM_AFTER_BG: Colors.PRIMARY_20,
    SEARCH_ICON: Colors.NEUTRAL_40,
    CONFIRM_MODAL_TITLE: Colors.NEUTRAL_10,
    CONFIRM_MODAL_TEXT: Colors.NEUTRAL_20,
    CONFIRM_MODAL_BG: Colors.NEUTRAL_100,
    CONFIRM_MODAL_CONTENT: Colors.NEUTRAL_20,
    CONFIRM_MODAL_CANCEL_BTN_BG: Colors.NEUTRAL_80,
    CONFIRM_MODAL_CANCEL_BTN_TEXT: Colors.NEUTRAL_20,
    TAB_LABEL: Colors.NEUTRAL_40,
    TAB_LABEL_ACTIVE: Colors.NEUTRAL_10,

    SHADOW: Shadows.MODAL_DARK_SHADOW,
    DIVIDER: Colors.KASHMIR_BLUE,
    BACKGROUND_BUTTON: Colors.KASHMIR_BLUE,
    COLOR_BUTTON: Colors.ROCK_BLUE,
    BACKGROUND_INFO: Colors.ANAKIWA,
    DESTINATION_ITEM: {
      BACKGROUND_CONTAINER: Colors.ROYAL_BLUE_HOVER,
      HOVER_BACKGROUND_CONTAINER: Colors.KASHMIR_BLUE,
    },
  },

  COPY_DOCUMENT: {
    TEXT_COLOR: Colors.NEUTRAL_10,
    DISABLED_TEXT_COLOR: Colors.NEUTRAL_50,
    TITLE_COLOR: Colors.NEUTRAL_40,
    SELECTED_ITEM_BG: Colors.PRIMARY_90,
    MODAL_SHADOW: 'none',
    ERROR: '#FFBCBF',
    DIVIDER: Colors.NEUTRAL_60,
    ACTIVE_DIVIDER: Colors.NEUTRAL_80,
    MODAL_TITLE: Colors.SELAGO,
    DESTINATION_LIST: {
      ARROW_DOWN: Colors.WHITE,
    },
    DESTINATION_ITEM: {
      BG_HOVER: Colors.KASHMIR_BLUE,
      ICON_COLOR: Colors.NEUTRAL_20,
      ARROW_HOVER: Colors.NEUTRAL_60,
    },
  },

  NOTE: {
    DIVIDER: Colors.NEUTRAL_80,
    SELECTED_NUMBER: Colors.NEUTRAL_40,
    EXPORT_BUTTON: Colors.NEUTRAL_20,
    EXPORT_BUTTON_BG: Colors.NEUTRAL_80,
    DROPDOWN_TEXT: Colors.NEUTRAL_40,
    FILTER_SELECTED_TEXT: Colors.NEUTRAL_90,
  },
};

export const LightTheme = {
  BACKGROUND: Colors.WHITE,
  PRIMARY_TEXT: Colors.PRIMARY,
  SECONDARY_TEXT: Colors.SECONDARY,
  HEADER_TEXT: Colors.NEUTRAL_60,
  HEADER_TEXT_HOVER: Colors.NEUTRAL_20,
  BORDER: Colors.CLOUDYBLUE,
  TOOLTIP_BG: Colors.NEUTRAL_100,
  TOOLTIP_TEXT: Colors.WHITE,
  DROPDOWN_HOVER_BG: Colors.NEUTRAL_10,
  PANEL_BG: Colors.NEUTRAL_0,
  FILTER_SELECTING: Colors.NEUTRAL_20,
  FILTER_HOVER: Colors.NEUTRAL_10,

  CHECKBOX_BORDER: Colors.NEUTRAL_30,
  CHECKBOX_BG: Colors.NEUTRAL_0,

  MOVE_DOCUMENT_MODAL: {
    HEADER_TEXT: Colors.NEUTRAL_100,
    INPUT_TEXT: Colors.NEUTRAL_100,
    DROP_DOWN_ICON: Colors.NEUTRAL_80,
    DROP_DOWN_ITEM_HOVER_BG: Colors.NEUTRAL_10,
    DROP_DOWN_ITEM_CONTENT: Colors.NEUTRAL_80,
    DROP_DOWN_ITEM_CONTENT_HOVER: Colors.NEUTRAL_80,
    INPUT_HOVER: Colors.PRIMARY_20,
    DIVIDER_BG: Colors.NEUTRAL_20,
    FOLDER_TITLE: Colors.NEUTRAL_100,
    FOLDER_TITLE_DISABLED: Colors.NEUTRAL_50,
    EXPANDED_TITLE: Colors.NEUTRAL_80,
    BREADCRUMB_TITLE: Colors.NEUTRAL_80,
    BREADCRUMB_LAST_TITLE: Colors.NEUTRAL_80,
    EXPANDED_ITEM_HOVER: Colors.NEUTRAL_10,
    EXPANDED_ITEM_SELECTED: Colors.PRIMARY_20,
    EXPANDED_ITEM_AFTER_BG: Colors.PRIMARY_80,
    SEARCH_ICON: Colors.NEUTRAL_60,
    CONFIRM_MODAL_TITLE: Colors.NEUTRAL_100,
    CONFIRM_MODAL_TEXT: Colors.NEUTRAL_80,
    CONFIRM_MODAL_BG: Colors.NEUTRAL_0,
    CONFIRM_MODAL_CONTENT: Colors.NEUTRAL_80,
    CONFIRM_MODAL_CANCEL_BTN_BG: Colors.NEUTRAL_10,
    CONFIRM_MODAL_CANCEL_BTN_TEXT: Colors.NEUTRAL_100,
    TAB_LABEL: Colors.NEUTRAL_60,
    TAB_LABEL_ACTIVE: Colors.NEUTRAL_100,

    SHADOW: Shadows.MODAL_LIGHT_SHADOW,
    DIVIDER: Colors.SOLITUDE,
    BACKGROUND_BUTTON: Colors.SOLITUDE,
    BACKGROUND_INFO: rgba(Colors.ROYAL_BLUE_80, 0.1),
    DESTINATION_LIST: {
      BACKGROUND_TRACK_VERTICAL: Colors.ALICEBLUE,
    },
    DESTINATION_ITEM: {
      BACKGROUND_CONTAINER: Colors.HAWKES_BLUE,
      COLOR_CONTAINER: Colors.DARK_SKY_BLUE,
      HOVER_BACKGROUND_CONTAINER: Colors.SOLITUDE,
    },
  },

  COPY_DOCUMENT: {
    TEXT_COLOR: Colors.NEUTRAL_100,
    DISABLED_TEXT_COLOR: Colors.NEUTRAL_50,
    TITLE_COLOR: Colors.NEUTRAL_80,
    SELECTED_ITEM_BG: Colors.PRIMARY_20,
    MODAL_SHADOW: Shadows.CONTAINER_SHADOW,
    ERROR: rgba(Colors.RED, 0.2),
    DIVIDER: Colors.NEUTRAL_20,
    ACTIVE_DIVIDER: Colors.NEUTRAL_100,
    MODAL_TITLE: Colors.PRIMARY,
    DESTINATION_LIST: {
      ARROW_DOWN: Colors.PRIMARY,
    },
    DESTINATION_ITEM: {
      BG_HOVER: Colors.SOLITUDE,
      ICON_COLOR: Colors.NEUTRAL_60,
      ARROW_HOVER: Colors.WHITE,
    },
  },

  NOTE: {
    DIVIDER: Colors.NEUTRAL_20,
    SELECTED_NUMBER: Colors.NEUTRAL_60,
    EXPORT_BUTTON: Colors.NEUTRAL_0,
    EXPORT_BUTTON_BG: Colors.SECONDARY_50,
    DROPDOWN_TEXT: Colors.NEUTRAL_80,
    FILTER_SELECTED_TEXT: Colors.PRIMARY_90,
  },
};

export const APP_THEME = {
  [THEME_MODE.DARK]: DarkTheme,
  [THEME_MODE.LIGHT]: LightTheme,
};
