sonar.projectKey=nitrolabs_lumin-web-viewer-2.0
sonar.organization=nitrolabs
sonar.exclusions=**/apis/**,**/core/**,**/event-listeners/**,**/test/**,**/__tests__/**,**/js/**,**/i18n/**,**/settings/**,**/assets/**,**/*.scss,**/*.html,**/node_modules/**,**/*.json,**/webpack**,**/helpers/**,**/*.styled.js,**/constants/styles/editor/*.ts,**/EditPanelInsertBlankPage.js,**/check-test-coverage.js, **/features/BillingModal/hooks/useClaimFreeTrial.tsx,**/features/CNC/CncComponents/CheckoutModal/components/PaymentElementForm/PaymentElementForm.tsx
sonar.javascript.lcov.reportPaths=src/coverage/lcov.info

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=lumin-web-viewer-2.0
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
