export const CHATBOT_FEEDBACK_DESCRIPTION_MAX_LENGTH = 255;

export const FEEDBACK_TYPE = {
  NONE: 'none',
  LIKE: 'like',
  DISLIKE: 'dislike',
};

export enum CHATBOT_FEEDBACK_REASONS {
  UI_BUG = 'UI_BUG',
  HARMFUL_CONTENT = 'HARMFUL_CONTENT',
  OVERACTIVE_REFUSAL = 'OVERACTIVE_REFUSAL',
  MISUNDERSTOOD_REQUEST = 'MISUNDERSTOOD_REQUEST',
  NOT_FACTUALLY_CORRECT = 'NOT_FACTUALLY_CORRECT',
  INCOMPLETE_RESPONSE = 'INCOMPLETE_RESPONSE',
  OTHER = 'OTHER',
}
