// Pending invoice will be stored here.

// Pending invoice will be generated by:
//  1. Admin upgrade Circle to Enterprise plan.
//  2. Admin customize Doc stack plan of Circle.
import * as mongoose from 'mongoose';

import { UpgradeInvoicePlanEnums } from 'Payment/payment.enum';

const EnterpriseUpgradeSchema = new mongoose.Schema({
  orgId: mongoose.Schema.Types.ObjectId,
  invoiceId: String,
  status: String,
  plan: {
    type: String,
    enum: UpgradeInvoicePlanEnums,
  },
});

EnterpriseUpgradeSchema.index({ orgId: 1 }, { unique: true });
EnterpriseUpgradeSchema.index({ invoiceId: 1 }, { unique: true });

export default EnterpriseUpgradeSchema;
