const ROLE = {
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  MEMBER: 'MEMBER',
  OWNER: 'OWNER',
  TEAM_ADMIN: 'TEAM ADMIN',
};

const MAX_MEMBERS = 1000;

const MAX_MEMBERS_ONLY_PROMOTION = 1000;

export { ROLE, MAX_MEMBERS, MAX_MEMBERS_ONLY_PROMOTION };

export const LIST_MEMBER_TO_SHOW = {
  MEMBER: 'MEMBER',
  PENDING_MEMBER: 'PENDING_MEMBER',
};
