/* eslint-disable sonarjs/no-duplicate-string */

// NOTE: Clone the colors to add to stripe iframe
import { cssVar, rgba } from 'polished';

const Colors = {
  GRAY_3: cssVar('--kiwi-colors-surface-outline-variant'),
  NEUTRAL_100: '#102d42',
  NEUTRAL_80: '#325167',
  NEUTRAL_40: '#9EB6C7',
  NEUTRAL_30: '#BCCFDC',
  NEUTRAL_20: '#DAE4EC',
  NEUTRAL_10: '#F1F5F8',
  PRIMARY_20: '#E5F9FF',
  PRIMARY_50: '#8edef4',
  PRIMARY_30: '#d4f5ff',
  SECONDARY_50: '#f2385a',
  SURFACE_ON_SURFACE: cssVar('--kiwi-colors-surface-on-surface'),
  SURFACE_ON_SURFACE_VARIANT: cssVar('--kiwi-colors-surface-on-surface-variant'),
  SAFETY_COLOR: '#00D66F',
  LIGHT_CYAN: '#edfbff',
  PLACEHOLDER_COLOR: rgba(
    cssVar('--kiwi-colors-surface-on-surface'),
    // eslint-disable-next-line no-magic-numbers
    parseFloat(cssVar('--kiwi-opacity-disabled-on-container')) / 100
  ),
  BOX_SHADOW_COLOR: cssVar('--kiwi-colors-core-secondary-container'),
  CORE_SECONDARY: cssVar('--kiwi-colors-core-secondary'),
  SEMANTIC_ERROR: cssVar('--kiwi-colors-semantic-error'),
  SURFACE_BLUE: cssVar('--kiwi-colors-support-blue-background-highest'),
  CORE_PRIMARY: cssVar('--kiwi-colors-support-dark-blue-background-low'),
  SURFACE_OUTLINE: cssVar('--kiwi-colors-surface-outline'),
};

export const Appearance = {
  theme: 'stripe',
  variables: {
    fontFamily: "'Axiforma', arial, sans-serif",
    fontWeightNormal: '400',
    fontWeightMedium: '500',
    fontWeightBold: '600',
    borderRadius: '8px',
    colorPrimary: Colors.SAFETY_COLOR,
    colorTextSecondary: Colors.NEUTRAL_40,
    colorTextPlaceholder: Colors.NEUTRAL_40,
    fontSizeBase: '14px',
    spacingGridColumn: '16px',
    spacingGridRow: '16px',
    colorIconPasscodeDeviceNotification: Colors.NEUTRAL_30,
    colorIconMenu: Colors.NEUTRAL_30,
    tabIconColor: Colors.NEUTRAL_100,
    tabIconSelectedColor: Colors.NEUTRAL_100,
  },
  rules: {
    '.Input': {
      fontFamily: 'var(--fontFamily)',
      backgroundColor: 'transparent',
      border: `1px solid ${Colors.NEUTRAL_30}`,
      boxShadow: 'none',
      padding: '0 16px',
      fontWeight: '500',
      lineHeight: '48px',
      color: Colors.NEUTRAL_100,
    },
    '.Input:focus': {
      outline: 'none',
      borderColor: Colors.PRIMARY_50,
      color: Colors.NEUTRAL_100,
      boxShadow: `0 0 0 1.2px ${Colors.PRIMARY_30}`,
    },
    '.Input--invalid': {
      outline: 'none',
      boxShadow: 'none',
      borderColor: Colors.SECONDARY_50,
      color: Colors.SECONDARY_50,
    },
    '.Label': {
      fontWeight: 'var(--fontWeightBold)',
      textTransform: 'capitalize',
      marginBottom: '4px',
      fontSize: '12px',
      color: Colors.NEUTRAL_80,
    },
    '.Error': {
      color: Colors.SECONDARY_50,
      marginTop: '4px',
      fontSize: '12px',
      fontWeight: '400',
    },
    '.Action': {
      color: Colors.NEUTRAL_30,
    },
    '.MenuAction': {
      color: Colors.NEUTRAL_30,
    },
    '.PickerItem--highlight': {
      borderColor: Colors.NEUTRAL_30,
      boxShadow: `0 0 0 1px ${Colors.NEUTRAL_30}`,
    },
    '.PickerItem--highlight:hover': {
      boxShadow: `0 0 0 1px ${Colors.NEUTRAL_30}`,
      borderColor: Colors.NEUTRAL_30,
    },
    '.PickerItem--new': {
      color: Colors.NEUTRAL_30,
    },
    '.Tab': {
      paddingLeft: '16px',
    },
    '.TabLabel': {
      color: Colors.NEUTRAL_100,
    },
    '.Tab:hover': {
      backgroundColor: Colors.NEUTRAL_10,
      borderRadius: '8px',
      borderColor: Colors.NEUTRAL_30,
      borderWidth: '1px',
      boxShadow: 'none',
    },
    '.Tab:active': {
      backgroundColor: Colors.NEUTRAL_20,
      borderRadius: '8px',
      borderColor: Colors.NEUTRAL_30,
      borderWidth: '1px',
      boxShadow: 'none',
    },
    '.Tab--selected': {
      backgroundColor: Colors.PRIMARY_20,
      borderRadius: '8px',
      borderColor: Colors.NEUTRAL_30,
      borderWidth: '1px',
      boxShadow: 'none',
    },
    '.Tab--selected:focus': {
      backgroundColor: Colors.PRIMARY_20,
      borderRadius: '8px',
      borderColor: Colors.NEUTRAL_30,
      borderWidth: '1px',
      boxShadow: 'none',
    },
    '.Tab--selected:hover': {
      backgroundColor: Colors.PRIMARY_20,
      borderRadius: '8px',
      borderColor: Colors.NEUTRAL_30,
      borderWidth: '1px',
      boxShadow: 'none',
    },
    '.Block': {
      paddingLeft: '16px',
    },
    '.Link': {
      color: Colors.NEUTRAL_30,
    },
  },
};

export const AppearanceNewUI = {
  ...Appearance,
  variables: {
    ...Appearance.variables,
    spacingGridColumn: '12px',
    spacingGridRow: '12px',
    fontFamily: "'Inter', arial, sans-serif",
    iconChevronDownColor: Colors.LUMIN_SIGN_PRIMARY,
    tabIconColor: Colors.LUMIN_SIGN_PRIMARY,
    tabIconSelectedColor: Colors.LUMIN_SIGN_PRIMARY,
  },
  rules: {
    ...Appearance.rules,
    '.Tab': {
      paddingLeft: '16px',
    },
    '.TabLabel': {
      color: Colors.LUMIN_SIGN_PRIMARY,
    },
    '.Tab:hover': {
      backgroundColor: 'rgba(25, 40, 51, 0.08)', // Colors.LUMIN_SIGN_PRIMARY with 8% opacity,
      borderRadius: '8px',
      borderColor: Colors.GRAY_3,
      borderWidth: '1px',
      boxShadow: 'none',
      color: Colors.LUMIN_SIGN_PRIMARY,
    },
    '.Tab:active': {
      backgroundColor: 'rgba(25, 40, 51, 0.12)', // Colors.LUMIN_SIGN_PRIMARY with 12% opacity,`,
      borderRadius: '8px',
      borderColor: Colors.GRAY_3,
      borderWidth: '1px',
      boxShadow: 'none',
    },
    '.Tab--selected': {
      backgroundColor: Colors.LIGHT_CYAN,
      borderRadius: '8px',
      borderColor: Colors.LUMIN_SIGN_PRIMARY,
      borderWidth: '1px',
      boxShadow: 'none',
    },
    '.Tab--selected:focus': {
      backgroundColor: Colors.LIGHT_CYAN,
      borderRadius: '8px',
      borderColor: Colors.LUMIN_SIGN_PRIMARY,
      borderWidth: '1px',
      boxShadow: 'none',
    },
    '.Tab--selected:hover': {
      backgroundColor: Colors.LIGHT_CYAN,
      borderRadius: '8px',
      borderColor: Colors.LUMIN_SIGN_PRIMARY,
      borderWidth: '1px',
      boxShadow: 'none',
    },
    '.Input': {
      ...Appearance.rules['.Input'],
      fontSize: '14px',
      lineHeight: '40px',
      color: Colors.LUMIN_SIGN_PRIMARY,
    },
    '.Label': {
      ...Appearance.rules['.Label'],
      fontFamily: 'var(--fontFamily)',
      fontWeight: 'var(--fontWeightMedium)',
      color: Colors.LUMIN_SIGN_PRIMARY,
      lineHeight: '100%',
    },
    '.TermsText': {
      fontFamily: 'var(--fontFamily)',
      fontWeight: 'var(--fontWeightNormal)',
      fontSize: '11px',
      lineHeight: '150%',
      color: Colors.NEUTRAL_80,
    },
  },
};

export const AppearanceReskin = {
  ...Appearance,
  variables: {
    ...Appearance.variables,
    spacingGridColumn: '12px',
    spacingGridRow: '12px',
    fontFamily: '"Inter", arial, sans-serif',
    iconChevronDownColor: Colors.SURFACE_ON_SURFACE,
    colorText: Colors.SURFACE_ON_SURFACE,
    colorTextPlaceholder: Colors.PLACEHOLDER_COLOR,
    colorIconRedirect: Colors.SURFACE_OUTLINE,
    colorTextSecondary: Colors.SURFACE_OUTLINE,
    spacingTab: '6px',
  },
  rules: {
    ...Appearance.rules,
    '.Input': {
      ...Appearance.rules['.Input'],
      color: Colors.SURFACE_ON_SURFACE,
      padding: '8px 10px',
      fontSize: '16px',
      fontWeight: '420',
      lineHeight: '22px',
      border: `1px solid ${Colors.GRAY_3}`,
    },
    '.Input:focus': {
      outline: 'none',
      borderColor: Colors.CORE_SECONDARY,
      color: Colors.SURFACE_ON_SURFACE,
      boxShadow: `0px 1px 2px 0px ${Colors.BOX_SHADOW_COLOR}, 0px 0px 0px 4px ${Colors.BOX_SHADOW_COLOR}`,
    },
    '.Input--invalid': {
      ...Appearance.rules['.Input--invalid'],
      outline: 'none',
      boxShadow: 'none',
      borderColor: Colors.SEMANTIC_ERROR,
      color: Colors.SEMANTIC_ERROR,
    },
    '.Error': {
      ...Appearance.rules['.Error'],
      color: Colors.SEMANTIC_ERROR,
      fontWeight: '420',
      lineHeight: '16px',
    },
    '.Label': {
      ...Appearance.rules['.Label'],
      color: Colors.SURFACE_ON_SURFACE,
      fontFamily: 'var(--fontFamily)',
      fontWeight: 'var(--fontWeightMedium)',
      fontSize: '14px',
      lineHeight: '20px',
      textTransform: 'none',
    },
    '.TermsText': {
      fontFamily: 'var(--fontFamily)',
      fontWeight: '420',
      fontSize: '12px',
      lineHeight: '16px',
      color: Colors.SURFACE_ON_SURFACE_VARIANT,
    },
    '.Tab': {
      padding: '8px 16px',
      borderRadius: '8px',
      borderWidth: '1px',
      boxShadow: 'none',
      borderColor: Colors.GRAY_3,
    },
    '.Tab:hover': {
      borderRadius: '8px',
      borderWidth: '1px',
      boxShadow: 'none',
      borderColor: Colors.GRAY_3,
      backgroundColor: 'rgba(25, 40, 51, 0.08)',
    },
    '.Tab:active': {
      borderRadius: '8px',
      borderWidth: '1px',
      boxShadow: 'none',
      borderColor: Colors.GRAY_3,
      backgroundColor: 'rgba(25, 40, 51, 0.12)',
    },
    '.Tab:focus': {
      borderRadius: '8px',
      borderWidth: '1px',
      boxShadow: 'none',
      borderColor: Colors.GRAY_3,
    },
    '.Tab--selected': {
      borderRadius: '8px',
      borderWidth: '1px',
      boxShadow: 'none',
      borderColor: Colors.CORE_PRIMARY,
      backgroundColor: Colors.SURFACE_BLUE,
    },
    '.Tab--selected:focus': {
      borderRadius: '8px',
      borderWidth: '1px',
      boxShadow: 'none',
      borderColor: Colors.CORE_PRIMARY,
      backgroundColor: Colors.SURFACE_BLUE,
    },
    '.Tab--selected:hover': {
      borderRadius: '8px',
      borderWidth: '1px',
      boxShadow: 'none',
      borderColor: Colors.CORE_PRIMARY,
      backgroundColor: Colors.SURFACE_BLUE,
    },
    '.Tab--selected:active': {
      borderRadius: '8px',
      borderWidth: '1px',
      boxShadow: 'none',
      borderColor: Colors.CORE_PRIMARY,
      backgroundColor: Colors.SURFACE_BLUE,
    },
    '.TabLabel': {
      fontFamily: 'var(--fontFamily)',
      fontSize: '14px',
      fontWeight: '420',
      lineHeight: '20px',
      color: Colors.SURFACE_ON_SURFACE,
    },
    '.BlockDivider': {
      background: Colors.GRAY_3,
      marginTop: '12px',
      marginBottom: '12px',
    },
    '.Block': {
      padding: '12px 16px',
      borderColor: Colors.GRAY_3,
      fontFamily: 'var(--fontFamily)',
      fontSize: '14px',
      fontWeight: '420',
      lineHeight: '20px',
      color: Colors.SURFACE_ON_SURFACE,
    },
    '.RedirectText': {
      fontFamily: 'var(--fontFamily)',
      fontSize: '12px',
      fontWeight: '420',
      lineHeight: '16px',
      color: Colors.SURFACE_ON_SURFACE_VARIANT,
    },
    '.TermsLink': {
      color: Colors.SURFACE_ON_SURFACE_VARIANT,
    },
  },
};
