export const CATEGORY_JSON_PATH = {
  STAGING: "strapi/data/json/staging-category.json",
  PRODUCTION: "strapi/data/json/production-category.json",
};

export enum ParentCategory {
  INDUSTRY = "industry",
  TASK = "task",
  FILTER = "form-type-filter",
}

export const ParentCategoryId = {
  INDUSTRY: 1,
  TASK: 2,
  FILTER: 3,
}

export enum ParentCategoryName {
  INDUSTRY = "Industry",
  TASK = "Task",
  FILTER = "Form Type Filter",
}

export const INDUSTRY_CATEGORIES = [
  "Agencies",
  "Construction",
  "Consultants",
  "Education",
  "Executive assistants",
  "Finance",
  "Government forms",
  "Health",
  "HR",
  "IT",
  "Contractors",
  "Legal",
  "Marketing",
  "Nonprofit",
  "Personal",
  "Property management",
  "Real estate",
  "Students",
  "Teachers",
  "Agriculture",
  "Environmental",
];

export const TASK_CATEGORIES = [
  "Administration",
  "Client onboarding",
  "Community action",
  "Compliance",
  "Claims",
  "Event management",
  "Immigration",
  "Insurance",
  "Itineraries",
  "Invoicing",
  "Job hunting",
  "Loan application",
  "Leave request",
  "Licensing",
  "Medical forms",
  "New employee onboarding",
  "Parental forms",
  "Rental application",
  "Security",
  "Tax",
  "Travel forms",
  "Vehicle",
  "Management",
];

export const FORM_TYPES = [
  "Agreements",
  "Applications",
  "Assessments",
  "Attestations",
  "Affidavits",
  "Approvals",
  "Authorizations",
  "Bill of sale",
  "Complaints",
  "Contracts",
  "Checklists",
  "Consent forms",
  // "Claims",
  "Certification forms",
  "Certificates",
  "Disputes",
  "Declarations",
  "Directives",
  "Enrollment forms",
  "Handbooks",
  "Instructions",
  "Invoices",
  "Letters",
  "Notices",
  "Nominations",
  "Notifications",
  "Orders",
  "Offers",
  "Payment forms",
  "Permission slips",
  "Petitions",
  "Plans",
  "Policies",
  "Proposals",
  "Purchase orders",
  "Questionnaires",
  "Registrations",
  "Requests",
  "Reports",
  "Referrals",
  "Resumes",
  "Statements",
  "Submissions",
  "Tax forms",
  "Verification forms",
  "Visa forms",
  "Worksheets",
  "Permits",
  "Information forms",
  "Motions",
  "Waivers",
  "Appeals",
  "Briefs",
];