export enum DocumentEventNames {
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  DOCUMENT_OPENED = 'DOCUMENT_OPENED',
  DOCUMENT_DELETED = 'DOCUMENT_DELETED',
  DOCUMENT_ANNOTATED = 'DOCUMENT_ANNOTATED',
  DOCUMENT_SIGNED = 'DOCUMENT_SIGNED',
  DOCUMENT_MANIPULATED = 'DOCUMENT_MANIPULATED',
  DOCUMENT_COMMENTED = 'DOCUMENT_COMMENTED',
  COMMENT_REPLIED = 'COMMENT_REPLIED',
  COMMENT_MENTIONED = 'COMMENT_MENTIONED',
  COMMENT_DELETED = 'COMMENT_DELETED',
  DOCUMENT_SHARED = 'DOCUMENT_SHARED',
  DOCUMENT_REQUESTED_TO_ACCESS = 'DOCUMENT_REQUESTED_TO_ACCESS',
  DOCUMENT_USED = 'DOCUMENT_USED',
  TEMPLATE_USED = 'TEMPLATE_USED',
}

export enum NonDocumentEventNames {
  TRANSACTIONAL_EMAIL_SENT = 'TRANSACTIONAL_EMAIL_SENT',
  // Team events
  TEAM_MEMBER_ADDED = 'TEAM_MEMBER_ADDED',
  TEAM_MEMBER_REMOVED = 'TEAM_MEMBER_REMOVED',
  TEAM_MEMBER_LEFT = 'TEAM_MEMBER_LEFT',
  TEAM_OWNERSHIP_TRANSFERED = 'TEAM_OWNERSHIP_TRANSFERED',
  TEAM_MEMBER_ROLE_CHANGED = 'TEAM_MEMBER_ROLE_CHANGED',
  TEAM_PLAN_CHANGED = 'TEAM_PLAN_CHANGED',
  TEAM_PLAN_CANCELED = 'TEAM_PLAN_CANCELED',
  TEAM_PLAN_RENEWED = 'TEAM_PLAN_RENEWED',
  // Personal events
  PERSONAL_PLAN_CHANGED = 'PERSONAL_PLAN_CHANGED',
  PERSONAL_PLAN_RENEWED = 'PERSONAL_PLAN_RENEWED',
  PERSONAL_PLAN_CANCELED = 'PERSONAL_PLAN_CANCELED',
  PERSONAL_ACCOUNT_CREATED = 'PERSONAL_ACCOUNT_CREATED',
  PERSONAL_SIGNED_IN = 'PERSONAL_SIGNED_IN',
  PERSONAL_SIGNED_OUT = 'PERSONAL_SIGNED_OUT',
  // Organization events
  ORGANIZATION_CREATED = 'ORGANIZATION_CREATED',
  ORGANIZATION_DELETED = 'ORGANIZATION_DELETED',
  ORG_TEAM_CREATED = 'ORG_TEAM_CREATED',
  ORG_TEAM_DELETED = 'ORG_TEAM_DELETED',
  ORG_MEMBER_ADDED = 'ORG_MEMBER_ADDED',
  ORG_PLAN_UPGRADED = 'ORG_PLAN_UPGRADED',
  ORG_PLAN_RENEWED = 'ORG_PLAN_RENEWED',
  ORG_PLAN_CANCELED = 'ORG_PLAN_CANCELED',
  ORG_MEMBER_JOINED = 'ORG_MEMBER_JOINED',
}

export enum PlanActionEvent {
  ENTERPRISE_UPGRADE_CREATED = 'ENTERPRISE_UPGRADE_CREATED',
  ENTERPRISE_UPGRADE_PAID = 'ENTERPRISE_UPGRADE_PAID',
  ENTERPRISE_UPGRADE_EXPIRED = 'ENTERPRISE_UPGRADE_EXPIRED',
  ORG_PLAN_CANCELED = 'ORG_PLAN_CANCELED',
  USER_PLAN_CANCELED = 'USER_PLAN_CANCELED',
  DOCSTACK_PLAN_CREATED = 'DOCSTACK_PLAN_CREATED',
  DOCSTACK_PLAN_PAID = 'DOCSTACK_PLAN_PAID',
  DOCSTACK_PLAN_EXPIRED = 'DOCSTACK_PLAN_EXPIRED',
}

export enum OrgActionEvent {
  ORGANIZATION_CREATED = 'ORGANIZATION_CREATED',
  ORGANIZATION_DELETED = 'ORGANIZATION_DELETED',
  ORGANIZATION_BLACKLISTED = 'ORGANIZATION_BLACKLISTED',
  ORGANIZATION_WHITELISTED = 'ORGANIZATION_WHITELISTED',
  CUSTOM_ORG_CONVERTED_TO_MAIN = 'CUSTOM_ORG_CONVERTED_TO_MAIN',
  MAIN_ORG_CONVERTED_TO_CUSTOM = 'MAIN_ORG_CONVERTED_TO_CUSTOM',
  ORGANIZATION_EDITED = 'ORGANIZATION_EDITED',
  ASSOCIATED_DOMAIN_REMOVED = 'ASSOCIATED_DOMAIN_REMOVED',
}

export enum AdminActionEvent {
  ADMIN_ADDED = 'ADMIN_ADDED',
  ADMIN_DELETED = 'ADMIN_DELETED',
  ADMIN_CHANGE_ROLE = 'ADMIN_CHANGE_ROLE'
}

export enum UserActionEvent {
  USER_DELETED = 'USER_DELETED',
  USER_BLACKLISTED = 'USER_BLACKLISTED',
  USER_WHITELISTED = 'USER_WHITELISTED',
  USER_EMAIL_CHANGED = 'USER_EMAIL_CHANGED',
}

export enum EventScopes {
  PERSONAL = 'PERSONAL',
  TEAM = 'TEAM',
  ORGANIZATION = 'ORGANIZATION',
  ADMIN = 'ADMIN',
  SYSTEM = 'SYSTEM',
}

export enum ExportPrefixEnums {
  SIGNED_IN = 'signed_in',
  SIGNED_OUT = 'signed_out',
  UPLOADED_DOC = 'uploaded_doc',
  OPENED_DOC = 'opened_doc',
  CHANGED_PLAN = 'changed_plan',
  INVITATION = 'invitation',
}

export enum SourceActions {
  INVITATION_SIGN_UP = 'INVITATION_SIGN_UP',
  REGULAR_SIGN_UP = 'REGULAR_SIGN_UP',
  CUSTOM_ORG_CONVERTED_TO_MAIN = 'CUSTOM_ORG_CONVERTED_TO_MAIN',
  ORGANIZATION_DELETED = 'ORGANIZATION_DELETED',
  USER_DELETED = 'USER_DELETED',
}

export enum CommunityTemplateActionEvent {
  TEMPLATE_PUBLISHED = 'TEMPLATE_PUBLISHED',
  TEMPLATE_UNPUBLISHED = 'TEMPLATE_UNPUBLISHED',
  TEMPLATE_DELETED = 'TEMPLATE_DELETED',
  TEMPLATE_CREATED = 'TEMPLATE_CREATED',
  TEMPLATE_EDITED = 'TEMPLATE_EDITED',
}

export enum TemplateCategoryActionEvent {
  CATEGORY_CREATED = 'CATEGORY_CREATED',
  CATEGORY_EDITED = 'CATEGORY_EDITED',
  CATEGORY_DELETED = 'CATEGORY_DELETED',
}

export type AdminEventNameType =
  PlanActionEvent |
  OrgActionEvent |
  AdminActionEvent |
  UserActionEvent |
  CommunityTemplateActionEvent |
  TemplateCategoryActionEvent;

export type EventNameType = DocumentEventNames | NonDocumentEventNames;
export type EventScopeType = keyof typeof EventScopes;
