export const EXCHANGE_TYPE = {
  DIRECT: 'direct',
  FANOUT: 'fanout',
  HEADERS: 'headers',
  DELAY: 'x-delayed-message',
};

export const ROUTING_KEY = {
  LUMIN_WEB: 'lumin_web',
  USER_REGISTRATION_SUCCESS: 'lumin_sign.user_registration.succeeded',
  DOCUMENT_VERSION_CREATE: 'lumin_editor.document_version_create',
  LUMIN_AI_SIMPLE_PDF_DETECTION_DEFAULT: 'lumin_ai_simple_pdf_detection_default',
  LUMIN_WEB_SYNC_OIDC_AVATAR_DEFAULT: 'lumin_web.sync_oidc_avatar.default',
  LUMIN_WEB_SYNC_OIDC_AVATAR_DELAY: 'lumin_web.sync_oidc_avatar.delay',
  LUMIN_FFD_APPLY_AI_FIELDS: 'lumin_ffd_apply_ai_fields_routing_key',
  LUMIN_COMPRESS_PDF: 'lumin_compress_pdf_routing_key',
  LUMIN_WEB_DOCUMENT_SHARE_IN_SLACK_DEFAULT: 'lumin_web.document_share_in_slack.default',
  LUMIN_RAG_DOCUMENT_INDEXING_DEFAULT: 'lumin_rag.document_indexing.default',
  LUMIN_RAG_DOCUMENT_INDEXING_DELETE: 'lumin_rag.document_indexing.delete',
  LUMIN_RAG_DOCUMENT_INDEXING_UPDATE: 'lumin_rag.document_indexing.update',
  LUMIN_RAG_DOCUMENT_INDEXING_STATUS_SYNC: 'lumin_rag.document_indexing.status_sync',
  LUMIN_RAG_DOCUMENT_INDEXING_DLX: 'lumin_rag.document_indexing.dlx',
  LUMIN_WEB_SYNC_SIGN_NOTIFICATION_DEFAULT: 'lumin_web.sync_sign_notification.default',
  LUMIN_WEB_TRANSFER_WORKSPACE: 'lumin_web.transfer_workspace',
  LUMIN_WEB_DELETE_WORKSPACE: 'lumin_web.delete_workspace',
  LUMIN_RAG_DOCUMENT_INDEXING_PRIORITY: 'lumin_rag.document_indexing.priority',
  LUMIN_SIGN_SYNC_PROOFING_STATUS: 'lumin_sign.proofing.sync_status',
  LUMIN_SIGN_UPDATE_WORKSPACE_PAYMENT: 'lumin_sign.update_workspace_payment.succeeded',
  LUMIN_SIGN_UPLOADED_AGREEMENT_SYNC_DOC_STACKS: 'lumin_sign.uploaded_agreement.sync_doc_stacks',
};

export const EXCHANGE_KEYS = {
  NOTIFICATION: 'notification',
  USER_REGISTRATION: 'lumin_sign.user',
  DOCUMENT_VERSIONS: 'lumin_editor.document_versions',
  LUMIN_FFD_APPLY_AI_FIELDS: 'lumin_ffd_apply_ai_fields_exchange',
  LUMIN_AI_SIMPLE_PDF: 'lumin_ai_simple_pdf_exchange',
  FORM_FIELD_DETECTION: 'form_field_detection',
  LUMIN_COMPRESS_PDF: 'lumin_compress_pdf_exchange',
  DEFAULT: '',
  LUMIN_WEB_USER: 'lumin_web.user',
  LUMIN_WEB_DOCUMENT_SHARING: 'lumin_web.document_sharing',
  LUMIN_RAG_DOCUMENT_INDEXING: 'lumin_rag.document_indexing',
  LUMIN_RAG_DOCUMENT_INDEXING_DLX: 'lumin_rag.document_indexing.dlx',
  WORKSPACE: 'workspace_exchange',
  LUMIN_SIGN_X_EDITOR: 'lumin_sign.x_editor',
  LUMIN_SIGN_UPDATE_WORKSPACE_PAYMENT: 'lumin_sign.update_workspace_payment',
  LUMIN_SIGN_UPLOADED_AGREEMENT: 'lumin_sign.uploaded_agreement',
};

export const QUEUES = {
  LUMIN_WEB_NOTIFICATION: 'lumin_web_notification',
  LUMIN_SFD_RESULT_QUEUE: 'lumin_sfd_result',
  LUMIN_SFD_FAIL_INPUT_QUEUE: 'lumin_sfd_fail_task',
  LUMIN_USER_REGISTRATION_QUEUE: 'lumin_sign.user_registration',
  LUMIN_DOCUMENT_VERSION_CREATE: 'lumin_editor.document_version_create',
  LUMIN_FFD_APPLY_AI_FIELDS: 'lumin_ffd_apply_ai_fields_queue',
  LUMIN_AI_SIMPLE_PDF_DETECTION: 'lumin_ai_simple_pdf_detection',
  LUMIN_COMPRESS_PDF: 'lumin_compress_pdf_queue',
  LUMIN_WEB_SYNC_OIDC_AVATAR: 'lumin_web.sync_oidc_avatar',
  LUMIN_WEB_SYNC_OIDC_AVATAR_DELAY: 'lumin_web.sync_oidc_avatar.delay',
  LUMIN_WEB_DOCUMENT_SHARE_IN_SLACK: 'lumin_web.document_share_in_slack',
  LUMIN_RAG_DOCUMENT_INDEXING: 'lumin_rag_document_indexing_queue',
  LUMIN_RAG_DOCUMENT_INDEXING_DELETE: 'lumin_rag_document_indexing_delete_queue',
  LUMIN_RAG_DOCUMENT_INDEXING_UPDATE: 'lumin_rag_document_indexing_update_queue',
  LUMIN_RAD_DOCUMENT_INDEXING_UPLOADED: 'lumin_rad_document_indexing_uploaded_queue',
  LUMIN_RAG_DOCUMENT_INDEXING_STATUS_SYNC: 'lumin_rag_document_indexing_status_sync_queue',
  LUMIN_RAG_DOCUMENT_INDEXING_DLX: 'lumin_rag_document_indexing_dlx_queue',
  LUMIN_WEB_SYNC_SIGN_NOTIFICATION: 'lumin_web.sync_sign_notification',
  LUMIN_RAG_DOCUMENT_INDEXING_PRIORITY: 'lumin_rag_document_indexing_priority_queue',
  LUMIN_SIGN_PROOFING_SYNC_STATUS: 'lumin_sign.proofing.sync_status',
  LUMIN_SIGN_UPDATE_WORKSPACE_PAYMENT: 'lumin_sign.update_workspace_payment_queue',
  LUMIN_SIGN_UPLOADED_AGREEMENT: 'lumin_sign.uploaded_agreement',
};
