export enum ButtonColor {
  PRIMARY = 'PRIMARY',
  PRIMARY_DARK = 'PRIMARY_DARK',
  SECONDARY = 'SECONDARY',
  SECONDARY_DARK = 'SECONDARY_DARK',
  TERTIARY = 'TERTIARY',
  HYPERLINK = 'HYPERLINK',
  PRIMARY_DIM = 'PRIMARY_DIM',
  GHOST = 'GHOSt'
}
