export const LEFT_PANEL_VALUES = {
  BOOKMARK: 'BOOKMARK',
  THUMBNAIL: 'THUMBNAIL',
  OUTLINE: 'OUTLINE',
};

export const TOOL_PROPERTIES_VALUE = {
  DEFAULT: 'DEFAULT',
  MERGE: 'MERGE',
  ROTATE: 'ROTATE',
  INSERT: 'INSERT',
  SPLIT_EXTRACT: 'SPLIT_EXTRACT',
  MOVE: 'MOVE',
  DELETE: 'DELETE',
  CROP: 'CROP',
  EDIT_PDF: 'EDIT_PDF',
  FORM_BUILD: 'FORM_BUILD',
  REVISION: 'REVISION',
  MEASURE: 'MEASURE',
};
