user  nginx;
worker_processes  1;

pid /var/cache/nginx/nginx.pid;

events {
    worker_connections  1024;
}


http {
    http2 on;
    http2_push_preload on;
    include       /etc/nginx/mime.types;
    types {
        application/x-dtbresource+xml res;
    }
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';


    sendfile        on;
    client_max_body_size 50M;

    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;
    #brotli on;
    #brotli_comp_level 6;
    #brotli_types  application/octet-stream


    server {
			listen       8080;
			server_name  localhost;
			root   /usr/share/nginx/html;

			location / {
					index  index.app.html;
					try_files $uri /index.app.html;
			}

            location ~* ^/(es|fr|vi|pt)/open/google/?$ {
                rewrite ^/(es|fr|vi|pt)/open/google https://$host/open/google redirect;
            }

			include 						includes/sourcemap.conf;

			location ~* /(MemGrow.*.wasm|.*gz.wasm) {
					types { }
					default_type application/wasm;
			}

			location ~* /(MemGrow.*.mem|.*gz\.mem) {
					types { }
					default_type application/octet-stream;
			}

			location ~* /(.*gz.*\.mem) {
					types { }
					default_type application/octet-stream;
			}

        location ~* /InfixServer.mem {
            types { }
            default_type application/octet-stream;
        }

        location ~* /InfixServer.wasm {
            types { }
            default_type application/wasm;
        }

			location ~* \.(mem)$ {
					types { }
					add_header Content-Encoding 'br';
					expires           30d;
					add_header        Cache-Control "public";
			}

			location ~* \.(woff2)$ {
					expires           30d;
					add_header        Cache-Control "public";
			}

        location ~* \.(wasm)$ {
            types { }
            default_type application/wasm;
            expires           30d;
            add_header        Cache-Control "public";
        }

        location ~* \.(wasm\.br)$ {
            types { }
            default_type application/wasm;
            add_header Content-Encoding 'br';
            expires           30d;
            add_header        Cache-Control "public";
        }

        location ~* core\/webviewer-core\.min\..*\.js  {
            charset utf-8;
            charset_types application/javascript;
        }

        # location ~* ^\/(open\/google\/.+|open\/dropbox\/.+)$ {
        #     index  index.html;
        #     try_files $uri /index.html;
        #     add_header        Cache-Control "no-store";
        # }

    #    location ~* ^\/(contact|denied|viewer\/.+|teams\/notFound|documents\/notFound|documents|teams|teams\/.+|setting|setting\/.+|payment\/.+\/.+|plans|pricings|authentication|verify-account|unsubscribe-email|guide|guide\/.+\/.+|personal-data|privacy-policy|terms-of-use)$ {
    #        index  index.app.html;
    #        try_files $uri /index.app.html;
    #        add_header        Cache-Control "no-cache, no-store, must-revalidate";
    #    }

        # location = /index.html {
        #     try_files $uri /index.html;
        #     add_header        Cache-Control "no-cache, no-store, must-revalidate";
        # }


        location = /index.app.html {
            try_files           $uri /index.app.html;
            add_header          Cache-Control "no-cache, no-store, must-revalidate";
        }

        # redirect server error pages to the static page /50x.html
        error_page      404 /index.html;
        error_page      500 502 503 504  /50x.html;
    #    location = /50x.html {
    #        root   /usr/share/nginx/html;
    #    }
    }
}
