export const CNCButtonName = {
  REDIRECT_TO_TRIAL_PAGE_ON_BANNER_VIEWER: 'redirectToTrialPageOnBannerViewer',
  GO_TO_APP_STORE_PAGE: 'goToAppStorePage',
  GO_TO_GOOGLE_PLAY_PAGE: 'goToGooglePlayPage',
  GO_TO_DOWNLOAD_DESKTOP_APP_PAGE: 'goToDownloadDesktopAppPage',
  REQUEST_TO_JOIN_ORGANIZATION_ON_BUSINESS_DOMAIN_TRIAL_ONBOARDING_FLOW:
    'requestToJoinOrganizationOnBusinessDomainTrialOnboardingFlow',
  JOIN_ORGANIZATION_ON_BUSINESS_DOMAIN_TRIAL_ONBOARDING_FLOW: 'joinOrganizationOnBusinessDomainTrialOnboardingFlow',
  ACCEPT_INVITATION_ON_BUSINESS_DOMAIN_TRIAL_ONBOARDING_FLOW: 'acceptInvitationOnBusinessDomainTrialOnboardingFlow',
  SKIP_ONBOARDING_FLOW_FROM_OPEN_DRIVE: 'skipOnboardingFlowFromOpenDrive',
  DISMISS_PROMOTE_CHROME_EXTENSION_MODAL: 'dismissPromoteChromeExtensionModal',
  GO_TO_CHROME_EXTENSION_PAGE: 'goToChromeExtensionPage',
  KEEP_SUBSCRIPTION: 'keepSubscription',
  CANCEL_SUBSCRIPTION: 'cancelSubscription',
  FINISH_CANCEL_SUBSCRIPTION: 'finishCancelSubscription',
  BACK_TO_HOME: 'backToHomePage',
  CANCEL_SUBSCRIPTION_ON_BILLING_DETAIL_PAGE: 'cancelSubscriptionOnBillingDetailPage',
  PRO_START_FREE_TRIAL: 'proStartFreeTrial',
  BUSINESS_START_FREE_TRIAL: 'businessStartFreeTrial',
  VIEW_ALL_PLANS: 'viewAllPlans',
  NEW_CHECKOUT_PAGE_PERIOD_SWITCH_MONTHLY: 'newCheckoutPagePeriodSwitchMonthly',
  NEW_CHECKOUT_PAGE_PERIOD_SWITCH_YEARLY: 'newCheckoutPagePeriodSwitchYearly',
  NEW_CHECKOUT_PAGE_PLAN_SWITCH_STARTER: 'newCheckoutPagePlanSwitchStarter',
  NEW_CHECKOUT_PAGE_PLAN_SWITCH_PRO_TRIAL: 'newCheckoutPagePlanSwitchProTrial',
  NEW_CHECKOUT_PAGE_PLAN_SWITCH_PRO: 'newCheckoutPagePlanSwitchPro',
  NEW_CHECKOUT_PAGE_PLAN_SWITCH_BUSINESS_TRIAL: 'newCheckoutPagePlanSwitchBusinessTrial',
  INVITE_COLLABORATORS: 'inviteCollaborators',
  SKIP_INVITE_COLLABORATORS: 'skipInviteCollaborators',
  START_FREE_TRIAL: 'StartFreeTrial',
  LUMIN_PDF: 'luminpdf',
  LUMIN_SIGN: 'luminsign',
  AGREEMENT_GEN: 'agreementgen',
  DOCUMENTS: 'documents',
  GET_HELP_LUMIN_PDF: 'get-help-luminpdf',
  GET_HELP_LUMIN_SIGN: 'get-help-luminsign',
  GET_HELP_AGREEMENT_GEN: 'get-help-agreementgen',
  GET_HELP_LUMIN_PDF_WORKSPACE_AND_SPACE: 'get-help-luminpdf-workspace-and-space',
  TRY_LUMIN_SIGN_FREE: 'TryLuminSignFree',
  TRY_AGREEMENT_GEN_FREE: 'TryAgreementGenFree',
  GET_STARTED: 'GetStarted',
  DONT_SHOW_THIS_AGAIN: 'DontShowThisAgain',
  START_VIA_SAMPLE_PROMPT: 'start_via_sample_prompt',
  GO_TO_AGREEMENT_GEN: 'go_to_agreementgen',
  UPLOAD_AVATAR_FROM_DEVICE: 'uploadAvatarFromDevice',
  OPEN_SUGGESTION_MODAL_FROM_WS_SETTINGS: 'openSuggestionModalFromWsSettings',
  OPEN_SUGGESTION_MODAL_FROM_WS_INFO_MODAL: 'openSuggestionModalFromWsInfoModal',
  OPEN_SUGGESTION_MODAL_FROM_WS_SWITCHER: 'openSuggestionModalFromWsSwitcher',
  OPEN_SUGGESTION_MODAL_FROM_WS_LIST: 'openSuggestionModalFromWsList',
  OPEN_SUGGESTION_MODAL_FROM_WS_CREATE: 'openSuggestionModalFromWsCreate',
};

export const CNCButtonPurpose = {
  [CNCButtonName.REDIRECT_TO_TRIAL_PAGE_ON_BANNER_VIEWER]: 'Redirect to trial page on banner viewer',
  [CNCButtonName.GO_TO_APP_STORE_PAGE]: 'Go to app store page',
  [CNCButtonName.GO_TO_GOOGLE_PLAY_PAGE]: 'Go to google play page',
  [CNCButtonName.GO_TO_DOWNLOAD_DESKTOP_APP_PAGE]: 'Go to download desktop app page',
  [CNCButtonName.REQUEST_TO_JOIN_ORGANIZATION_ON_BUSINESS_DOMAIN_TRIAL_ONBOARDING_FLOW]:
    'Request to join organization on business domain trial onboarding flow',
  [CNCButtonName.JOIN_ORGANIZATION_ON_BUSINESS_DOMAIN_TRIAL_ONBOARDING_FLOW]:
    'Join organization on business domain trial onboarding flow',
  [CNCButtonName.ACCEPT_INVITATION_ON_BUSINESS_DOMAIN_TRIAL_ONBOARDING_FLOW]:
    'Accept invitation on business domain trial onboarding flow',
  [CNCButtonName.SKIP_ONBOARDING_FLOW_FROM_OPEN_DRIVE]: 'Skip onboarding flow from open drive',
  [CNCButtonName.DISMISS_PROMOTE_CHROME_EXTENSION_MODAL]: 'Dismiss promote chrome extension modal',
  [CNCButtonName.GO_TO_CHROME_EXTENSION_PAGE]: 'Go to chrome extension page',
  [CNCButtonName.KEEP_SUBSCRIPTION]: 'Keep subscription and back to billing page',
  [CNCButtonName.CANCEL_SUBSCRIPTION]: 'Cancel subscription',
  [CNCButtonName.FINISH_CANCEL_SUBSCRIPTION]: 'Finish cancel subscription',
  [CNCButtonName.BACK_TO_HOME]: 'Go back to Home page',
  [CNCButtonName.CANCEL_SUBSCRIPTION_ON_BILLING_DETAIL_PAGE]: 'Cancel subscription on billing detail page',
  [CNCButtonName.PRO_START_FREE_TRIAL]: 'Go to new checkout page from pro plan',
  [CNCButtonName.BUSINESS_START_FREE_TRIAL]: 'Go to new checkout page from business plan',
  [CNCButtonName.VIEW_ALL_PLANS]: 'View all plans',
  [CNCButtonName.NEW_CHECKOUT_PAGE_PERIOD_SWITCH_MONTHLY]: 'Switch period to monthly on new checkout page',
  [CNCButtonName.NEW_CHECKOUT_PAGE_PERIOD_SWITCH_YEARLY]: 'Switch period to yearly on new checkout page',
  [CNCButtonName.NEW_CHECKOUT_PAGE_PLAN_SWITCH_STARTER]: 'Switch plan to starter on new checkout page',
  [CNCButtonName.NEW_CHECKOUT_PAGE_PLAN_SWITCH_PRO_TRIAL]: 'Switch plan to pro trial on new checkout page',
  [CNCButtonName.NEW_CHECKOUT_PAGE_PLAN_SWITCH_PRO]: 'Switch plan to pro on new checkout page',
  [CNCButtonName.NEW_CHECKOUT_PAGE_PLAN_SWITCH_BUSINESS_TRIAL]: 'Switch plan to business trial on new checkout page',
  [CNCButtonName.INVITE_COLLABORATORS]: 'Invite the prefilled google drive shared emails to the Workspace',
  [CNCButtonName.SKIP_INVITE_COLLABORATORS]: 'Skip invitation on google onboarding suggested circles',
  [CNCButtonName.LUMIN_PDF]: 'Explore the Lumin PDF product',
  [CNCButtonName.LUMIN_SIGN]: 'Explore the Lumin Sign product',
  [CNCButtonName.AGREEMENT_GEN]: 'Explore the AgreementGen product',
  [CNCButtonName.DOCUMENTS]: 'Explore the Document List',
  [CNCButtonName.GET_HELP_LUMIN_PDF]: 'Get help on How to use Lumin',
  [CNCButtonName.GET_HELP_LUMIN_SIGN]: 'Get help on How to use Lumin Sign',
  [CNCButtonName.GET_HELP_AGREEMENT_GEN]: 'Get help on How to use AgreementGen',
  [CNCButtonName.GET_HELP_LUMIN_PDF_WORKSPACE_AND_SPACE]: 'Get help on How to use Lumin Workspace and Space',
  [CNCButtonName.START_VIA_SAMPLE_PROMPT]: 'Click a sample prompt button',
  [CNCButtonName.GO_TO_AGREEMENT_GEN]: 'Go to AgreementGen product page',
  [CNCButtonName.UPLOAD_AVATAR_FROM_DEVICE]: 'Upload avatar from device button in prompt to upload logo modal',
};
