sonar.projectKey=nitrolabs_lumin-auth
sonar.organization=nitrolabs
sonar.lang.patterns.ts=**/*.ts,**/*.tsx,**/*.*.ts
sonar.lang.patterns.js=**/*.js,**/*.jsx,**/*.vue
sonar.javascript.lcov.reportPaths=src/coverage/lcov.info
sonar.exclusions=**/*.test.ts
# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=lumin-web-backend-2.0
#sonar.projectVersion=1.0
 
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# sonar.sources=.
 
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
