export enum AutoSyncChangeType {
  ANNOTATION_CHANGE = 'ANNOTATION_CHANGE',
  CONTENT_CHANGE = 'CONTENT_CHANGE',
  RESTORE_ORIGINAL_VERSION = 'RESTORE_ORIGINAL_VERSION',
  EDIT_PDF = 'EDIT_PDF',
  REDACTION = 'REDACTION',
  SYNC_FROM_S3 = 'SYNC_FROM_S3',
  TOGGLE_AUTO_SYNC = 'TOGGLE_AUTO_SYNC',
  OCR = 'OCR',
  OUTLINE = 'OUTLINE',
}

export enum AutoSyncActionType {
  CHECK_SYNC_PERMISSION = 'checkSyncPermission',
  UPDATE_ENABLE_GOOGLE_SYNC = 'updateEnableGoogleSync',
}

export const MAX_ANNOTATION_SYNC_COUNT = 500;
