import { TOOLS_NAME } from 'constants/toolsName';

export const TEMP_EDIT_MODE_ALLOWED_TOOLS = [
  TOOLS_NAME.ERASER,
  TOOLS_NAME.FREEHAND,
  TOOLS_NAME.FREETEXT,
  TOOLS_NAME.SIGNATURE,
  TOOLS_NAME.STAMP,
  'shapeTools',
  'textTools',
  'highlightTools',
  TOOLS_NAME.PASSWORD_PROTECTION,
  TOOLS_NAME.CONTENT_EDIT,
  TOOLS_NAME.MERGE_PAGE,
];

export const TEMP_EDIT_MODE_MANIPULATE_ALLOWS_TOOL = [
  TOOLS_NAME.PASSWORD_PROTECTION,
  TOOLS_NAME.CONTENT_EDIT,
  TOOLS_NAME.MERGE_PAGE,
];
