export enum Operations {
  VIEW_DOCUMENT,
  EDIT_DOCUMENT,
  DELETE_DOCUMENT,
  PRINT_DOCUMENT,
  DOWNLOAD_DOCUMENT,
  SHARE_DOCUMENT,
  SHARE_SETTING,
  REMOVE_PEOPLE_SHARED,
  MOVE_DOCUMENT_INDIVIDUAL_TO_TEAM,
  MOVE_DOCUMENT_TEAM_TO_TEAM
}
