export const CustomRuleOperation = {
  UPLOAD_DOCUMENT_TO_PERSONAL_V2: 'uploadDocumentToPersonalV2',
  UPLOAD_DOCUMENT_TO_ORGANIZATION_V2: 'uploadDocumentToOrganizationV2',
  UPLOAD_DOCUMENT_TO_ORG_TEAM_V2: 'uploadDocumentToOrgTeamV2',
  DUPLICATE_DOCUMENT: 'duplicateDocument',
  DUPLICATE_DOCUMENT_TO_FOLDER: 'duplicateDocumentToFolder',
  REQUEST_ACCESS_DOCUMENT: 'requestAccessDocument',
  CREATE_ORGANIZATION: 'createOrganization',
  UPLOAD_THIRD_PARTY_DOCUMENTS: 'uploadThirdPartyDocuments',
  MOVE_DOCUMENTS_TO_FOLDER: 'moveDocumentsToFolder',
  MOVE_DOCUMENTS: 'moveDocuments',
  DOCUMENT: 'document',
  SHARE_DOCUMENT: 'shareDocument',
  INVITE_MEMBER_TO_ORGANIZATION: 'inviteMemberToOrganization',
  SEND_REQUEST_JOIN_ORG: 'sendRequestJoinOrg',
  GET_ME: 'getMe',
  INIT_GOOGLE_FLOW: 'initGoogleFlow',
  REDIRECT_OPEN_GOOGLE: 'redirectOpenGoogle',
  FIND_USER: 'findUser',
  ORGS_OF_USER: 'orgsOfUser',
  GET_ORGANIZATION_BY_URL: 'getOrganizationByUrl',
  UPDATE_SHARE_SETTING: 'updateShareSetting',
  FIND_USER_BY_ADMIN: 'findUserByAdmin',
  CREATE_ORGANIZATION_BY_ADMIN: 'createOrganizationByAdmin',
  VALIDATE_IP_WHITELIST: 'validateIPWhitelist',
  GET_GOOGLE_CONTACTS: 'getGoogleContacts',
  GET_USER_DETAIL: 'getUserDetail',
};
