import merge from 'lodash/merge';

import { ButtonColor } from 'lumin-components/ButtonMaterial/types/ButtonColor';

import { ModalTypes } from 'constants/lumin-common';
import { ModalPlacement } from 'constants/styles';
import { ModalPriority } from 'constants/styles/Modal';

// eslint-disable-next-line default-param-last
export default (initialState) => (state = initialState, action) => {
  const { type, payload } = action;
  switch (type) {
    case 'OPEN_MODAL':
      return {
        ...state,
        open: true,
        type: payload.type,
        title: payload.title,
        message: payload.message,
        boldMessage: payload.boldMessage,
        onCancel: payload.onCancel,
        confirmButtonTitle: payload.confirmButtonTitle,
        confirmButtonType: payload.confirmButtonType,
        href: payload.href,
        cancelButtonTitle: payload.cancelButtonTitle,
        cancelButtonColor: payload.cancelButtonColor,
        onConfirm: payload.onConfirm,
        isCustomModal: payload.isCustomModal,
        firstButtonTitle: payload.firstButtonTitle,
        secondButtonTitle: payload.secondButtonTitle,
        onFirstButtonClick: payload.onFirstButtonClick,
        onSecondButtonClick: payload.onSecondButtonClick,
        deleteButton: payload.deleteButton,
        color: payload.color,
        isFullWidthButton: payload.isFullWidthButton,
        disableBackdropClick: payload.disableBackdropClick,
        disableEscapeKeyDown: payload.disableEscapeKeyDown,
        customIcon: payload.customIcon,
        className: payload.className,
        isProcessing: payload.isProcessing,
        closeOnConfirm: payload.closeOnConfirm,
        submitId: payload.submitId,
        checkboxMessage: payload.checkboxMessage,
        checkboxWrapperClassname: payload.checkboxWrapperClassname,
        onClose: payload.onClose,
        cancelButtonStyle: payload.cancelButtonStyle,
        confetti: payload.confetti,
        confirmBtnElementName: payload.confirmBtnElementName,
        cancelDataLumin: payload.cancelDataLumin,
        confirmDataLumin: payload.confirmDataLumin,
        hasCloseBtn: payload.hasCloseBtn,
        placement: payload.placement,
        priority: payload.priority,
        closeOnRouteChange: typeof payload.closeOnRouteChange === 'boolean' ? payload.closeOnRouteChange : true,
        /**
         * Props for new layout
         */
        showOnlyInViewer: payload.showOnlyInViewer,
        size: payload.size,
        footerVariant: payload.footerVariant,
        header: payload.header,
        footer: payload.footer,
        content: payload.content,
        icon: payload.icon,
        center: payload.center,
         /**
         * Props for reskin
         */
        useReskinModal: payload.useReskinModal,
        titleCentered: payload.titleCentered,
        cancelButtonProps: payload.cancelButtonProps,
        confirmButtonProps: payload.confirmButtonProps,
        TransitionProps: payload.TransitionProps,
        PaperProps: payload.PaperProps,
        Image: payload.Image,
        key: payload.key,
        hideDefaultButtons: payload.hideDefaultButtons,
      };
    case 'CLOSE_MODAL':
      return {
        ...state,
        open: false,
        type: ModalTypes.WARNING,
        title: 'Default',
        message: 'Default',
        onCancel: () => {},
        confirmButtonTitle: 'Confirm',
        cancelButtonTitle: 'Cancel',
        cancelButtonColor: ButtonColor.GHOST,
        onConfirm: () => {},
        isCustomModal: false,
        firstButtonTitle: 'Default',
        secondButtonTitle: 'Default',
        onFirstButtonClick: () => {},
        onSecondButtonClick: () => {},
        deleteButton: 'Delete',
        isFullWidthButton: false,
        disableBackdropClick: false,
        disableEscapeKeyDown: false,
        className: undefined,
        customIcon: undefined,
        isProcessing: false,
        closeOnConfirm: true,
        submitId: '',
        checkboxMessage: '',
        onClose: undefined,
        cancelButtonStyle: '',
        confetti: false,
        confirmBtnElementName: '',
        cancelDataLumin: {},
        confirmDataLumin: {},
        hasCloseBtn: false,
        placement: ModalPlacement.CENTER,
        priority: ModalPriority.MEDIUM,
        showOnlyInViewer: false,
        closeOnRouteChange: false,
        // NOTE: New layout
        size: 'medium',
        footerVariant: 'variant1',
        header: null,
        footer: null,
        content: null,
        PaperProps: {},
        key: '',
      };
    case 'UPDATE_MODAL_PROPERTIES':
      return merge({ ...state }, {
        open: payload.open,
        type: payload.type,
        title: payload.title,
        message: payload.message,
        boldMessage: payload.boldMessage,
        onCancel: payload.onCancel,
        confirmButtonTitle: payload.confirmButtonTitle,
        confirmButtonType: payload.confirmButtonType,
        href: payload.href,
        cancelButtonTitle: payload.cancelButtonTitle,
        cancelButtonColor: payload.cancelButtonColor,
        onConfirm: payload.onConfirm,
        isCustomModal: payload.isCustomModal,
        firstButtonTitle: payload.firstButtonTitle,
        secondButtonTitle: payload.secondButtonTitle,
        onFirstButtonClick: payload.onFirstButtonClick,
        onSecondButtonClick: payload.onSecondButtonClick,
        deleteButton: payload.deleteButton,
        color: payload.color,
        isFullWidthButton: payload.isFullWidthButton,
        disableBackdropClick: payload.disableBackdropClick,
        disableEscapeKeyDown: payload.disableEscapeKeyDown,
        customIcon: payload.customIcon,
        className: payload.className,
        isProcessing: payload.isProcessing,
        closeOnConfirm: payload.closeOnConfirm,
        checkboxMessage: payload.checkboxMessage,
        onClose: payload.onClose,
        cancelButtonStyle: payload.cancelButtonStyle,
        confetti: payload.confetti,
        hasCloseBtn: payload.hasCloseBtn,
        placement: payload.placement,
        priority: payload.priority,
        size: payload.size,
        footerVariant: payload.footerVariant,
        header: payload.header,
        footer: payload.footer,
        content: payload.content,
        closeOnRouteChange: payload.closeOnRouteChange,
        confirmButtonProps: payload.confirmButtonProps,
        key: payload.key,
      });
    default:
      return state;
  }
};
