export enum TemplateLibraryDiscoverTabs {
  DISCOVER = "Discover",
  WORK = "Work",
  LIFE = "Life",
}

export enum InputMode {
  GUIDED = "guided",
  FREEDOM = "freedom",
}

export enum ModalStep {
  FORM = "form",
  CONTEXT = "context",
  LOADING = "loading",
  RESULTS = "results",
}

export const PROMPT_PLACEHOLDER = "___";
export const MIN_INPUT_WIDTH = 80;
export const PLACEHOLDER_TEXT = "type here...";

export const LOADING_MESSAGES = [
  "Got it! Finding the most relevant templates",
  "On it! Searching for perfect matches",
  "Working on it! Locating the best templates",
  "Understood! Hunting down ideal options",
  "Roger that! Discovering top templates",
  "Noted! Fetching the best fits for you",
  "Got you! Scanning for relevant templates",
  "Copy that! Finding what you need",
  "Alright! Searching the template library",
  "Sure thing! Looking for the right templates",
  "Great! Matching you with perfect templates",
  "Perfect! Retrieving the best options",
  "Awesome! Digging through templates",
  "Nice! Finding templates just for you",
  "Sweet! Locating the ideal matches",
  "Excellent! Browsing relevant templates",
  "Wonderful! Searching for top picks",
  "Fantastic! Finding your perfect templates",
  "Brilliant! Hunting for the best matches",
  "Superb! Discovering ideal templates",
  "Amazing! Looking through our collection",
  "Marvelous! Finding templates that fit",
  "Splendid! Searching for great matches",
  "Terrific! Locating perfect options",
  "Fabulous! Scanning our template library",
  "On the case! Finding relevant templates",
  "Right away! Searching for matches",
  "Coming up! Locating best templates",
  "Hold tight! Finding perfect fits",
  "One moment! Discovering great templates",
  "Just a sec! Searching the library",
  "Hang on! Looking for ideal templates",
  "Bear with me! Finding your matches",
  "Working magic! Locating templates",
  "Searching now! Finding best options",
  "Loading! Discovering relevant templates",
  "Processing! Hunting for matches",
  "Analyzing! Finding perfect templates",
  "Computing! Locating ideal options",
  "Calculating! Searching for fits",
  "Let's go! Finding templates for you",
  "Here we go! Searching the collection",
  "Starting search! Locating templates",
  "Initiating! Finding best matches",
  "Launching! Discovering templates",
  "Firing up! Looking for options",
  "Powering through! Finding templates",
  "Diving in! Searching for matches",
  "Exploring! Locating perfect fits",
  "Investigating! Finding ideal templates",
  "Researching! Discovering options",
  "Scouring! Hunting for templates",
  "Combing through! Finding matches",
  "Filtering! Locating best templates",
  "Sorting! Searching for fits",
  "Curating! Finding perfect options",
  "Selecting! Discovering templates",
  "Picking! Hunting for matches",
  "Choosing! Locating ideal fits",
  "Gathering! Finding relevant templates",
  "Collecting! Searching for options",
  "Assembling! Discovering matches",
  "Compiling! Locating templates",
  "Building! Finding best fits",
  "Crafting! Hunting for templates",
  "Preparing! Searching the library",
  "Getting ready! Finding matches",
  "Setting up! Locating options",
  "Warming up! Discovering templates",
  "Spinning up! Finding ideal fits",
  "Revving up! Searching for templates",
  "Gearing up! Locating matches",
  "Ramping up! Finding options",
  "Kicking off! Hunting for templates",
  "Jumping in! Discovering fits",
  "Digging deep! Finding templates",
  "Going deep! Searching for matches",
  "Looking hard! Locating options",
  "Searching far! Finding templates",
  "Reaching out! Discovering fits",
  "Extending search! Hunting matches",
  "Broadening! Finding ideal templates",
  "Expanding! Locating best options",
  "Widening! Searching for fits",
  "Sweeping! Finding relevant templates",
  "Scanning wide! Discovering matches",
  "Probing! Locating perfect templates",
  "Querying! Finding ideal options",
  "Requesting! Searching for fits",
  "Fetching! Hunting for templates",
  "Retrieving! Discovering matches",
  "Pulling! Finding best templates",
  "Grabbing! Locating options",
  "Snagging! Searching for fits",
  "Catching! Finding perfect templates",
  "Nabbing! Discovering ideal matches",
  "Securing! Hunting for options",
  "Obtaining! Finding templates for you",
  "Acquiring! Locating best fits",
  "Procuring! Searching for matches",
] as const;
