import { TOOLS_NAME, IToolName } from 'constants/toolsName';

export const MEASUREMENT_TOOLS: IToolName[] = [
  TOOLS_NAME.DISTANCE_MEASUREMENT,
  TOOLS_NAME.ARC_MEASUREMENT,
  TOOLS_NAME.PERIMETER_MEASUREMENT,
  TOOLS_NAME.AREA_MEASUREMENT,
  TOOLS_NAME.RECTANGULAR_AREA_MEASUREMENT,
  TOOLS_NAME.ELLIPSE_MEASUREMENT,
  TOOLS_NAME.CALIBRATION_MEASUREMENT,
];
