export const BROADCAST_CHANNEL_KEY = {
  UPDATE_PAYMENT: 'UPDATE_PAYMENT',
  UPDATE_FORM_FIELD_SUGGESTION: 'UPDATE_FORM_FIELD_SUGGESTION',
  TOGGLE_FORM_FIELD_SUGGESTION: 'TOGGLE_FORM_FIELD_SUGGESTION',
  UPDATE_SIGNATURE_LIST: 'UPDATE_SIGNATURE_LIST',
};

export const BROADCAST_ACTION = {
  UPDATE_USER_PAYMENT: 'UPDATE_USER_PAYMENT',
  UPDATE_ORG_PAYMENT: 'UPDATE_ORG_PAYMENT',
};
