export const CUSTOM_EVENT = {
  REFETCH_DOCUMENT: 'refetchDocument',
  CREATE_WIDGET: 'createWidget',
  FINISHED_SAVING_PDF: 'finishedSavingPDF',
  ON_LUMIN_LAYOUT_UPDATED: 'onLuminLayoutUpdated',
  SHOW_LOADING_DOCUMENT_WARN: 'showLoadingDocumentWarn',
  SHOW_PROMPT_INVITE_USERS_BANNER: 'showPromptInviteUsersBanner',
  FINISHED_MANIPULATE: 'finished_manipulate',
  PAGE_CONTENT_UPDATED_EDIT_PDF: 'pageContentUpdated.editPdf',
  OUTLINE_BOOKMARKS_CHANGED: 'outlineBookmarksChanged',
  OUTLINE_CHANGED: 'outlineChanged',
  MANIPULATION_CHANGED: 'manipulationChanged',
  START_SYNC_ON_CONTENT_CHANGE: 'startSyncOnContentChange',
  OPEN_OUTLINE_PANEL: 'openOutlinePanel',
  TOOLBAR_RIGHT_SECTION_LOADED: 'toolbarRightSectionLoaded',
  AUTO_SUBMIT_CHATBOT_FEEDBACK: 'autoSubmitChatbotFeedback',
  CHATBOT_ASSISTANT_MESSAGE_ANIMATED: 'chatbotAssistantMessageAnimated',
  CHATBOT_ASSISTANT_MESSAGE_ANIMATED_END: 'chatbotAssistantMessageAnimatedEnd',
  EXCEED_GROWTHBOOK_LOADING_TIME: 'exceedGrowthbookLoadingTime',
  ON_DRAG_END_THUMBNAIL_PAGE_TOOL: 'onDragEndThumbnailPageTool',
  PAGE_TRACKER_MANIPULATION_CHANGED: 'pageTrackerManipulationChanged',
  PAGE_TRACKER_COLLAB_MANIP_CHANGED: 'pageTrackerCollabManipChanged',
  CHATBOT_AUTO_COMMAND: 'chatbotAutoCommand',
  REFETCH_THUMBNAILS: 'refetchThumbnails',
  DOCUMENT_SYNC_COMPLETED: 'documentSyncCompleted',
  PAYMENT_PURCHASE_SUCCESS: 'paymentPurchaseSuccess',
  TOGGLE_READ_ALOUD_BUTTON: 'toggleReadAloudButton',
  ASSIGN_SIGN_SEATS_SUCCESS: 'assignSignSeatsSuccess',
  REFETCH_ORG_MEMBER: 'refetchOrgMember',
  MINIAPP_TRACKING: 'miniAppTracking',
  SYNC_DOCUMENT: 'syncDocument',
  CHATBOT_AUTO_SET_INPUT_MESSAGE: 'chatbotAutoSetInputMessage',
  MINI_APP: {
    XERO_INTEGRATION: {
      NOTIFY_XERO_APP: 'notifyXeroApp',
      NOTIFY_LUMIN_APP: 'notifyLuminApp',
    },
  },
};
