export const DataElements = {
  REDACTION_OVERLAY: 'redactionOverlay',
  ZOOM_OVERLAY: 'zoomOverlay',
  MENU_OVERLAY: 'menuOverlay',
  COLOR_PALETTE: 'colorPalette',
  OPACITY_SLIDER: 'opacitySlider',
  STROKE_THICKNESS_SLIDER: 'strokeThicknessSlider',
  FONT_SIZE_SLIDER: 'fontSizeSlider',
  STYLE_OPTION: 'styleOption',
  STYLE_POPUP: 'stylePopup',
  SCALE_INPUT_CONTAINER: 'scaleInputContainer',
  PRECISION_INPUT_CONTAINER: 'precisionInputContainer',
  ANNOTATION_POPUP: 'annotationPopup',
  AREA_MEASUREMENT_TOOL_BUTTON: 'areaMeasurementToolButton',
  ARROW_TOOL_BUTTON: 'arrowToolButton',
  BOOKMARKS_PANEL: 'bookmarksPanel',
  BOOKMARKS_PANEL_BUTTON: 'bookmarksPanelButton',
  CLOUD_TOOL_BUTTON: 'cloudToolButton',
  COUNT_MEASUREMENT_TOOL_BUTTON: 'countMeasurementToolButton',
  CROP_TOOL_BUTTON: 'cropToolButton',
  DISTANCE_MEASUREMENT_TOOL_BUTTON: 'distanceMeasurementToolButton',
  ELLIPSE_MEASUREMENT_TOOL_BUTTON: 'ellipseMeasurementToolButton',
  ELLIPSE_TOOL_BUTTON: 'ellipseToolButton',
  ERASER_TOOL_BUTTON: 'eraserToolButton',
  FILE_ATTACHMENT_TOOL_BUTTON: 'fileAttachmentToolButton',
  FILE_PICKER_BUTTON: 'filePickerButton',
  FILE_PICKER_HANDLER: 'filePickerHandler',
  FREE_HANDTOOL_BUTTON: 'freeHandToolButton',
  FREETEXT_TOOL_BUTTON: 'freeTextToolButton',
  HIGHLIGHT_TOOL_BUTTON: 'highlightToolButton',
  FREEHAND_HIGHLIGHT_TOOL_BUTTON: 'freehandHighlightToolButton',
  LAYERS_PANEL: 'layersPanel',
  LAYERS_PANEL_BUTTON: 'layersPanelButton',
  LINE_TOOL_BUTTON: 'lineToolButton',
  LINK_BUTTON: 'linkButton',
  MEASUREMENT_OVERLAY: 'measurementOverlay',
  MEASUREMENT_TOOL_GROUP_BUTTON: 'measurementToolGroupButton',
  PERIMETER_MEASUREMENT_TOOL_BUTTON: 'perimeterMeasurementToolButton',
  POLYGON_TOOL_BUTTON: 'polygonToolButton',
  POLYLINE_TOOL_BUTTON: 'polylineToolButton',
  RECTANGLE_TOOL_BUTTON: 'rectangleToolButton',
  RECTANGULAR_AREA_MEASUREMENT_TOOL_BUTTON: 'rectangularAreaMeasurementToolButton',
  REDACTION_BUTTON: 'redactionButton',
  REDO_BUTTON: 'redoButton',
  RUBBER_STAMP_TOOL_BUTTON: 'rubberStampToolButton',
  SHAPE_TOOL_GROUP_BUTTON: 'shapeToolGroupButton',
  SIGNATURE_TOOL_BUTTON: 'signatureToolButton',
  SEARCH_TOOL_BUTTON: 'searchButton',
  SQUIGGLY_TOOL_BUTTON: 'squigglyToolButton',
  STAMP_TOOL_BUTTON: 'stampToolButton',
  STICKY_TOOL_BUTTON: 'stickyToolButton',
  ADD_OUTLINE_BUTTON: 'addOutlineButton',
  STRIKEOUT_TOOL_BUTTON: 'strikeoutToolButton',
  TEXT_HIGHLIGHT_TOOL_BUTTON: 'textHighlightToolButton',
  TEXT_REDACT_TOOL_BUTTON: 'textRedactToolButton',
  TEXT_SELECT_BUTTON: 'textSelectButton',
  TEXT_SQUIGGLY_TOOL_BUTTON: 'textSquigglyToolButton',
  TEXT_STRIKEOUT_TOOL_BUTTON: 'textStrikeoutToolButton',
  TEXT_TOOL_GROUP_BUTTON: 'textToolGroupButton',
  TEXT_UNDERLINE_TOOL_BUTTON: 'textUnderlineToolButton',
  TOOLS_BUTTON: 'toolsButton',
  UNDERLINE_TOOL_BUTTON: 'underlineToolButton',
  UNDO_BUTTON: 'undoButton',
  COPY_TEXT_BUTTON: 'copyTextButton',
  FILE_INFO_PANEL: 'fileInfoPanel',
  FILE_INFO_PANEL_BUTTON: 'fileInfoPanelButton',
  FORM_BUILD_PANEL: 'rightPanelFormBuild',
  COMMENT_HISTORY_PANEL: 'rightPanelComment',
  RIGHT_PANEL: 'rightPanel',
  SEARCH_OVERLAY: 'searchOverlay',
  SEARCH_PANEL: 'searchPanel',
  LEFT_PANEL: 'leftPanel',
  TEXT_POPUP: 'textPopup',
  CONTEXT_MENU_POPUP: 'contextMenuPopup',
  ROTATE_COUNTER_CLOCKWISE_BUTTON: 'rotateCounterClockwiseButton',
  LINK_MODAL: 'linkModal',
  URL_PANEL: 'URLPanel',
  PAGE_NUMBER_PANEL: 'PageNumberPanel',
  URL_PANEL_BUTTON: 'URLPanelButton',
  PAGE_NUMBER_PANEL_BUTTON: 'PageNumberPanelButton',
  FORM_BUILD_TOOLTIP: 'FormBuildTooltip',
  CONTENT_EDIT_BUTTON: 'contentEditButton',
  NOTES_PANEL: 'notesPanel',
  OUTLINES_PANEL: 'outlinesPanel',
  THUMBNAILS_PANEL: 'thumbnailsPanel',
  RIGHT_TOOL_PANEL: 'rightToolsPanel',
  COMMENT_POPUP: 'commentPopup',
  SIGNATURE_OVERLAY: 'signatureOverlay',
  SIGNATURE_MODAL: 'signatureModal',
  CONTENT_EDIT_PANEL: 'rightContentEditPanel',
  SIGNATURE_SAVED_MODAL: 'signatureSavedModal',
  LOADING_MODAL: 'loadingModal',
  RUBBER_STAMP_BUTTON: 'rubberStampToolButton',
  RUBBER_STAMP_OVERLAY: 'rubberStampOverlay',
  RUBBER_STAMP_MODAL: 'ruberStampModal',
  PAGE_NAVIGATION_OVERLAY: 'pageNavOverlay',
  TOOLS_OVERLAY: 'toolsOverlay',
  TOOL_STYLE_POPUP: 'toolStylePopup',
  VIEW_CONTROLS_OVERLAY: 'viewControlsOverlay',
  USE_COMMENT_MODAL: 'requireUseCommentModal',
  NOTE_POPUP: 'notePopup',
  NOTE_POPUP_EDIT: 'notePopupEdit',
  NOTE_POPUP_DELETE: 'notePopupDelete',
  SIGN_INTEGRATION_BUTTON: 'signIntegrationButton',
  ANNOTATION_CONTENT_OVERLAY: 'annotationContentOverlay',
  VIEWER_LOADING_MODAL: 'viewerLoadingModal',
  SAVE_AS_MODAL: 'saveAsModal',
  SAVE_TO_DRIVE: 'saveToDrive',
  FREE_HAND_TOOL_GROUP_BUTTON: 'freeHandToolGroupButton',
  POPULAR_TAB: 'popularTab',
  ANNOTATE_TAB: 'annotateTab',
  FILL_AND_SIGN_TAB: 'fillAndSignTab',
  EDIT_PDF_TAB: 'editPdfTab',
  SECURITY_TAB: 'securityTab',
  PAGE_TOOLS_TAB: 'pageToolsTab',
  LUMIN_AI_TAB: 'luminAiTab',
  DATE_PICKER_CONTAINER: 'datePickerContainer',
  ANNOTATION_STYLE_POPUP: 'annotationStylePopup',
  FREETEXT_PREVIEW: 'freeTextPreview',
  PASSWORD_MODAL: 'passwordModal',
  TOOLBAR_POPOVER: 'toolbarPopover',
  CHATBOT_FEEDBACK_MODAL: 'chatbotFeedbackModal',
  READ_ALOUD_BUTTON: 'readAloudButton',
  VIEW_CONTROL_BUTTON: 'viewControlButton',
  // TODO add more
} as const;

export const TOOLS_TRIGGER_LOAD_DOCUMENT: Array<string> = [
  DataElements.SEARCH_OVERLAY,
  DataElements.RIGHT_PANEL,
  DataElements.SIGNATURE_OVERLAY,
  DataElements.SEARCH_TOOL_BUTTON,
];

export const TOOLS_TRIGGER_CLOSE_RESTORE_ORIGINAL: Array<string> = [
  DataElements.TOOLS_OVERLAY,
  DataElements.SEARCH_OVERLAY,
  DataElements.TOOL_STYLE_POPUP,
  DataElements.VIEW_CONTROLS_OVERLAY,
];

export type DataElement = typeof DataElements[keyof typeof DataElements];

export default DataElements;
