const ErrorCode = {
  Document: {
    DOCUMENT_NOT_FOUND: 'document_not_found',
    DOCUMENT_HAS_BEEN_DELETED: 'document_has_been_deleted',
    ALREADY_HAVE_PERMISSION: 'already_have_permission',
    NO_DOCUMENT_PERMISSION: 'no_document_permission',
    EXCEEDED_LIMIT_SHARE_DOCUMENT: 'exceeded_limit_share_document',
    OVER_FILE_SIZE_PREMIUM: 'over_file_size_premium',
    OVER_FILE_SIZE_FREE: 'over_file_size_free',
    UPLOAD_DOCUMENT_FAIL: 'upload_document_fail',
    DOCUMENT_FORM_NOT_FOUND: 'document_form_not_found',
    CREATE_DOCUMENT_FAIL: 'create_document_fail',
    REQUESTER_DOCUMENT_NOT_FOUND: 'requester_document_not_found',
    REQUESTER_DOCUMENT_HAS_BEEN_ADDED: 'requester_document_has_been_added',
    REQUEST_ACCESS_DOCUMENT_NOT_FOUND: 'request_access_document_not_found',
    LIMITED_TIME: 'document_has_limited_time',
    DAILY_LIMIT_UPLOAD: 'daily_limit_upload',
    UNKNOWN_ERROR: 'unknown_error',
    ORG_REACHED_DOC_STACK_LIMIT: 'org_reached_doc_stack_limit',
    SYSTEM_FILE_OPEN_ERROR: 'system_file_open_error',
    SYSTEM_FILE_DELETED: 'system_file_deleted',
    REQUEST_ACCESS_NOT_FOUND: 'request_access_not_found',
    INVALID_DOC_REFERENCE: 'invalid_doc_reference',
    DOCUMENT_TEMPLATE_QUOTA_EXCEEDED: 'document_template_quota_exceeded',
    DOMAIN_RESTRICTED_FROM_UPLOADING_DOCUMENT: 'domain_restricted_from_uploading_document',
  },
  Org: {
    TRANSFER_TOKEN_EXPIRED: 'transfer_token_expired',
    TRANSFER_ALREADY_CONFIRM: 'transfer_already_confirm',
    MEMBERSHIP_NOT_FOUND: 'membership_not_found',
    CANNOT_REMOVE_TEAM_ADMIN: 'cannot_remove_team_admin',
    GRANTED_ADMIN_IS_PROCESSING: 'granted_admin_is_processing',
    UPGRADING_INVOICE: 'upgrading_invoice',
    SCHEDULED_DELETE: 'scheduled_delete',
    ORGANIZATION_DOMAIN_EXISTED: 'organization_domain_existed',
    ORGANIZATION_DOMAIN_FORBIDDEN: 'organization_domain_forbidden',
    DOMAIN_IS_NOT_ILLEGAL: 'domain_is_not_illegal',
    USER_NOT_IN_ORGANIZATION: 'user_not_in_organization',
    CANNOT_CHANGE_PERMISSION_OF_ORG_MANAGER: 'cannot_change_permission_of_org_manager',
    ORGANIZATION_NOT_FOUND: 'organization_not_found',
    ORGANIZATION_ADMIN_CANNOT_LEAVE_ORG: 'organization_admin_cannot_leave_org',
    ORGANIZATION_FREE_LIMIT_TEAMS: 'organization_free_limit_teams',
    ALREADY_REQUEST_TO_JOIN_ORG: 'already_request_to_join_org',
    ORGANIZATION_MEMBER_EXCEEDED: 'organization_member_exceeded',
    CANNOT_ADD_MEMBER_TO_ORGANIZATION: 'cannot_add_member_to_organization',
    CANNOT_UPDATE_ORG_PROFILE: 'cannot_update_org_profile',
    ORG_FREE_CANNOT_GET_INSIGHT: 'org_free_cannot_get_insight',
    OGANIZATION_DELETING: 'organization_deleting',
    CANNOT_DELETE_ORGANIZATION: 'cannot_delete_organization',
    ORGANIZATION_HAS_NOT_BEEN_SCHEDULED_TO_DELETE: 'organization_has_not_been_schedule_to_delete',
    INVALID_ASSOCIATE_DOMAIN_POPULAR_DOMAIN: 'invalid_associate_domain_popular_domain',
    INVALID_ASSOCIATE_DOMAIN_NOT_EXIST_MEMBER: 'invalid_associate_domain_not_exist_member',
    INVALID_ASSOCIATE_DOMAIN_USE_BY_ANOTHER_CIRCLE: 'invalid_associate_domain_use_by_another_circle',
    ORG_INVITATION_ALREADY_SENT: 'org_invitation_already_sent',
    REACH_LIMIT_CREATED_ORG: 'reach_limit_created_org',
    ORG_ALREADY_CHARGED: 'org_already_charged',
    LAST_JOINED_ORGANIZATION: 'last_joined_organization',
    CANNOT_INVITE_USER: 'cannot_invite_user',
    INVITE_ALREADY_USED: 'invite_already_used',
    USER_ALREADY_HAS_SEAT: 'user_already_has_seat',
    SEAT_REQUEST_ALREADY_REJECTED: 'seat_request_already_rejected',
    ACTION_BLOCKED_BY_SCIM: 'action_blocked_by_scim',
    SAML_SSO_DOMAIN_ALREADY_CONFIGURED: 'saml_sso_domain_already_configured',
    UPSERT_SAML_SSO_CONNECTION_FAILED: 'upsert_saml_sso_connection_failed',
  },
  OrgTeam: {
    USER_NOT_IN_ORGANIZATION_TEAM: 'user_not_in_organization_team',
    CANNOT_CHANGE_PERMISSION_OF_TEAM_MANAGER: 'cannot_change_permission_of_team_manager',
    CANNOT_REMOVE_TEAM_ADMIN: 'cannot_remove_team_admin',
    REMOVE_TEAM_MEMBER_FAIL: 'remove_team_member_fail',
    ORGANIZATION_TEAM_NOT_FOUND: 'organization_team_not_found',
    ORGANIZATION_TEAM_ADMIN_CANNOT_LEAVE_ORG: 'organization_team_admin_cannot_leave_org',
    TEAM_ADMIN_NOT_FOUND: 'team_admin_not_found',
    CANNOT_ADD_MEMBER_TO_ORGANIZATION_TEAM: 'cannot_add_member_to_organization_team',
    TEAM_ADMIN_CANNOT_LEAVE_TEAM: 'team_admin_cannot_leave_team',
    CANNOT_LEAVE_TEAM: 'cannot_leave_team',
  },
  Common: {
    INVALID_INPUT: 'invalid_input',
    TOKEN_EXPIRED: 'token_expired',
    TOKEN_INVALID: 'token_invalid',
    REQUEST_ALREADY_SENT: 'request_already_sent',
    FILE_NOT_EXISTS: 'file_not_exists',
    INVALID_FILE_TYPE: 'invalid_file_type',
    TOKEN_BLACKLIST: 'token_blacklist',
    NO_PERMISSION: 'no_permission',
    CANNOT_CREATE_SUBSCRIPTION: 'cannot_create_subscription',
    WRONG_DRIVE_ACCOUNT: 'wrong_drive_account',
    INSUFFICIENT_DRIVE_PERMISSION: 'insufficient_drive_permission',
    NOT_FOUND: 'not_found',
    POPUP_FAILED_TO_OPEN: 'popup_failed_to_open',
    POPUP_CLOSED: 'popup_closed',
    RECAPTCHA_V3_VALIDATION_FAILED: 'recaptcha_v3_validation_failed',
    GOOGLE_TOKEN_EXPIRED: 'google_token_expired',
    SESSION_EXPIRED: 'session_expired',
    INVALID_IP_ADDRESS: 'invalid_ip_address',
    RESTRICTED_ACTION: 'restricted_action_by_domain',
    OUTDATED_VERSION: 'outdated_version',
    FORBIDDEN: 'forbidden_resource',
  },
  User: {
    USER_NOT_FOUND: 'user_not_found',
    USER_NOT_VERIFIED: 'user_not_verified',
    USER_ALREADY_VERIFIED: 'user_already_verified',
    EMAIL_IS_BANNED: 'email_is_banned',
    INVALID_EMAIL: 'invalid_email',
    UNAVAILABLE_USER: 'unavailable_user',
    ORGANIZATION_REQUIRE_STRONG_PASSWORD: 'organization_require_strong_password',
    USER_REQUIRE_STRONG_PASSWORD: 'user_require_strong_password',
    RESEND_VERIFY_EMAIL_FAIL: 'resend_verify_email_fail',
    EXCEEDED_LIMIT_RESET_PASSWORD: 'exceeded_limit_reset_password',
    INVALID_PASSWORD_INPUT: 'invalid_password_input',
    NEW_PASSWORD_SAME_OLD_PASSWORD: 'new_password_same_old_password',
    DUPLICATE_RECENT_PASSWORD: 'duplicate_recent_password',
    RESET_PASSWORD_FAIL: 'reset_password_fail',
    RESET_PASSWORD_INVALID_LINK: 'reset_password_invalid_link',
    SIGN_OUT_FAIL: 'sign_out_fail',
    SIGN_IN_FAIL_ATTEMPT_REMAINING: 'sign_in_fail_attempt_remaining',
    CREATE_USER_FAIL: 'create_user_fail',
    CANNOT_DELETE_ACCOUNT_ORG_OR_TEAM_OWNER: 'cannot_delete_account_org_or_team_owner',
    ACCOUNT_BLOCKED: 'account_blocked',
    EMAIL_ALREADY_EXISTS: 'email_already_exists',
    THIRD_PARTY_ACCOUNT: 'third_party_account',
    SAME_OLD_PASSWORD: 'new_password_same_old_password',
    CANNOT_USE_FREE_TRIAL: 'cannot_use_free_trial',
    USER_DELETING: 'user_deleting',
    EXCEEDED_LIMIT_CREATE_SIGNATURE: 'exceeded_limit_create_signature',
  },
  Payment: {
    INVOICE_QUANTITY_NOT_ENOUGH: 'invoice_quantity_not_enough',
    CURRENCY_NOT_MATCHED: 'currency_not_matched',
    API_KEY_EXPIRED: 'api_key_expired',
    CANNOT_CREATE_ANOTHER_SUBSCRIPTION: 'cannot_create_another_subscription',
    CANNOT_USE_SAME_TRIAL: 'cannot_use_same_trial',
    CANNOT_USE_LOWER_TRIAL: 'cannot_use_lower_trial',
    SETUP_INTENT_UNEXPECTED_STATE: 'setup_intent_unexpected_state',
    PAYMENT_INCOMPLETE: 'payment_incomplete',
    INVALID_COUPON_CODE: 'invalid_coupon_code',
    CARD_DECLINED: 'card_declined',
    EXPIRED_CARD: 'expired_card',
    INCORRECT_CVC: 'incorrect_cvc',
  },
  Admin: {
    EMAIL_ALREADY_EXISTS: 'email_already_exists',
    ADMIN_NOT_FOUND: 'admin_not_found',
  },
  Question: {
    QUESTION_NOT_FOUND: 'question_not_found',
    CANNOT_CREATE_QUESTION: 'cannot_create_question',
  },
  GrpcService: {
    PLATFORM_MISSING: 'platform_missing',
    INVALID_CLIENT: 'invalid_client',
    MISSING_CLIENT: 'missing_client',
  },
  Event: {
    INVALID_EVENT_LIMITATION: 'invalid_evente_limitation',
  },
  Noti: {
    READ_NOTIFICATION_FAIL: 'read_notification_fail',
    READ_ALL_NOTIFICATIONS_FAIL: 'read_all_notifications_fail',
    NOTIFICATION_NOT_FOUND: 'notification_not_found',
  },
  Template: {
    TEMPLATE_NOT_FOUND: 'template_not_found',
    DAILY_UPLOAD_TEMPLATE_LIMIT: 'daily_upload_template_limit',
  },
  RequestAccess: {
    REQUEST_ACCESS_ALREADY_SENT: 'request_access_already_sent',
  },
};

const DefaultErrorCode = {
  BAD_REQUEST: 'bad_request',
  UNAUTHORIZED: 'unauthorized',
  NOT_ACCEPTABLE: 'not_acceptable',
  FORBIDDEN: 'forbidden_resource',
  NOT_FOUND: 'not_found',
  CONFLICT: 'conflict',
  INTERNAL_SERVER_ERROR: 'internal_server_error',
  UNPROCESSABLE_ERROR: 'unprocessable_error',
  TOO_MANY_REQUESTS: 'too_many_requests',
};

const TransactionErrorLabel = {
  TRANSIENT_TRANSACTION_ERROR: 'TransientTransactionError',
  UNKNOWN_TRANSACTION_COMMIT_RESULT: 'UnknownTransactionCommitResult',
};

const ErrorIgnoreToast = {
  USER_DELETING: ErrorCode.User.USER_DELETING,
};

const GoogleErrorCode = {
  CANNOT_DOWNLOAD_FILE: 'cannotDownloadFile',
  INSUFFICIENT_FILE_PERMISSIONS: 'insufficientFilePermissions',
};

const ConversionError = {
  TIMEOUT_ERROR: 'TimeoutError',
};

const BuiltInGraphqlErrorCode = {
  GRAPHQL_VALIDATION_FAILED: 'GRAPHQL_VALIDATION_FAILED',
};

export {
  ErrorCode,
  DefaultErrorCode,
  TransactionErrorLabel,
  ErrorIgnoreToast,
  GoogleErrorCode,
  ConversionError,
  BuiltInGraphqlErrorCode,
};
