export enum KEY_ATTRIBUTES_GROWTH_BOOK {
  ID = 'id',
  EMAIL = 'email',
  USER_CREATED_AT_EPOCH_SECONDS = 'userCreatedAtEpochSeconds',
  LOGIN_SERVICE = 'loginService',
  USER_PLAN = 'userPlan',
  USER_PLAN_STATUS = 'userPlanStatus',
  USER_SIGN_PLAN = 'userSignPlan',
  USER_SIGN_PLAN_STATUS = 'userSignPlanStatus',
  IS_BUSINESS_DOMAIN = 'isBusinessDomain',

  ORG_ID = 'orgId',
  CIRCLE_PLAN = 'circlePlan',
  CIRCLE_PLAN_STATUS = 'circlePlanStatus',
  CIRCLE_ROLE = 'circleRole',
  IS_CIRCLE_CANCELED_PLAN = 'isCircleCanceledPlan',
  CAN_START_TRIAL_PLAN = 'canStartTrialPlan',
  CIRCLE_REMAINING_CANCEL_DAYS = 'circleRemainingCancelDays',
  CIRCLE_CANCELED_AT = 'circleCanceledAt',
  ORG_CREATED_AT_EPOCH_SECONDS = 'orgCreatedAtEpochSeconds',

  IS_OPEN_FROM_TEMPLATES = 'isOpenFromTemplates',
  DONT_SHOW_FREE_TRIAL_MODAL_AGAIN_CLICKED = 'dontShowFreeTrialModalAgainClicked',

  THEME_MODE = 'themeMode',

  ANONYMOUS_USER_ID = 'anonymousUserId',
  BROWSER_LANGUAGE = 'browserLanguage',
  HOTJAR_RECORDING_ENABLED = 'hjRecordingEnabled',
}

export interface ATTRIBUTES_GROWTH_BOOK {
  [KEY_ATTRIBUTES_GROWTH_BOOK.ID]: string;
  [KEY_ATTRIBUTES_GROWTH_BOOK.EMAIL]: string;
  [KEY_ATTRIBUTES_GROWTH_BOOK.USER_CREATED_AT_EPOCH_SECONDS]: number;
  [KEY_ATTRIBUTES_GROWTH_BOOK.LOGIN_SERVICE]: string;
  [KEY_ATTRIBUTES_GROWTH_BOOK.USER_PLAN]: string;
  [KEY_ATTRIBUTES_GROWTH_BOOK.USER_PLAN_STATUS]: string;
  [KEY_ATTRIBUTES_GROWTH_BOOK.USER_SIGN_PLAN]: string;
  [KEY_ATTRIBUTES_GROWTH_BOOK.USER_SIGN_PLAN_STATUS]: string;
  [KEY_ATTRIBUTES_GROWTH_BOOK.IS_BUSINESS_DOMAIN]: boolean;

  [KEY_ATTRIBUTES_GROWTH_BOOK.ORG_ID]?: string;
  [KEY_ATTRIBUTES_GROWTH_BOOK.CIRCLE_PLAN]?: string;
  [KEY_ATTRIBUTES_GROWTH_BOOK.CIRCLE_PLAN_STATUS]?: string;
  [KEY_ATTRIBUTES_GROWTH_BOOK.CIRCLE_ROLE]?: string;
  [KEY_ATTRIBUTES_GROWTH_BOOK.IS_CIRCLE_CANCELED_PLAN]?: boolean;
  [KEY_ATTRIBUTES_GROWTH_BOOK.CAN_START_TRIAL_PLAN]?: string;
  [KEY_ATTRIBUTES_GROWTH_BOOK.CIRCLE_REMAINING_CANCEL_DAYS]?: number;
  [KEY_ATTRIBUTES_GROWTH_BOOK.CIRCLE_CANCELED_AT]?: number;
  [KEY_ATTRIBUTES_GROWTH_BOOK.ORG_CREATED_AT_EPOCH_SECONDS]?: number;

  [KEY_ATTRIBUTES_GROWTH_BOOK.IS_OPEN_FROM_TEMPLATES]?: boolean;
  [KEY_ATTRIBUTES_GROWTH_BOOK.DONT_SHOW_FREE_TRIAL_MODAL_AGAIN_CLICKED]?: boolean;

  [KEY_ATTRIBUTES_GROWTH_BOOK.THEME_MODE]?: string;

  [KEY_ATTRIBUTES_GROWTH_BOOK.ANONYMOUS_USER_ID]: string;
  [KEY_ATTRIBUTES_GROWTH_BOOK.BROWSER_LANGUAGE]: string;
  [KEY_ATTRIBUTES_GROWTH_BOOK.HOTJAR_RECORDING_ENABLED]: boolean;
}

export type COMMON_ATTRIBUTES =
  | KEY_ATTRIBUTES_GROWTH_BOOK.ID
  | KEY_ATTRIBUTES_GROWTH_BOOK.EMAIL
  | KEY_ATTRIBUTES_GROWTH_BOOK.USER_CREATED_AT_EPOCH_SECONDS
  | KEY_ATTRIBUTES_GROWTH_BOOK.LOGIN_SERVICE
  | KEY_ATTRIBUTES_GROWTH_BOOK.USER_PLAN
  | KEY_ATTRIBUTES_GROWTH_BOOK.USER_PLAN_STATUS
  | KEY_ATTRIBUTES_GROWTH_BOOK.USER_SIGN_PLAN
  | KEY_ATTRIBUTES_GROWTH_BOOK.USER_SIGN_PLAN_STATUS
  | KEY_ATTRIBUTES_GROWTH_BOOK.IS_BUSINESS_DOMAIN
  | KEY_ATTRIBUTES_GROWTH_BOOK.ANONYMOUS_USER_ID
  | KEY_ATTRIBUTES_GROWTH_BOOK.BROWSER_LANGUAGE
  | KEY_ATTRIBUTES_GROWTH_BOOK.HOTJAR_RECORDING_ENABLED;

export type ATTRIBUTES_IN_VIEWER =
  | KEY_ATTRIBUTES_GROWTH_BOOK.ORG_ID
  | KEY_ATTRIBUTES_GROWTH_BOOK.CIRCLE_PLAN
  | KEY_ATTRIBUTES_GROWTH_BOOK.CIRCLE_PLAN_STATUS
  | KEY_ATTRIBUTES_GROWTH_BOOK.CIRCLE_ROLE
  | KEY_ATTRIBUTES_GROWTH_BOOK.IS_CIRCLE_CANCELED_PLAN
  | KEY_ATTRIBUTES_GROWTH_BOOK.THEME_MODE
  | KEY_ATTRIBUTES_GROWTH_BOOK.CAN_START_TRIAL_PLAN
  | KEY_ATTRIBUTES_GROWTH_BOOK.CIRCLE_REMAINING_CANCEL_DAYS
  | KEY_ATTRIBUTES_GROWTH_BOOK.CIRCLE_CANCELED_AT
  | KEY_ATTRIBUTES_GROWTH_BOOK.IS_OPEN_FROM_TEMPLATES
  | KEY_ATTRIBUTES_GROWTH_BOOK.DONT_SHOW_FREE_TRIAL_MODAL_AGAIN_CLICKED
  | KEY_ATTRIBUTES_GROWTH_BOOK.ORG_CREATED_AT_EPOCH_SECONDS;

export type ATTRIBUTES_IN_ORG_PAGE =
  | KEY_ATTRIBUTES_GROWTH_BOOK.ORG_ID
  | KEY_ATTRIBUTES_GROWTH_BOOK.CIRCLE_PLAN
  | KEY_ATTRIBUTES_GROWTH_BOOK.CIRCLE_PLAN_STATUS
  | KEY_ATTRIBUTES_GROWTH_BOOK.CIRCLE_ROLE
  | KEY_ATTRIBUTES_GROWTH_BOOK.IS_CIRCLE_CANCELED_PLAN
  | KEY_ATTRIBUTES_GROWTH_BOOK.CAN_START_TRIAL_PLAN
  | KEY_ATTRIBUTES_GROWTH_BOOK.CIRCLE_REMAINING_CANCEL_DAYS
  | KEY_ATTRIBUTES_GROWTH_BOOK.CIRCLE_CANCELED_AT
  | KEY_ATTRIBUTES_GROWTH_BOOK.DONT_SHOW_FREE_TRIAL_MODAL_AGAIN_CLICKED;

export const EXCLUDED_ATTRIBUTES_GROWTH_BOOK_FOR_EVENT = [
  KEY_ATTRIBUTES_GROWTH_BOOK.ID,
  KEY_ATTRIBUTES_GROWTH_BOOK.EMAIL,
  KEY_ATTRIBUTES_GROWTH_BOOK.ANONYMOUS_USER_ID,
  KEY_ATTRIBUTES_GROWTH_BOOK.BROWSER_LANGUAGE,
  KEY_ATTRIBUTES_GROWTH_BOOK.ORG_ID,
  KEY_ATTRIBUTES_GROWTH_BOOK.DONT_SHOW_FREE_TRIAL_MODAL_AGAIN_CLICKED,
  KEY_ATTRIBUTES_GROWTH_BOOK.THEME_MODE,
];
