export enum HOTJAR_EVENT {
  LUMIN_SIGN_PAYWALL_VIEWED = 'lumin_sign_paywall_viewed',
  EXTEND_FREE_TRIAL_MODAL_VIEWED = 'extend_free_trial_modal_viewed',
  REACTIVATE_LUMIN_CIRCLE_SUBSCRIPTION_MODAL_VIEWED = 'reactivate_lumin_circle_subscription_modal_viewed',
  MODAL_VIEWED_INVITE_CIRCLE_MEMBER = 'modalViewed_inviteCircleMember',
  ORGANIZATION_ADD_USER = 'organizationAddUser',
  CONNECT_GOOGLE_ACCOUNT = 'connectGoogleAccount',
  BUSINESS_DOMAIN_TRIAL_MODAL_VIEWED = 'business_domain_trial_modal_viewed',
  DISMISS_FREE_TRIAL_SURVEY = 'dismissFreeTrialSurvey',
  DOWNLOAD_MOBILE_MODAL = 'downloadMobileModal',
  DOWNLOAD_DESKTOP_APP_MODAL = 'downloadDesktopAppModal',
  CANCEL_SUBSCRIPTION = 'cancelSubscription',
  CANCEL_SUBSCRIPTION_WITH_FOLLOW_UP_QUESTION = 'cancelSubscriptionWithFollowUpQuestion',
  DOWNLOAD_CHROME_EXTENSION = 'downloadChromeExtension',
  INVITE_SHARED_USERS_MODAL = 'inviteSharedUsersModal',
  START_HOTJAR_RECORDING = 'start_hotjar_recording',
  CLICK_SHARE_IN_SLACK = 'click_shareInSlack',
  ENABLE_INVITE_LINK = 'click_enableInviteLink',
  MODAL_VIEWED_INVITE_TO_GET_FREE_DOC_STACK = 'modal_viewed_inviteToGetFreeDocStack',
  PROMPT_TO_INVITE_MEMBER_TO_WORKSPACE = 'prompt_to_invite_member_to_workspace',
  CHECKOUT_ON_VIEWER = 'checkoutOnViewer',
  WORK_WITH_AGREEMENTS_SURVEY_POPOVER = 'workWithAgreementsSurveyPopover',
  PROMPT_AVATAR_SUGGESTION_MODAL = 'promptAvatarSuggestionModal',
  AGREEMENT_GEN_INPUT_BOX_VIEWED = 'agreementGenInputBoxViewed',
}
