export const SAVE_OPERATION_TYPES = {
  AUTO_SYNC: 'AUTO_SYNC',
  MANUAL_SAVE: 'MANUAL_SAVE',
  PAGE_TOOLS: 'PAGE_TOOLS',
  CONTENT_EDIT: 'CONTENT_EDIT',
  BASE64_CONVERT: 'BASE64_CONVERT',
  REDACTION: 'REDACTION',
  FIELD_CHANGE: 'FIELD_CHANGE',
  ANNOTATION_CHANGE: 'ANNOTATION_CHANGE',
} as const;

export const SAVE_OPERATION_STATUS = {
  SAVING: 'SAVING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  CANCELLED: 'CANCELLED',
  OFFLINE: 'OFFLINE',
} as const;

export const OPERATION_PRIORITIES = {
  [SAVE_OPERATION_TYPES.AUTO_SYNC]: 10,
  [SAVE_OPERATION_TYPES.MANUAL_SAVE]: 8,
  [SAVE_OPERATION_TYPES.CONTENT_EDIT]: 6,
  [SAVE_OPERATION_TYPES.PAGE_TOOLS]: 4,
  [SAVE_OPERATION_TYPES.REDACTION]: 5,
  [SAVE_OPERATION_TYPES.FIELD_CHANGE]: 3,
  [SAVE_OPERATION_TYPES.ANNOTATION_CHANGE]: 3,
  [SAVE_OPERATION_TYPES.BASE64_CONVERT]: 2,
} as const;

export const OPERATION_CLEANUP_DELAY = 3000; // 3 seconds

export const SAVE_OPERATION_ACTIONS = {
  START_SAVE_OPERATION: 'START_SAVE_OPERATION',
  UPDATE_SAVE_OPERATION: 'UPDATE_SAVE_OPERATION',
  COMPLETE_SAVE_OPERATION: 'COMPLETE_SAVE_OPERATION',
  REMOVE_SAVE_OPERATION: 'REMOVE_SAVE_OPERATION',
} as const;
