const SOCKET_EMIT = {
  ANNOTATION_CHANGE: 'annotationChanged',
  CONNECTION: 'connection',
  DISCONNECTION: 'disconnection',
  SEND_MANIPULATION_CHANGED: 'sendManipulationChanged',
  SEND_EMAIL_COMMENT_DOC: 'sendEmailCommentDoc',
  SEND_MENTION_EMAIL: 'sendMentionEmail',
  SEND_EMAIL_REPLY_COMMENT: 'sendEmailReplyComment',
  CLEAR_ANNOTATION_AND_MANIPULATION_OF_DOCUMENT: 'clearAnnotationAndManipulationOfDocument',
  UPDATE_DOCUMENT: 'updateDocument',
  SHARE_PERMISSION: 'sharePermission',
  REMOVE_DOCUMENT: 'removeDocument',
  MERGED_DOCUMENT: 'mergedDocument',
  START_MERGING_DOCUMENT: 'startMergingDocument',
  REMOVE_TEAMMEMBER: 'removeTeamMember',
  CHANGE_SHARE_SETTING: 'changeShareSetting',
  CHANGE_TEAM_ROLE: 'changeTeamRole',
  DELETE_TEAM: 'deleteTeam',
  ADD_NEW_SIGNATURE: 'addNewSignature',
  SEND_DELETED_PAGE: 'sendDeletedPage',
  IDLE_USER: 'idleUser',
  ADD_ACTIVE_USER: 'addActiveUser',
  ADD_USER_TO_ROOM: 'addUserToRoom',
  FORCE_LOGOUT: 'forceLogout',
  USER_LOGIN: 'userLogin',
  DELETE_USER_ACCOUNT: 'deleteUserAccount',
  DELETE_COMMENT_NOTI: 'deleteCommentNoti',
  RESET_PASSWORD: 'resetPassword',
  CREATE_COMMENT_REMOVAL_EVENT: 'createCommentRemovalEvent',
  TOGGLE_AUTO_SYNC: 'toggleAutoSync',
  REQUEST_AUTO_SYNC: 'requestAutoSync',
  RESPONSE_AUTO_SYNC: 'responseAutoSync',
  REMOVE_ORG_MEMBER: 'removeOrgMember',
  JOIN_TO_ORG_ROOM: 'joinToOrgRoom',
  REACTIVE_USER_ACCOUNT: 'reactiveUserAccount',
  UPDATED_TEXT_CONTENT: 'updatedTextContent',
  GET_ANNOTATIONS: 'getAnnotations',
  MANIPULATION: 'manipulation',
  CONVERT_TO_DOCX: 'convertToDocx',
  CONNECTION_INIT: 'connection_init',
  FORM_FIELD_CHANGE: 'formFieldChanged',
  OUTLINES_CHANGE: 'outlinesChanged',
  RESTORE_DOCUMENT: 'restoreDocument',
  CANCEL_SYNC_SESSION: 'cancelSyncSession',
  UPDATE_DOCUMENT_PRINCIPLE_LIST: 'updateDocumentPrincipleList',
} as const;

const SOCKET_ON = {
  ANNOTATION_CHANGE: 'annotationChanged',
  CONNECT: 'connect',
  DISCONNECT: 'disconnect',
  MANIPULATION_CHANGE: 'manipulationChanged',
  NEW_COMER: 'newComer',
  ONLINE_MEMBERS: 'onlineMembers',
  UPDATE_DOCUMENT: 'updateDocument',
  UPDATE_PERMISSION: 'updatePermission',
  REMOVE_DOCUMENT: 'removeDocument',
  MERGED_DOCUMENT: 'mergedDocument',
  START_MERGING_DOCUMENT: 'startMergingDocument',
  FREE_USER_START_MERGING_DOCUMENT: 'freeUserStartMergingDocument',
  REMOVE_TEAMMEMBER: 'removeTeamMember',
  CHANGE_SHARE_SETTING: 'changeShareSetting',
  CHANGE_TEAM_ROLE: 'changeTeamRole',
  REMOVE_FROM_SHARE_LIST: 'removeFromShareList',
  DELETE_TEAM: 'deleteTeam',
  ADD_NEW_SIGNATURE: 'addNewSignature',
  REMOVE_USER_SIGNATURE: 'removeUserSignature',
  DELETED_PAGE_UPDATED: 'deletedPageUpdated',
  IDLE_USER: 'idleUser',
  ADD_ACTIVE_USER: 'addActiveUser',
  FORCE_LOGOUT: 'forceLogout',
  GOOGLE_AUTO_SYNC_STATUS: 'googleSync',
  REMOVE_ORG_MEMBER: 'removeOrgMember',
  UPDATE_TEAM: 'updateTeam',
  DELETE_ORGANIZATION: 'deleteOrganization',
  ORG_PAYMENT_UPDATED: 'orgPaymentUpdated',
  REACTIVE_USER_ACCOUNT: 'reactiveUserAccount',
  UPDATED_TEXT_CONTENT: 'updatedTextContent',
  BULK_UPDATE_DOCUMENT_MEMBER_LIST: 'bulkUpdateDocumentMemberList',
  GET_ANNOTATIONS: 'getAnnotations',
  FINISH_GETTING_ANNOTATIONS: 'finishGettingAnnotations',
  RECONNECT: 'reconnect',
  USER_LOGOUT: 'userLogout',
  DEACTIVATE_ACCOUNT: 'deactivateAccount',
  ENABLE_GOOGLE_SIGN_IN_SUCCESS: 'enableGoogleSignInSuccess',
  INVALID_IP_ADDRESS: 'invalidIpAddress',
  TOKEN_EXPIRED: 'tokenExpired',
  EXCEPTION: 'exception',
  ADD_TO_SHARE_LIST: 'addToShareList',
  AUTHENTICATED: 'authenticated',
  RENEW_AUTHORIZATION_TOKEN: 'renewAuthorizationToken',
  FORM_FIELD_CHANGE: 'formFieldChanged',
  USER_EMAIL_CHANGED: 'userEmailChanged',
  SUMMARIZATION_COMPLETED: 'summarizationCompleted',
  OUTLINES_UPDATE: 'outlinesUpdated',
  FORM_FIELD_DETECTION_COMPLETED: 'formFieldDetectionCompleted',
  SLACK_OAUTH_FLOW_COMPLETED: 'slackOauthFlowCompleted',
  COMPRESS_PDF_COMPLETED: 'compressPdfCompleted',
  PROMPT_TO_JOIN_TRIALING_ORG: 'promptToJoinTrialingOrg',
  SYNC_PROOFING_PROGRESS: 'syncProofingProgress',
  UPDATE_DOCUMENT_ACTION_PERMISSION_SETTINGS: 'updateDocumentActionPermissionSettings',
  NOTIFY_XERO_APP: 'notifyXeroApp',
} as const;

const SOCKET_EMIT_TYPE = {
  UPDATED_PERMISSION: 'UPDATED_PERMISSION',
  DELETE: 'DELETE',
} as const;

export {
  SOCKET_EMIT,
  SOCKET_ON,
  SOCKET_EMIT_TYPE
};
