export const THUMBNAIL_WIDTH_CONTAINER = 250;
export const THUMBNAIL_HEIGHT_CONTAINER = 380;

export const THUMBNAIL_WIDTH = 300;
export const THUMBNAIL_HEIGHT = 450;

export const LEFT_PANEL_EDIT_MODE_WIDTH = 357;
export const HEADER_HEIGHT = 120;
export const TOP_BAR_HEIGHT = 55;

export const THUMBNAIL_RATIO = THUMBNAIL_WIDTH / THUMBNAIL_HEIGHT;
