export const ToolbarRelatedWidth = {
  DEFAULT_RIGHT_PANEL: 368,
  DEFAULT_LEFT_SIDE_BAR: 80,
  DEFAULT_RIGHT_SIDE_BAR: 50,
  MINIMUM_GAP_TOOLBAR: 96,
  COLLAPSED_DIFFERENCE: 54,
  VIEWER_NAVIGATION: 260,
};
