export const TOOLS_NAME = {
  SQUIGGLY: 'AnnotationCreateTextSquiggly',
  HIGHLIGHT: 'AnnotationCreateTextHighlight',
  UNDERLINE: 'AnnotationCreateTextUnderline',
  STRIKEOUT: 'AnnotationCreateTextStrikeout',
  FREETEXT: 'AnnotationCreateFreeText',
  FREEHAND: 'AnnotationCreateFreeHand',
  FREEHAND_HIGHLIGHT: 'AnnotationCreateFreeHandHighlight',
  STICKY: 'AnnotationCreateSticky',
  SIGNATURE: 'AnnotationCreateSignature',
  REDACTION: 'AnnotationCreateRedaction',
  STAMP: 'AnnotationCreateStamp',
  RUBBER_STAMP: 'AnnotationCreateRubberStamp',
  ERASER: 'AnnotationEraserTool',
  EDIT: 'AnnotationEdit',
  DATE_FREE_TEXT: 'AnnotationCreateDateFreeText',
  TEXT_FIELD: 'TextFormFieldCreateTool',
  RADIO: 'RadioButtonFormFieldCreateTool',
  CHECK_BOX: 'CheckBoxFormFieldCreateTool',
  SIGNATURE_FIELD: 'SignatureFormFieldCreateTool',
  CROP_PAGE: 'CropPage',
  CONTENT_EDIT: 'ContentEditTool',
  FORM_BUILDER: 'FormBuilder',
  SPLIT_PAGE: 'SplitPage',
  MERGE_PAGE: 'MergePage',
  DELETE_PAGE: 'DeletePage',
  ROTATE_PAGE: 'RotatePage',
  MOVE_PAGE: 'MovePage',
  INSERT_BLANK_PAGE: 'InsertBlankPage',
  RESTORE_ORIGINAL: 'RestoreOriginal',
  ADD_PARAGRAPH: 'AddParagraphTool',
  OCR: 'OCR',
  ELLIPSE: 'AnnotationCreateEllipse',
  ARROW: 'AnnotationCreateArrow',
  POLYLINE: 'AnnotationCreatePolyline',
  RECTANGLE: 'AnnotationCreateRectangle',
  LINE: 'AnnotationCreateLine',
  POLYGON: 'AnnotationCreatePolygon',
  POLYGON_CLOUD: 'AnnotationCreatePolygonCloud',
  STAR: 'AnnotationCreateStar',
  CROSS: 'AnnotationCreateCross',
  TICK: 'AnnotationCreateTick',
  PAN: 'Pan',
  DOT_STAMP: 'AnnotationCreateDotStamp',
  CROSS_STAMP: 'AnnotationCreateCrossStamp',
  TICK_STAMP: 'AnnotationCreateTickStamp',
  OUTLINE_DESTINATION: 'OutlineDestinationCreateTool',
  PASSWORD_PROTECTION: 'PasswordProtection',
  SYNC_ONE_DRIVE: 'SyncOneDrive',
  FORM_FIELD_DETECTION: 'FormFieldDetection',
  DOCUMENT_SUMMARIZATION: 'DocumentSummarization',
  LIST_BOX_FIELD: 'ListBoxFormFieldCreateTool',
  COMBO_BOX_FIELD: 'ComboBoxFormFieldCreateTool',
  AGREEMENT_GEN: 'AgreementGen',
  MEASUREMENT: 'Measurement',
  DISTANCE_MEASUREMENT: 'AnnotationCreateDistanceMeasurement',
  ARC_MEASUREMENT: 'AnnotationCreateArcMeasurement',
  PERIMETER_MEASUREMENT: 'AnnotationCreatePerimeterMeasurement',
  AREA_MEASUREMENT: 'AnnotationCreateAreaMeasurement',
  ELLIPSE_MEASUREMENT: 'AnnotationCreateEllipseMeasurement',
  RECTANGULAR_AREA_MEASUREMENT: 'AnnotationCreateRectangularAreaMeasurement',
  CALIBRATION_MEASUREMENT: 'AnnotationCreateCalibrationMeasurement',
  COMPRESS_PDF: 'CompressPdf',
  INSERT_OUTLINES: 'InsertOutlines',
  CHATBOT: 'ChatBot',
} as const;

export const MEASUREMENT_TOOLS = [
  TOOLS_NAME.DISTANCE_MEASUREMENT,
  TOOLS_NAME.ARC_MEASUREMENT,
  TOOLS_NAME.PERIMETER_MEASUREMENT,
  TOOLS_NAME.AREA_MEASUREMENT,
  TOOLS_NAME.ELLIPSE_MEASUREMENT,
  TOOLS_NAME.RECTANGULAR_AREA_MEASUREMENT,
  TOOLS_NAME.CALIBRATION_MEASUREMENT,
] as const;

export type IToolName = typeof TOOLS_NAME[keyof typeof TOOLS_NAME];

export const SYNC_TOOLS = [TOOLS_NAME.SYNC_ONE_DRIVE];

export const PREMIUM_FEATURE_NAME = {
  [TOOLS_NAME.SQUIGGLY]: 'textTool',
  [TOOLS_NAME.HIGHLIGHT]: 'textTool',
  [TOOLS_NAME.UNDERLINE]: 'textTool',
  [TOOLS_NAME.STRIKEOUT]: 'textTool',
  [TOOLS_NAME.FREETEXT]: 'freeText',
  [TOOLS_NAME.FREEHAND]: 'freeHand',
  [TOOLS_NAME.STICKY]: 'comment',
  [TOOLS_NAME.SIGNATURE]: 'stamp',
  [TOOLS_NAME.RUBBER_STAMP]: 'rubberStamp',
  [TOOLS_NAME.REDACTION]: 'redaction',
  [TOOLS_NAME.STAMP]: 'stamp',
  [TOOLS_NAME.ERASER]: 'eraser',
  [TOOLS_NAME.DATE_FREE_TEXT]: 'freeText',
  [TOOLS_NAME.TEXT_FIELD]: 'formBuilder',
  [TOOLS_NAME.RADIO]: 'formBuilder',
  [TOOLS_NAME.CHECK_BOX]: 'formBuilder',
  [TOOLS_NAME.SIGNATURE_FIELD]: 'formBuilder',
  [TOOLS_NAME.CONTENT_EDIT]: 'editPDFContent',
  [TOOLS_NAME.FORM_BUILDER]: 'formBuilder',
  [TOOLS_NAME.SPLIT_PAGE]: 'splitPage',
  [TOOLS_NAME.CROP_PAGE]: 'cropPage',
  [TOOLS_NAME.MOVE_PAGE]: 'movePage',
  [TOOLS_NAME.ROTATE_PAGE]: 'rotatePage',
  [TOOLS_NAME.DELETE_PAGE]: 'deletePage',
  [TOOLS_NAME.INSERT_BLANK_PAGE]: 'insertPage',
  [TOOLS_NAME.RESTORE_ORIGINAL]: 'restoreOriginal',
  [TOOLS_NAME.OCR]: 'ocr',
  [TOOLS_NAME.DOT_STAMP]: 'dotStamp',
  [TOOLS_NAME.CROSS_STAMP]: 'crossStamp',
  [TOOLS_NAME.TICK_STAMP]: 'tickStamp',
  [TOOLS_NAME.PASSWORD_PROTECTION]: 'passwordProtection',
  [TOOLS_NAME.SYNC_ONE_DRIVE]: 'oneDrive',
} as const;

// these values are the key in translation to get shortcut
export const TOOLS_WITH_SHORT_CUT = [
  'arrow',
  'callout',
  'copy',
  'delete',
  'ellipse',
  'eraser',
  'freehand',
  'freetext',
  'highlight',
  'line',
  'pan',
  'rectangle',
  'rotateClockwise',
  'rotateCounterClockwise',
  'select',
  'signature',
  'squiggly',
  'stamp',
  'stickyNote',
  'strikeout',
  'underline',
  'zoomIn',
  'zoomOut',
  'richText',
];

export const TOOLS_TRIGGER_LOAD_DOCUMENT = [
  TOOLS_NAME.HIGHLIGHT,
  TOOLS_NAME.FREEHAND_HIGHLIGHT,
  TOOLS_NAME.UNDERLINE,
  TOOLS_NAME.SQUIGGLY,
  TOOLS_NAME.STRIKEOUT,
  TOOLS_NAME.FREETEXT,
  TOOLS_NAME.FREEHAND,

  TOOLS_NAME.RECTANGLE,
  TOOLS_NAME.ELLIPSE,
  TOOLS_NAME.LINE,
  TOOLS_NAME.ARROW,
  TOOLS_NAME.POLYLINE,
  TOOLS_NAME.POLYGON,
  TOOLS_NAME.POLYGON_CLOUD,
  TOOLS_NAME.STAR,
  TOOLS_NAME.CROSS,
  TOOLS_NAME.TICK,

  TOOLS_NAME.ERASER,
  TOOLS_NAME.STAMP,
  TOOLS_NAME.REDACTION,
  TOOLS_NAME.DATE_FREE_TEXT,
  TOOLS_NAME.STICKY,
];

/**
 * @deprecated use name export instead
 */
export default TOOLS_NAME;
