import envManager from '../../settings/PublicEnv';

const BASEURL = envManager.getEnv('BASEURL');
const GRAPHQL_API = envManager.getEnv('GRAPHQL_API');
const AXIOS_BASEURL = envManager.getEnv('AXIOS_BASEURL');
const DROPBOX_REDIRECT_URL = envManager.getEnv('DROPBOX_REDIRECT_URL');
const SOCKET_IO_URL = envManager.getEnv('SOCKET_IO_URL');
const GRAPHQL_WEBSOCKET_API = envManager.getEnv('GRAPHQL_WEBSOCKET_API');
const DROPBOX_AUTHORIZE_API = envManager.getEnv('DROPBOX_AUTHORIZE_API');
const DROPBOX_AUTHORIZE_DOWNLOAD_API = envManager.getEnv('DROPBOX_AUTHORIZE_DOWNLOAD_API');
const STATIC_PAGE_URL = envManager.getEnv('STATIC_PAGE_URL');
const ENV = envManager.getEnv('ENV');
const PUBLIC_RECAPTCHA_SITE_KEY = envManager.getEnv('PUBLIC_RECAPTCHA_SITE_KEY');
const HUBSPOT_ID = envManager.getEnv('HUBSPOT_ID');
const GA4_ID = envManager.getEnv('GA4_ID');
const BANANA_SIGN_WEB_URL = envManager.getEnv('BANANA_SIGN_WEB_URL');
const UNIVERSAL_LINK = envManager.getEnv('UNIVERSAL_LINK');
const PUBLIC_RECAPTCHA_V3_SITE_KEY = envManager.getEnv('PUBLIC_RECAPTCHA_V3_SITE_KEY');
const APPLE_CLIENT_ID = envManager.getEnv('APPLE_CLIENT_ID');
const TAG_MANAGER_ID = envManager.getEnv('TAG_MANAGER_ID');
const ENABLE_NEW_AUTHEN_DATE = envManager.getEnv('ENABLE_NEW_AUTHEN_DATE');
const AUTH_SERVICE_URL = envManager.getEnv('AUTH_SERVICE_URL');
const KRATOS_PUBLIC_API = envManager.getEnv('KRATOS_PUBLIC_API');
const SIGN_APP_URL = envManager.getEnv('SIGN_APP_URL');
const CACHE_DOCUMENT_EXPIRATION = parseInt(envManager.getEnv('CACHE_DOCUMENT_EXPIRATION'));
const HIDE_TEMPLATE_WIDGET_DATE = envManager.getEnv('HIDE_TEMPLATE_WIDGET_DATE');
const HIDE_TEMPLATE_BANNER_DATE = envManager.getEnv('HIDE_TEMPLATE_BANNER_DATE');
const CORE_VERSION = envManager.getEnv('CORE_VERSION');
const GROWTHBOOK_CLIENT_KEY = envManager.getEnv('GROWTHBOOK_CLIENT_KEY');
const PROMPT_INVITE_GOOGLE_USERS_DURATION = envManager.getEnv('PROMPT_INVITE_GOOGLE_USERS_DURATION');
const DOCUMENT_TIME_LIMITED = envManager.getEnv('DOCUMENT_TIME_LIMITED');
const SIGN_BACKEND_URL = envManager.getEnv('SIGN_BACKEND_URL');
const ONE_DRIVE_BASE_URL = envManager.getEnv('ONE_DRIVE_BASE_URL');
const MICROSOFT_AUTHORIZATION_URL = envManager.getEnv('MICROSOFT_AUTHORIZATION_URL');
const MICROSOFT_CLIENT_ID = envManager.getEnv('MICROSOFT_CLIENT_ID');
const MICROSOFT_ADD_INS_CLIENT_ID = envManager.getEnv('MICROSOFT_ADD_INS_CLIENT_ID');
const MICROSOFT_FILE_PICKER_CLIENT_ID = envManager.getEnv('MICROSOFT_FILE_PICKER_CLIENT_ID');
const CANNY_FEEDBACK_REDIRECT_URL = envManager.getEnv('CANNY_FEEDBACK_REDIRECT_URL');
const CANNY_AUTHOR_ID = envManager.getEnv('CANNY_AUTHOR_ID');
const CANNY_LAYOUT_FEEDBACK_BOARD_ID = envManager.getEnv('CANNY_LAYOUT_FEEDBACK_BOARD_ID');
const CANNY_LAYOUT_FEEDBACK_TAG_ID = envManager.getEnv('CANNY_LAYOUT_FEEDBACK_TAG_ID');
const BACK_UP_DOCUMENT_INTERVAL = envManager.getEnv('BACK_UP_DOCUMENT_INTERVAL');
const CONTINUOUS_EDITS_BACKUP_TIMEOUT = envManager.getEnv('CONTINUOUS_EDITS_BACKUP_TIMEOUT');
const AUTO_DETECT_QUEUE_THROTTLE_TIME = envManager.getEnv('AUTO_DETECT_QUEUE_THROTTLE_TIME');
const CHROME_EXTENSION_URL = envManager.getEnv('CHROME_EXTENSION_URL');
const INSTALL_APP_ON_MOBILE_DOC_LIST_URL = envManager.getEnv('INSTALL_APP_ON_MOBILE_DOC_LIST_URL');
const MOBILE_DEEP_LINK_URL = envManager.getEnv('MOBILE_DEEP_LINK_URL');
const TEMPLATES_API = envManager.getEnv('TEMPLATES_API');
const EDITOR_BACKEND_BASE_URL = envManager.getEnv('EDITOR_BACKEND_BASE_URL');
const AGREEMENT_GEN_APP_URL = envManager.getEnv('AGREEMENT_GEN_APP_URL');
const AGREEMENT_GEN_API_URL = envManager.getEnv('AGREEMENT_GEN_API_URL');
const INTRODUCING_AGREEMENT_GEN_URL = envManager.getEnv('INTRODUCING_AGREEMENT_GEN_URL');
const MAX_CAPACITY_FOR_PRIVATE_SHARING = envManager.getEnv('MAX_CAPACITY_FOR_PRIVATE_SHARING');
const PRICING_URL = envManager.getEnv('PRICING_URL');
const ISSUE_BANK_CANNOT_START_TRIAL = envManager.getEnv('ISSUE_BANK_CANNOT_START_TRIAL');
const STRIPE_NZ_ACCOUNT_ID = envManager.getEnv('STRIPE_NZ_ACCOUNT_ID');
const STRIPE_US_ACCOUNT_ID = envManager.getEnv('STRIPE_US_ACCOUNT_ID');
const FORCE_SYNC_ANNOTATIONS_THRESHOLD = envManager.getEnv('FORCE_SYNC_ANNOTATIONS_THRESHOLD');
const WEB_CHAT_BOT_API_URL = envManager.getEnv('WEB_CHAT_BOT_API_URL');
const SIGN_URL = envManager.getEnv('SIGN_URL');
const DEVELOPER_API_BASEURL = envManager.getEnv('DEVELOPER_API_BASEURL');
const INSTALL_APP_ON_MOBILE_HOMEPAGE_URL = envManager.getEnv('INSTALL_APP_ON_MOBILE_HOMEPAGE_URL');
const OUTLINES_SAVE_THRESHOLD = envManager.getEnv('OUTLINES_SAVE_THRESHOLD');
const PUBLIC_KEY_VERIFY_SIGNED_RESPONSE = envManager.getEnv('PUBLIC_KEY_VERIFY_SIGNED_RESPONSE');
const GOOGLE_PICKER_CLIENTID = envManager.getEnv('GOOGLE_PICKER_CLIENTID');
const PROMOTE_TEMPLATES_EXPIRY = envManager.getEnv('PROMOTE_TEMPLATES_EXPIRY');
const LOGO_DEV_API_KEY = envManager.getEnv('LOGO_DEV_API_KEY');

export {
  BASEURL,
  GRAPHQL_API,
  AXIOS_BASEURL,
  DROPBOX_REDIRECT_URL,
  SOCKET_IO_URL,
  GRAPHQL_WEBSOCKET_API,
  DROPBOX_AUTHORIZE_API,
  DROPBOX_AUTHORIZE_DOWNLOAD_API,
  STATIC_PAGE_URL,
  ENV,
  PUBLIC_RECAPTCHA_SITE_KEY,
  HUBSPOT_ID,
  GA4_ID,
  BANANA_SIGN_WEB_URL,
  UNIVERSAL_LINK,
  PUBLIC_RECAPTCHA_V3_SITE_KEY,
  APPLE_CLIENT_ID,
  TAG_MANAGER_ID,
  ENABLE_NEW_AUTHEN_DATE,
  AUTH_SERVICE_URL,
  KRATOS_PUBLIC_API,
  SIGN_APP_URL,
  CACHE_DOCUMENT_EXPIRATION,
  HIDE_TEMPLATE_WIDGET_DATE,
  HIDE_TEMPLATE_BANNER_DATE,
  CORE_VERSION,
  GROWTHBOOK_CLIENT_KEY,
  PROMPT_INVITE_GOOGLE_USERS_DURATION,
  DOCUMENT_TIME_LIMITED,
  SIGN_BACKEND_URL,
  ONE_DRIVE_BASE_URL,
  MICROSOFT_AUTHORIZATION_URL,
  MICROSOFT_CLIENT_ID,
  MICROSOFT_ADD_INS_CLIENT_ID,
  MICROSOFT_FILE_PICKER_CLIENT_ID,
  CANNY_FEEDBACK_REDIRECT_URL,
  CANNY_AUTHOR_ID,
  CANNY_LAYOUT_FEEDBACK_BOARD_ID,
  CANNY_LAYOUT_FEEDBACK_TAG_ID,
  BACK_UP_DOCUMENT_INTERVAL,
  CONTINUOUS_EDITS_BACKUP_TIMEOUT,
  AUTO_DETECT_QUEUE_THROTTLE_TIME,
  CHROME_EXTENSION_URL,
  INSTALL_APP_ON_MOBILE_DOC_LIST_URL,
  MOBILE_DEEP_LINK_URL,
  TEMPLATES_API,
  EDITOR_BACKEND_BASE_URL,
  AGREEMENT_GEN_APP_URL,
  AGREEMENT_GEN_API_URL,
  INTRODUCING_AGREEMENT_GEN_URL,
  MAX_CAPACITY_FOR_PRIVATE_SHARING,
  PRICING_URL,
  ISSUE_BANK_CANNOT_START_TRIAL,
  STRIPE_NZ_ACCOUNT_ID,
  STRIPE_US_ACCOUNT_ID,
  FORCE_SYNC_ANNOTATIONS_THRESHOLD,
  WEB_CHAT_BOT_API_URL,
  SIGN_URL,
  DEVELOPER_API_BASEURL,
  INSTALL_APP_ON_MOBILE_HOMEPAGE_URL,
  OUTLINES_SAVE_THRESHOLD,
  PUBLIC_KEY_VERIFY_SIGNED_RESPONSE,
  GOOGLE_PICKER_CLIENTID,
  PROMOTE_TEMPLATES_EXPIRY,
  LOGO_DEV_API_KEY,
};
