const ErrorCode = {
  Document: {
    INVALID_PAYMENT_PLAN: 'invalid_payment_plan',
    DOCUMENT_NOT_FOUND: 'document_not_found',
    DOCUMENT_HAS_BEEN_DELETED: 'document_has_been_deleted',
    ALREADY_HAVE_PERMISSION: 'already_have_permission',
    NO_DOCUMENT_PERMISSION: 'no_document_permission',
    OVER_FILE_SIZE_PREMIUM: 'over_file_size_premium',
    OVER_FILE_SIZE_FREE: 'over_file_size_free',
    UPLOAD_DOCUMENT_FAIL: 'upload_document_fail',
    DOCUMENT_FORM_NOT_FOUND: 'document_form_not_found',
    CREATE_DOCUMENT_FAIL: 'create_document_fail',
    REQUESTER_DOCUMENT_NOT_FOUND: 'requester_document_not_found',
    REQUESTER_DOCUMENT_HAS_BEEN_ADDED: 'requester_document_has_been_added',
    REQUEST_ACCESS_DOCUMENT_NOT_FOUND: 'request_access_document_not_found',
    DAILY_LIMIT_UPLOAD: 'daily_limit_upload',
    LOST_ANNOTATION_OF_USER: 'lost_annotation_of_user',
    REACHED_DOCUMENT_STACK: 'reached_document_quota',
    ORG_REACHED_DOC_STACK_LIMIT: 'org_reached_doc_stack_limit',
    BACKUP_DOCUMENT_FAILED: 'backup_document_failed',
    CAN_NOT_UPDATE_SETTING: 'can_not_update_setting',
    TEMPORARY_FILE_MISSING: 'temporary_file_missing',
    OUTLINE_EXISTED: 'outline_existed',
    OUTLINE_NOT_FOUND: 'outline_not_found',
    PATH_ID_MISSING: 'path_id_missing',
    DOCUMENT_ID_MISSING: 'document_id_missing',
    NAME_OUT_OF_RANGE: 'name_out_of_range',
    OUTLINE_NOT_VALID: 'outline_not_valid',
    DOES_NOT_HAVE_OUTLINES: 'does_not_have_outlines',
    DOCUMENT_TEMPLATE_QUOTA_EXCEEDED: 'document_template_quota_exceeded',
    DOCUMENT_TEMPLATE_NOT_FOUND: 'document_not_found',
    DOMAIN_RESTRICTED_FROM_UPLOADING_DOCUMENT: 'domain_restricted_from_uploading_document',
  },
  Template: {
    OVER_FILE_SIZE_LIMIT: 'over_file_size_limit',
    TEMPLATE_NOT_FOUND: 'template_not_found',
    DAILY_UPLOAD_TEMPLATE_LIMIT: 'daily_upload_template_limit',
    URL_TAKEN: 'url_taken',
  },
  Org: {
    TRANSFER_TOKEN_EXPIRED: 'transfer_token_expired',
    TRANSFER_ALREADY_CONFIRM: 'transfer_already_confirm',
    MEMBERSHIP_NOT_FOUND: 'membership_not_found',
    CANNOT_REMOVE_TEAM_ADMIN: 'cannot_remove_team_admin',
    GRANTED_ADMIN_IS_PROCESSING: 'granted_admin_is_processing',
    UPGRADING_INVOICE: 'upgrading_invoice',
    SCHEDULED_DELETE: 'scheduled_delete',
    ORGANIZATION_DOMAIN_EXISTED: 'organization_domain_existed',
    ORGANIZATION_DOMAIN_FORBIDDEN: 'organization_domain_forbidden',
    DOMAIN_IS_NOT_ILLEGAL: 'domain_is_not_illegal',
    USER_NOT_IN_ORGANIZATION: 'user_not_in_organization',
    CANNOT_CHANGE_PERMISSION_OF_ORG_MANAGER: 'cannot_change_permission_of_org_manager',
    ORGANIZATION_NOT_FOUND: 'organization_not_found',
    ORGANIZATION_ADMIN_CANNOT_LEAVE_ORG: 'organization_admin_cannot_leave_org',
    ORGANIZATION_FREE_LIMIT_TEAMS: 'organization_free_limit_teams',
    ORGANIZATION_PREMIUM_LIMIT_TEAMS: 'organization_premium_limit_teams',
    ALREADY_REQUEST_TO_JOIN_ORG: 'already_request_to_join_org',
    ALREADY_IN_THIS_ORG: 'already_in_this_org',
    ORGANIZATION_MEMBER_EXCEEDED: 'organization_member_exceeded',
    CANNOT_ADD_MEMBER_TO_ORGANIZATION: 'cannot_add_member_to_organization',
    CANNOT_UPDATE_ORG_PROFILE: 'cannot_update_org_profile',
    ORG_FREE_CANNOT_GET_INSIGHT: 'org_free_cannot_get_insight',
    OGANIZATION_DELETING: 'organization_deleting',
    CANNOT_DELETE_ORGANIZATION: 'cannot_delete_organization',
    ORGANIZATION_HAS_NOT_BEEN_SCHEDULED_TO_DELETE: 'organization_has_not_been_schedule_to_delete',
    LIMIT_ASSOCIATE_DOMAIN: 'limit_associate_domain',
    INVALID_ASSOCIATE_DOMAIN_POPULAR_DOMAIN: 'invalid_associate_domain_popular_domain',
    INVALID_ASSOCIATE_DOMAIN_NOT_EXIST_MEMBER: 'invalid_associate_domain_not_exist_member',
    INVALID_ASSOCIATE_DOMAIN_USE_BY_ANOTHER_CIRCLE: 'invalid_associate_domain_use_by_another_circle',
    UPGRADE_PLAN_TO_USE_AUTO_APPROVE: 'upgrade_plan_to_use_auto_approve',
    UPGRADE_MORE_SLOT_TO_USE_AUTO_APPROVE: 'upgrade_more_slot_to_use_auto_approve',
    ORG_INVITATION_ALREADY_SENT: 'org_invitation_already_sent',
    PROHIBIT_DEFAULT_ORGANIZATION_ACTION: 'prohibit_default_organization_action',
    REACH_LIMIT_CREATED_ORG: 'reach_limit_created_org',
    ORG_ALREADY_CHARGED: 'org_already_charged',
    LAST_JOINED_ORGANIZATION: 'last_joined_organization',
    CANNOT_UPDATE_INVITE_USERS_SETTING: 'cannot_update_invite_users_setting',
    CANNOT_INVITE_USER: 'cannot_invite_user',
    CANNOT_UPDATE_VISIBILITY_SETTING: 'cannot_update_visibility_setting',
    CANNOT_UPDATE_ORG_SETTING_BASED_ON_PLAN: 'cannot_update_org_setting_based_on_plan',
    INVITE_ALREADY_USED: 'invite_already_used',
    OWNER_NOT_FOUND: 'owner_not_found',
    SAML_SSO_DOMAIN_ALREADY_CONFIGURED: 'saml_sso_domain_already_configured',
    SAML_SSO_DOMAIN_NOT_ASSOCIATED: 'saml_sso_domain_not_associated',
    SCIM_SSO_PROVISION_ALREADY_ENABLED: 'scim_sso_provision_already_enabled',
    SAML_SSO_CONFIGURATION_NOT_FOUND: 'saml_sso_configuration_not_found',
    ACTION_BLOCKED_BY_SCIM: 'action_blocked_by_scim',
    UPSERT_SAML_SSO_CONNECTION_FAILED: 'upsert_saml_sso_connection_failed',
    SAML_SCIM_NOT_AVAILABLE: 'saml_scim_not_available',
  },
  OrgTeam: {
    USER_NOT_IN_ORGANIZATION_TEAM: 'user_not_in_organization_team',
    CANNOT_CHANGE_PERMISSION_OF_TEAM_MANAGER: 'cannot_change_permission_of_team_manager',
    CANNOT_REMOVE_TEAM_ADMIN: 'cannot_remove_team_admin',
    REMOVE_TEAM_MEMBER_FAIL: 'remove_team_member_fail',
    ORGANIZATION_TEAM_NOT_FOUND: 'organization_team_not_found',
    ORGANIZATION_TEAM_ADMIN_CANNOT_LEAVE_ORG: 'organization_team_admin_cannot_leave_org',
    TEAM_ADMIN_NOT_FOUND: 'team_admin_not_found',
    CANNOT_ADD_MEMBER_TO_ORGANIZATION_TEAM: 'cannot_add_member_to_organization_team',
    TEAM_ADMIN_CANNOT_LEAVE_TEAM: 'team_admin_cannot_leave_team',
    CANNOT_LEAVE_TEAM: 'cannot_leave_team',
    MEMBERSHIP_NOT_FOUND: 'team_membership_not_found',
  },
  Common: {
    INVALID_INPUT: 'invalid_input',
    TOKEN_EXPIRED: 'token_expired',
    TOKEN_INVALID: 'token_invalid',
    REQUEST_ALREADY_SENT: 'request_already_sent',
    FILE_NOT_EXISTS: 'file_not_exists',
    INVALID_FILE_TYPE: 'invalid_file_type',
    TOKEN_BLACKLIST: 'token_blacklist',
    NO_PERMISSION: 'no_permission',
    CANNOT_CREATE_SUBSCRIPTION: 'cannot_create_subscription',
    THIRD_PARTY_ERROR: 'third_party_error',
    NOT_FOUND: 'not_found',
    RECAPTCHA_V3_VALIDATION_FAILED: 'recaptcha_v3_validation_failed',
    GOOGLE_TOKEN_EXPIRED: 'google_token_expired',
    EXCEED_THUMBNAIL_SIZE: 'exceed_thumbnail_size',
    RECAPTCHA_V2_VALIDATION_FAILED: 'recaptcha_v2_validation_failed',
    SESSION_EXPIRED: 'session_expired',
    INVALID_IP_ADDRESS: 'invalid_ip_address',
    INVALID_REQUEST_HEADER: 'invalid_request_header',
    OUTDATED_VERSION: 'outdated_version',
    RECAPTCHA_ENTERPRISE_CLIENT_NOT_INITIALIZED: 'recaptcha_enterprise_client_not_initialized',
  },
  User: {
    USER_NOT_FOUND: 'user_not_found',
    USER_NOT_VERIFIED: 'user_not_verified',
    USER_ALREADY_VERIFIED: 'user_already_verified',
    EMAIL_IS_BANNED: 'email_is_banned',
    INVALID_EMAIL: 'invalid_email',
    UNAVAILABLE_USER: 'unavailable_user',
    ORGANIZATION_REQUIRE_STRONG_PASSWORD: 'organization_require_strong_password',
    USER_REQUIRE_STRONG_PASSWORD: 'user_require_strong_password',
    RESEND_VERIFY_EMAIL_FAIL: 'resend_verify_email_fail',
    EXCEEDED_LIMIT_RESET_PASSWORD: 'exceeded_limit_reset_password',
    INVALID_PASSWORD_INPUT: 'invalid_password_input',
    NEW_PASSWORD_SAME_OLD_PASSWORD: 'new_password_same_old_password',
    DUPLICATE_RECENT_PASSWORD: 'duplicate_recent_password',
    RESET_PASSWORD_FAIL: 'reset_password_fail',
    RESET_PASSWORD_INVALID_LINK: 'reset_password_invalid_link',
    SIGN_OUT_FAIL: 'sign_out_fail',
    SIGN_IN_FAIL_ATTEMPT_REMAINING: 'sign_in_fail_attempt_remaining',
    CREATE_USER_FAIL: 'create_user_fail',
    CANNOT_DELETE_ACCOUNT_ORG_OR_TEAM_OWNER: 'cannot_delete_account_org_or_team_owner',
    ACCOUNT_BLOCKED: 'account_blocked',
    EMAIL_ALREADY_EXISTS: 'email_already_exists',
    THIRD_PARTY_ACCOUNT: 'third_party_account',
    USER_DELETING: 'USER_DELETING',
    CANNOT_UPDATE_DEFAULT_WORKSPACE: 'cannot_update_default_workspace',
    PASSWORD_EXPIRED: 'password_expired',
    ALREADY_SIGNED_IN_ANOTHER_METHOD: 'already_signed_in_another_method',
    RESTRICTED_ACTION: 'restricted_action_by_domain',
    EXCEEDED_LIMIT_CREATE_SIGNATURE: 'exceeded_limit_create_signature',
    CHATBOT_FREE_REQUESTS_LIMIT_REACHED: 'chatbot_free_requests_limit_reached',
    CHATBOT_DAILY_REQUESTS_LIMIT_REACHED: 'chatbot_daily_requests_limit_reached',
    CHATBOT_SAVE_ATTACHED_FILES_METADATA_FAILED: 'chatbot_save_attached_files_metadata_failed',
    SSO_IS_ENABLED_FOR_EMAIL_DOMAIN: 'sso_is_enabled_for_email_domain',
    USERS_ALREADY_HAVE_SIGN_SEATS: 'users_already_have_sign_seats',
  },
  Payment: {
    INVALID_PRICE_ID: 'invalid_price_id',
    INVOICE_QUANTITY_NOT_ENOUGH: 'invoice_quantity_not_enough',
    CURRENCY_NOT_MATCHED: 'currency_not_matched',
    INVALID_COUPON_CODE: 'invalid_coupon_code',
    COUPON_NOT_FOUND: 'coupon_not_found',
    EXPIRED_COUPON_CODE: 'expired_coupon_code',
    NOT_APPLICABLE: 'not_applicable',
    COUPON_LIMIT_REACHED: 'coupon_limit_reached',
    INVALID_CURRENCY: 'invalid_currency',
    CANNOT_CREATE_ANOTHER_SUBSCRIPTION: 'cannot_create_another_subscription',
    CANNOT_USE_SAME_TRIAL: 'cannot_use_same_trial',
    CANNOT_USE_LOWER_TRIAL: 'cannot_use_lower_trial',
    CANNOT_START_SIGN_TRIAL: 'cannot_start_sign_trial',
    PAYMENT_INCOMPLETE: 'payment_incomplete',
    AUTO_UPGRADE_DOC_STACK_FAILED: 'auto_upgrade_doc_stack_failed',
    CANNOT_START_TRIAL: 'cannot_start_trial',
    ACTION_RESTRICTED: 'action_restricted',
    PAYMENT_NOT_FOUND: 'payment_not_found',
    INVALID_SUBSCRIPTION_ITEMS: 'invalid_subscription_items',
    CANNOT_UPGRADE_SUBSCRIPTION: 'cannot_upgrade_subscription',
    NO_AVAILABLE_SIGN_SEATS: 'no_available_sign_seats',
    USER_ALREADY_HAS_SEAT: 'user_already_has_seat',
    SEAT_REQUEST_ALREADY_REJECTED: 'seat_request_already_rejected',
  },
  Admin: {
    EMAIL_ALREADY_EXISTS: 'email_already_exists',
    ADMIN_NOT_FOUND: 'admin_not_found',
  },
  Question: {
    QUESTION_NOT_FOUND: 'question_not_found',
    CANNOT_CREATE_QUESTION: 'cannot_create_question',
  },
  GrpcService: {
    PLATFORM_MISSING: 'platform_missing',
    INVALID_CLIENT: 'invalid_client',
    MISSING_CLIENT: 'missing_client',
    INVALID_SESSION: 'invalid_session',
  },
  Event: {
    INVALID_EVENT_LIMITATION: 'invalid_evente_limitation',
  },
  Noti: {
    READ_NOTIFICATION_FAIL: 'read_notification_fail',
    READ_ALL_NOTIFICATIONS_FAIL: 'read_all_notifications_fail',
    NOTIFICATION_NOT_FOUND: 'notification_not_found',
  },
  WidgetNoti: {
    CREATE_WIDGET_NOTIFICATIONS_FAIL: 'create_widget_notification_fail',
    PREVIEW_WIDGET_NOTIFICATIONS_FAIL: 'preview_widget_notification_fail',
    READ_WIDGET_NOTIFICATION_FAIL: 'read_widget_notification_fail',
    READ_ALL_WIDGET_NOTIFICATIONS_FAIL: 'read_all_widget_notifications_fail',
    PREVIEW_ALL_WIDGET_NOTIFICATIONS_FAIL: 'preview_all_widget_notifications_fail',
  },
  CommunityTemplate: {
    TEMPLATE_NOT_FOUND: 'template_not_found',
    TEMPLATE_HAS_PUBLISHED: 'template_has_published',
    TEMPLATE_HAS_UNPUBLISHED: 'template_has_unpublished',
  },
  TemplateCategory: {
    CATEGORY_NOT_FOUND: 'category_not_found',
    CATEGORY_NAME_HAS_EXISTED: 'category_name_has_existed',
    HAS_TEMPLATE_BONDED: 'has_template_bonded',
  },
  RequestAccess: {
    REQUEST_ACCESS_NOT_FOUND: 'request_access_not_found',
    REQUEST_ACCESS_ALREADY_SENT: 'request_access_already_sent',
  },
};

enum DefaultErrorCode {
  BAD_REQUEST = 'bad_request',
  UNAUTHORIZED = 'unauthorized',
  NOT_ACCEPTABLE = 'not_acceptable',
  FORBIDDEN = 'forbidden_resource',
  NOT_FOUND = 'not_found',
  CONFLICT = 'conflict',
  INTERNAL_SERVER_ERROR = 'internal_server_error',
  UNPROCESSABLE_ERROR = 'unprocessable_error',
  TOO_MANY_REQUESTS = 'too_many_requests',
}

enum TransactionErrorLabel {
  TRANSIENT_TRANSACTION_ERROR = 'TransientTransactionError',
  UNKNOWN_TRANSACTION_COMMIT_RESULT = 'UnknownTransactionCommitResult',
}

export {
  ErrorCode,
  DefaultErrorCode,
  TransactionErrorLabel,
};
