export default {
  EVENT_INDEX: 'events',
  MINIMUM_SEARCHED_EVENTS: 1,
  MAXIMUM_SEARCHED_EVENTS: 100,
  MAXIMUM_SIZE_DOCUMENTS: 10000,
  SCROLL_ALIVE: '1m',
  MAXIMUM_RESPONSE_BUCKET_SIZE: 10000,
};
